project:
  type: book
lang: pt-br
title-block-author-plural: "Organizadores"  
toc-title: "Sumário"
#number-sections: false
indent: true

book:
  sidebar:
    tools:
      - icon: translate
        href: https://fphap.quarto.pub/pt-psi-en/
  page-navigation: false
  title: "Produções Técnicas em Psicologia"
  subtitle: "Experiências Compartilhadas"
  page-footer:
    right: | 
      Este livro foi construído com <a href="https://quarto.org/">Quarto</a>.
    left:
      <img src="./imagens/ppgpsi.png" width="100"> 
      <img src="./imagens/ppgpppp.png" width="100">
  cover-image: cover_pt.png
  cover-image-alt: |
    A imagem mostra a capa do livro Produções Técnicas em Psicologia: Experiências Compartilhadas. No topo da capa, em fonte menor e de cor preta, estão as siglas PPGPSI e PPGPPPP, seguidas pelo nome Universidade Federal do Ceará, indicando a associação com a instituição. O título principal é apresentado em letras grandes e negrito, com Produções Técnicas em verde e em Psicologia em preto, abaixo do qual está o subtítulo Experiências Compartilhadas em fonte menor e itálico. Centralizado na capa há o desenho de uma ave, um carcará, em voo, com as asas abertas e o corpo voltado para a esquerda, delineado em traços pretos. O pássaro carrega uma cobra em suas garras. Abaixo do desenho, em letras pretas menores, estão os nomes Francisco Pablo Huascar Aragão Pinheiro e João Paulo Pereira Barros, seguidos pela palavra Orgs., sugerindo que são os organizadores da publicação. A capa tem um fundo claro e o design geral é simples.
  repo-url: https://github.com/pablo-huascar/livro_pt_2024.git
  repo-branch: main
  favicon: cover_pt.png
  reader-mode: true
  

  chapters:
    - index.qmd
    - institucional.qmd
    - conselho_editorial.qmd
    - folha_de_rosto.qmd
    - part: Produtos de comunicação
      chapters:
        - barros_podcast.qmd
    
    - part: Eventos organizados
      chapters: 
        - gomes_polifonias.qmd
        - liberato_contagios.qmd
        - vasconcelos_eneddes.qmd
    
    - part: "Relatórios técnicos: assessoria, consultoria e pesquisa"
      chapters:
        - beserra_de_melo_assessoria.qmd
        - costa_interv_criancas.qmd
        - melo_assessoria.qmd
        - rodrigues_relatorio_tecnico.qmd
        - costa_assessoria_saae.qmd
        - sampaio_assessoria.qmd
        - lima_assessoria.qmd
        - vasconcelos_narrativas.qmd
        - soares_psicologia_saude.qmd

    - part: Curso para formação profissional
      chapters:
        - barros_cursos_vieses.qmd
        - bomfim_metodologias_part.qmd
        - martins_clinica_estetica.qmd
        - sena_curso_r.qmd
        - araujo_curso_agentes.qmd
    
    - part: Material didático
      chapters: 
        - da_silva_pandemia_pergunta.qmd
        - lopes_rabiscos_palavras.qmd
        - silva_costa_material_didatico.qmd

    - part: Compilações de vários produtos técnicos
      chapters:
        - barros_assessorias_cursos.qmd
        - miranda_produtos_pesquisa.qmd
    - part: Manual/protocolo
      chapters:
        - barbosa_mini_guia.qmd
        - da_silva_mapas_vizin.qmd
    
    - sobre_os_autores.qmd

format:
  html:
    smooth-scroll: true
    anchor-sections: true
    theme: 
      - cosmo
      - livro_pt.scss
    callout-appearance: simple
    toc: true
    toc_float: true
    toc-depth: 2
    standalone: true
    indent: true
    code-link: true
    code-tools: true  
    code-line-numbers: false
    code-copy: true
  

    author-meta: "Francisco Pablo Huascar Aragão Pinheiro e João Paulo Pereira Barros"

editor: visual
csl: apa.csl


