project:
  type: book
lang: pt-br
title-block-author-plural: "Organizadores"  
toc-title: "Sumário"
#number-sections: false
indent: true

book:
  #sidebar:
    #tools:
      #- icon: translate
        #href: https://fphap.quarto.pub/pt-psi-en/
  page-navigation: false
  title: "Produções Técnicas em Psicologia"
  subtitle: "Experiências Compartilhadas"
  page-footer:
    right: | 
      Este livro foi construído com <a href="https://quarto.org/">Quarto</a>.
    left:
      <img src="./imagens/uva-brasao.jpg" width="100">
  cover-image: cover-pt-uva.png
  cover-image-alt: |
    A capa do livro apresenta o título: Produções Técnicas em Psicologia: Experiências Compartilhadas, seguido pelos nomes dos organizadores: Francisco Pablo Huascar Aragão Pinheiro e João Paulo Pereira Barros. Na parte superior, há o logotipo Edições UVA. O destaque central é uma ilustração em preto e branco de um pássaro em voo, segurando uma cobra estilizada decorada com padrões geométricos.
  repo-url: https://github.com/pablo-huascar/livro_pt_2024.git
  repo-branch: main
  favicon: cover-pt-uva.png
  reader-mode: true
  
  chapters:
    - index.qmd
    - intro_en.qmd
    #- institucional.qmd
    - institucional-uva.qmd
    #- conselho_editorial.qmd
    - conselho-editorial-uva.qmd
    #- folha_de_rosto.qmd
    - folha-de-rosto-uva.qmd
    - part: Produtos de comunicação
      chapters:
        - barros_podcast.qmd
        - barros_podcast_en.qmd
    
    - part: Eventos organizados
      chapters: 
        - gomes_polifonias.qmd
        - gomes_polifonias_en.qmd
        - liberato_contagios.qmd
        - liberato_contagios_en.qmd
        - vasconcelos_eneddes.qmd
        - vasconcelos_eneddes_en.qmd
    
    - part: "Relatórios técnicos: assessoria, consultoria e pesquisa"
      chapters:
        - beserra_de_melo_assessoria.qmd
        - beserra_de_melo_assessoria_en.qmd
        - costa_interv_criancas.qmd
        - costa_interv_criancas_en.qmd
        - melo_assessoria.qmd
        - melo_assessoria_en.qmd
        - rodrigues_relatorio_tecnico.qmd
        - rodrigues_relatorio_tecnico_en.qmd
        - costa_assessoria_saae.qmd
        - costa_assessoria_saae_en.qmd
        - sampaio_assessoria.qmd
        - sampaio_assessoria_en.qmd
        - lima_assessoria.qmd
        - lima_assessoria_en.qmd
        - vasconcelos_narrativas.qmd
        - vasconcelos_narrativas_en.qmd
        - soares_psicologia_saude.qmd
        - soares_psicologia_saude_en.qmd

    - part: Curso para formação profissional
      chapters:
        - barros_cursos_vieses.qmd
        - barros_cursos_vieses_en.qmd
        - bomfim_metodologias_part.qmd
        - bomfim_metodologias_part_en.qmd
        - martins_clinica_estetica.qmd
        - sena_curso_r.qmd
        - sena_curso_r_en.qmd
        - araujo_curso_agentes.qmd
    
    - part: Material didático
      chapters: 
        - da_silva_pandemia_pergunta.qmd
        - da_silva_pandemia_pergunta_en.qmd
        - lopes_rabiscos_palavras.qmd
        - lopes_rabiscos_palavras_en.qmd
        - silva_costa_material_didatico.qmd

    - part: Compilações de vários produtos técnicos
      chapters:
        - barros_assessorias_cursos.qmd
        - miranda_produtos_pesquisa.qmd
    - part: Manual/protocolo
      chapters:
        - barbosa_mini_guia.qmd
        - da_silva_mapas_vizin.qmd
    - part: Software/aplicativo 
      chapters: 
        - ximenes_et_al_aplicativo.qmd
    - sobre_os_autores.qmd
    - sobre_os_autores_en.qmd

format:
  html:
    smooth-scroll: true
    anchor-sections: true
    theme: 
      - cosmo
      - livro_pt.scss
    callout-appearance: simple
    toc: true
    toc_float: true
    toc-depth: 2
    standalone: true
    indent: true
    code-link: true
    code-tools: true  
    code-line-numbers: false
    code-copy: true
  

    author-meta: "Francisco Pablo Huascar Aragão Pinheiro e João Paulo Pereira Barros"

editor: visual
csl: apa.csl


