---
author: 
  - name: João Paulo Pereira Barros
    orcid: 0000-0001-7680-576X
    email: joaopaulobarros@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará    
  - name: Érica Atem Gonçalves Araújo Costa
    orcid: 0000-0002-4341-8138
    email: ericaatem@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Emanuel Meireles Vieira
    orcid: 0000-0002-7346-4944
    email: emanuelmeireles@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Vládia Jamyle dos Santos Jucá
    orcid: 0000-0003-2416-7342
    email: vladiajuca@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Carla Jéssica de Araújo Gomes
    orcid: 0000-0002-6979-2646
    email: carlajessicagomes@alu.ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
language: 
  title-block-author-plural: "Autores"
filters:
  - section-bibliographies
bibliography: barros_assessorias_cursos.bib
reference-section-title: Referências
---

# Assessorias, cursos e tecnologias sociais junto a sujeitos, grupos e instituições de periferias de fortaleza durante a pandemia da covid-19: contribuições do VIESES-UFC para o impacto social da pós-graduação em Psicologia

## O VIESES-UFC e sua atuação no campo das violências, das territorialidades urbanas, das reexistências coletivas, da saúde mental e dos direitos humanos

O VIESES: Grupo de Pesquisas e Intervenções sobre Violência, Exclusão Social e Subjetivação nasceu em abril de 2015 e, desde então, abriga projetos e ações de pesquisa, ensino e extensão, os quais têm acarretado diversas modalidades de produções técnicas e tecnológicas. Está ligado ao Departamento de Psicologia e ao Programa de Pós-Graduação em Psicologia da UFC. Formalmente, tanto está cadastrado no diretório de grupos de pesquisa do CNPq quanto na Pró-Reitoria de Extensão da UFC, na condição de Programa de Extensão.

Esse laboratório vem promovendo ações de médio e longo prazo dentro e fora da universidade em torno dos aspectos psicossociais implicados nas diversas expressões da violência e da exclusão social. Para tanto, tem como horizonte ético a produção de diálogos e alianças entre universidade e outros agentes sociais em diferentes contextos, a fim de responder a demandas sociais prementes na garantia de direitos humanos e potencializar o compromisso e o impacto social das ações da graduação e da pós-graduação em Psicologia no que se refere ao enfrentamento de opressões e violências que marcam a realidade das maiorias populares no Brasil, imprimindo-lhes precarização da vida e sofrimentos diversos.

Seja na graduação ou na pós-graduação, o VIESES incide na qualificação de processos formativos voltados à produção de conhecimento crítico e nas práticas micropolíticas de produção de resistência e criação no cotidiano da cidade de Fortaleza. Com base em referências teórico-epistemológicas diversas no campo da Psicologia, suas práticas se dão em torno das problemáticas da violência e das tramas de exclusão e desigualdade social, em suas diversas expressões, seus contextos e suas interseccionalidades, com destaque para suas implicações nos modos de subjetivação e nas condições de saúde mental – sobretudo de segmentos infantojuvenis – de indivíduos que se inserem em contextos familiares e de profissionais que atuam com esses públicos.

De 2015 a 2019, o grupo realizou diversas ações de pesquisa e extensão em variados contextos urbanos periféricos com elevados índices de violência e desigualdade social, tais como Barra do Ceará, Pirambu, Vicente Pinzon/Serviluz/Titanzinho, Grande Jangurussu, Mondubim e Conjunto Ceará, a partir tanto de políticas públicas quanto de diversas parcerias com movimentos sociais e organizações da sociedade civil, o que mostra a abrangência do impacto social dessas ações, colocando a universidade em conexão com demandas, desafios e potencialidades da cidade a partir de ações realizadas diretamente em comunidades periféricas da capital cearense no que diz respeito à prevenção e ao enfrentamento da violência, bem como de atuação nos efeitos dessas dinâmicas na saúde mental de populações periferizadas. A partir de 2018, o VIESES passou a concentrar suas ações sobretudo na Região do Grande Bom Jardim, também situado na periferia de Fortaleza.

Com essas ações, que articulam pesquisa-extensão e ensino, o objetivo do VIESES é construir espaços coletivos que operem como dispositivos de problematização e transformação dos modos de subjetivação agenciados por dinâmicas de violência e exclusão social na contemporaneidade. Assim, as ações de inserção social do referido laboratório se justificam pela pertinência de se potencializar estudos e intervenções psicossociais em torno dos fenômenos da violência, da exclusão social e da produção de subjetividades na atualidade brasileira, mais particularmente na cearense. Considerando a matriz colonial e as configurações historicamente desiguais da sociedade brasileira – com ênfase aqui para a cearense – e a atualização das práticas de dominação que têm lugar no contexto da produção de subjetividade capitalística, o olhar do VIESES nessas ações considera a interseccionalidade de marcadores sociais de diferença, como classe, raça, gênero, geração e território.

A título de contextualização, o Ceará é o estado do país com maior índice de homicídios na adolescência, sendo Fortaleza a capital brasileira com maior índice de homicídios nessa faixa etária. Essa problemática, por sua vez, afeta de diferentes modos as trajetórias, os cotidianos, as experiências e as condições de saúde mental de diversos segmentos sociais, requerendo ações que articulem a produção de conhecimento acadêmico, na forma de pesquisas no âmbito da pós-graduação, e práticas de extensão que possam, ao mesmo tempo, produzir problemas de pesquisa, tensionar conceitos, fomentar aprimoramentos metodológicos e ampliar as ressonâncias das investigações acadêmicas. Nesse sentido, este tem sido o compromisso do VIESES desde sua criação, sempre em atenção às demandas sociais.

Além disso, estudos como o mapa da violência, o atlas da violência e o anuário brasileiro de segurança pública apontam um processo de agravamento da violência, especialmente no Nordeste. Isso requer fortalecimento de investigações e ações que produzam tanto diagnóstico psicossocial dessa realidade quanto linhas de enfrentamento a esses processos por parte da academia, bem como a articulação desta com outras instituições, cujo foco recaia nos segmentos sociais mais afetados por isso, notadamente pessoas negras, pobres, dissidentes do padrão cis-hetero-patriarcal e periferizadas [@barros2020violencia].

Destaca-se também que a pertinência das ações do VIESES se fundamenta ainda na possibilidade de responder a necessidades sociais prementes a partir de práticas psicossociais que articulem as pesquisas desenvolvidas pelo Grupo no âmbito do Programa de Pós-Graduação em Psicologia da UFC a práticas de extensão e ensino realizadas com a participação de estudantes de graduação em Psicologia. Isso porque assiste-se à intensificação de dinâmicas de exclusão social, de inclusão social perversa, bem como a diversas expressões da violência enquanto dispositivo de governamentalização social nas últimas décadas no Brasil, sobretudo no estado do Ceará, com vultosos impactos na institucionalização, na patologização, na criminalização e no extermínio de determinadas populações, especialmente negras, pobres e periferizadas, as quais, por sua vez, têm se mobilizado de diferentes maneiras para o enfrentamento das condições de matabilidade e (in)visibilização perversa que lhes são imputadas.

Presencia-se, também, o recrudescimento de lógicas punitivo-penais, de processos serializantes de produção de subjetividades e de refinamento de estratégias de controle social atreladas à governamentalidade neoliberal, a qual articula conservadorismo colonial e militarização da vida nas cidades, por meio da intensificação de processos de segregação socioespacial e estigmatização de populações infantojuvenis que habitam as margens urbanas e que são vistas como supérfluas [@mbembe2016necropolitica]. Portanto, a acentuação da violação de direitos humanos, articulada ao que Mbembe chama de necropolítica, ao que a mexicana Sayak Valencia [-@valencia2010capitalismogore] denomina de Capitalismo Gore e ao que Judith Butler [-@butler2015quadros] entende como precarização induzida da vida ou vulnerabilidade interseccional, compele a universidade pública a fortalecer problematizações e intervenções críticas, em diálogo com outros atores sociais que vivem essas situações.

Este capítulo objetiva, portanto, relatar produções técnicas e tecnológicas realizadas pelo VIESES: Grupo de Pesquisas e Intervenções sobre Violência, Exclusão Social e Subjetivação ou pelos profissionais/referências comunitárias, nos anos de 2021 e 2022, especificamente em periferias de Fortaleza. Assim, buscamos realçar contribuições do laboratório para o impacto social do Programa de Pós-Graduação em Psicologia da UFC. Esse recorte temporal foi adotado pelo fato de que, o momento da escrita do capítulo (final de 2022) corresponde ao quadriênio em vigor no âmbito da pós-graduação (a saber: 2021 a 2024).

Considerando as modalidades de produção técnicas e tecnológicas em vigor, indicadas pela avaliação da CAPES, destacamos 3:

-   assessorias a coletivos sociais, movimentos sociais, organizações da sociedade civil e políticas públicas na promoção de ações junto a crianças, adolescentes e jovens;
-   cursos de aperfeiçoamento em temáticas que envolvem a garantia de direitos desses segmentos sociais;
-   tecnologias sociais de promoção de cuidado junto a adolescentes e jovens inseridos em periferias urbanas ou junto a referências comunitárias que atuam nesses contextos.

## Assessoria a projetos, instituições e coletivos do Grande Bom Jardim: fortalecendo práticas de garantia de direitos junto a/com crianças a partir do projeto "Maquinarias: infâncias em invenção"

Em 2021 e 2022, o VIESES deu continuidade a projetos de extensão que realizam práticas de assessoria em 5 bairros da periferia de Fortaleza que compõem a região do Grande Bom Jardim, a qual está entre aquelas com menores Índices de Desenvolvimento Humano e com maiores taxas de crimes violentos letais e intencionais. Ao mesmo tempo, o Grande Bom Jardim notabiliza-se por uma forte organização popular de movimentos sociais, ONGs e coletivos na luta por direitos e contra opressões sociais e estigmatizações que recaem sobre as periferias urbanas.

A seguir, relataremos as assessorias desenvolvidas pelo Projeto “Maquinarias: infâncias em invenção”.

Trata-se de projeto coordenado pela Profa. Érica Atem, que pretende criar dispositivos de problematização dos territórios das infâncias (modos de ver e dizer as experiências das e com as crianças), a partir da sua agência e dos seus modos de participação em contextos periféricos da cidade de Fortaleza. Essa ação responde ao desejo de pensar com as crianças, a partir dos locais em que atuam, para além dos espaços institucionais habituados a acolhê-las e atendê-las. Justifica-se, pois, pela urgência de mudanças epistemológico-políticas nos modos de subjetivação da infância, hegemonicamente vinculados a perspectivas adultocêntricas e excludentes [@junior2020nocao].

O agenciamento com o VIESES enseja justamente ir ao encontro de realidades periféricas da cidade de Fortaleza em que as trajetórias de vida de crianças são silenciadas em seus movimentos de resistência e singularização. Esses movimentos provocam os olhares de especialistas que traduzem esses modos de re(existir) em percursos lineares e conjuntos prescritos de competências por idade. Pela interlocução com as crianças, o Maquinarias pretende atuar diante desta disponibilidade ao descentramento de saberes, tendo como inspiração as políticas cognitivas inventivas [@kastrup2000devircrianca], em que a invenção pode operar como inscrição de outros possíveis, incluindo os modos de fazer, dizer, brincar [@costa2007modos].

Criar dispositivos de problematização dos modos de subjetivação da/na infância a partir do encontro com crianças em territórios periféricos da cidade de Fortaleza emerge como possibilidade de crítica ao adultocentrismo fundante da concepção colonial, moderna, ocidental, universal de infância [@castro2021infancias]. Ouvir as crianças a partir de suas relações sociais no cotidiano tem se configurado epistemológica e politicamente como prática que as produz como agentes e coautoras na produção da realidade.

Para atingir seu objetivo principal, pretende-se alcançar os seguintes objetivos específicos: proporcionar às crianças e àqueles que as endereçam práticas de cuidado e/ou educação espaço para diferentes narrativas sobre suas experiências; criar possibilidades de compreender e ressignificar formas excludentes que invisibilizam a multiplicidade constituinte dessas experiências; cartografar em grupo os movimentos que põem em análise concepções de infância molar/normatizada, identificando rotas alternativas e inventivas criadas coletivamente, assim como seus efeitos para as crianças e para nós, os adultos. O principal recurso teórico-metodológico nas ações do Projeto no Grande Bom Jardim tem sido a proposição de oficinas/encontros com crianças, como lugar de protagonismo e experimentação, de modo que possa vir à tona o movimento inventivo e lúdico do grupo.

O projeto manteve, como uma de suas frentes, em 2021, a parceria na forma de assessoria com a ONG Fábrica de Imagens: ações em cidadania e gênero, cujo objetivo era a participação do coletivo Invenções no III Colorindo o Gênero. O coletivo é composto, em média, por 22 crianças e adolescentes entre 6 e 15 anos, moradoras da ocupação de Nova Canudos. O evento ocorreu virtualmente, em decorrência das adaptações necessárias em função da pandemia da COVID-19. Crianças e adolescentes integraram a curadoria de curtas-metragens, as sessões de debates com diretores, assim como foram convidadas a participar de toda a programação aberta oferecida pelo evento. Dada a desigualdade de acesso à internet e aos aparelhos celulares, marca do contexto das vulnerabilizações de crianças e adolescentes das periferias, esta ação mobilizou outros encontros e conversas em Whatsapp para que pudessem se integrar às atividades. Desde 2020, o projeto tem, em conversas cotidianas e trocas de mensagens e produções (imagens, memes, relatos de vivências), um dispositivo de manutenção de vínculos e criação conjunta, que constituem território existencial e contexto de insurgências de novos problemas e questões comuns.

Também fruto da parceria entre Maquinarias, ONG Fábrica de Imagens, CDVHS e Centro de Cidadania e Valorização Humana (CCVH), o coletivo Invenções, sob a assessoria do Projeto Maquinarias, foi um dos grupos de crianças periféricas convidadas a realizar oficinas de audiovisual que ocorreram no território de Nova Canudos, na sede do CCVH. O grupo aprendeu sobre noções de audiovisual e produziu um curta, registrando suas experiências no território durante o curso e também na Marcha da periferia, encontro em que pautas e lutas relacionadas às periferias se visibilizam na cidade e que contou com a presença de integrantes do coletivo e de extensionistas. O Maquinarias esteve junto na articulação e mobilização das oficinas, acompanhando processos de subjetivação agenciados no encontro entre políticas públicas de cultura, movimentos sociais e direitos de crianças e adolescentes. Desde 2019, o projeto de extensão mantém suas atividades relacionadas ao acompanhamento deste coletivo, fruto ele mesmo do encontro entre Universidade, periferias e crianças, realizando, além do descrito acima, atividades quinzenais (virtuais e/ou presenciais) nas sedes da Associação Comunitária (CCVH) e no CDVHS, que se revezam entre brincadeiras livres, reuniões de planejamento e decisões das próprias atividades do grupo, atividades de manutenção do espaço comunitário e encontros temáticos de interesse das crianças e da comunidade.

A retomada de encontros presenciais marcou o plano de atuação do Maquinarias no território do Grande Bom Jardim, em 2022. As principais frentes de atuação de assessoria vêm se consolidando nas parcerias com a ONG Centro de Defesa da Vida Herbert de Souza (CDVHS), o Centro de cidadania e Valorização Humana (CCVH), a ONG Fábrica de Imagens: ações em cidadania e gênero, a Rede de Desenvolvimento Local, Integrado e Sustentável do Grande Bom Jardim (Rede DLIS), assim como com coletivos juvenis os quais alguns dos adolescentes do Invenções passam a integrar, a exemplo do Grupo Raízes, apoiado pelo Centro de Defesa da Criança e do Adolescente (CEDECA). Como eixo que integra as atividades, permanece o acompanhamento das movimentações do coletivo, diante de mudanças de interesse dos grupos de idade (marca do coletivo), assim como sua maior capilarização pelo território. As condições financeiras para realização das atividades foram fruto do Edital Iniciativas Comunitárias, lançado pelo Centro Cultural do Grande Bom Jardim, equipamento da Secretaria de Cultura do Estado do Ceará (SECULT), com recursos provenientes do Fundo de Combate à Pobreza (FECOP), em que o grupo foi contemplado (e também reconhecido como ação sistemática integrada ao CCVH), em 2020 e 2021.

A extensão tem composto o campo de forças para produção dessas inserções e desses tensionamentos das políticas públicas, tendo em vista se tratarem de crianças e adolescentes periféricos que se experimentam em modos de participação complexos e moventes. A partir desses recursos, destaca-se a realização de trânsitos pela cidade, planejados conjuntamente com o grupo e/ou entre eles, a exemplo das idas à UFC, com visita à sede do VIESES, à biblioteca do Centro de Humanidades (CH), às dependências do Curso de Psicologia e às áreas do CH 2, da participação (durante dois sábados) no IV Colorindo o Gênero, em edição presencial, realizado no Centro Dragão do Mar de Arte e Cultura, e do passeio à Estação das Artes, equipamento da Secretaria de Cultura do Estado (SECULT), recém-inaugurado, o qual oferece atividades voltadas ao público infanto-juvenil aos domingos. É preciso salientar que os deslocamentos pela cidade requerem não só debates sobre o trajeto, a dinâmica de integração e os tipos de atividades, mas também a autorização dos responsáveis e a garantia de alimentação.

Essas ações têm sido foco do trabalho da extensão, uma vez que mobilizam conversas sobre nossas (in)visibilidades e territorialidades periféricas, sobre direito à cidade, sobre desigualdade social e efeitos psicossociais da violência urbana e do racismo, sobre segregação sócio-espacial materializada na cidade, aspectos que constituem interesse das crianças e dos adolescentes e mobilizam a troca de experiências e narrativas. São efetivados encontros presenciais prévios aos passeios, para planejamento, e posteriores, para diálogos sobre as vivências, assim como muitas combinações são mobilizadas entre crianças e adolescentes que se experimentam em comissões e atuam conjuntamente. Sair de Canudos, assim como viver diferentemente o próprio território – a exemplo da ida a parque de diversões nas proximidades do CCVH, escolhido pelo grupo, para cenário de gravação de vídeo sobre o direito ao lazer e à vida – tem sido foco de novas problematizações para pesquisas e conexões com instâncias de luta por moradia e promoção de direitos de crianças e adolescentes no território, como a Rede DLIS.

## Cursos de aperfeiçoamento voltados a juventudes periferizadas e profissionais de políticas públicas

Entre 2021 e 2022, o VIESES realizou, coordenados pelo Prof. João Paulo Pereira Barros e ministrados conjuntamente por estudantes do Programa de Pós-Graduação em Psicologia da UFC e por pessoas convidadas, os seguintes cursos:

### (Re)Existir nas encruzilhadas: diálogos sobre relações raciais, gênero e juventudes

Esse curso visou construir diálogos e aprofundamentos teóricos-metodológicos e vivenciais acerca dos atravessamentos das relações de raça e de gênero nos processos de subjetivação em contextos de periferias urbanas, que são atravessadas por condições não só de opressão, mas também de reexistências de juventudes inseridas nessas territorialidades periferizadas, engajadas nos desafios para a promoção de políticas públicas de garantia de direitos humanos e para a produção de cuidado frente aos sofrimentos produzidos pelo racismo, pela LGBTQIP+fobia e pelas suas interseccionalidades. O curso foi voltado a estudantes de Psicologia e áreas afins, profissionais e gestores de políticas públicas, integrantes de organizações da sociedade civil, juventudes LGBTQIAP+ do Grande Bom Jardim e comunidade em geral interessada na temática e nas discussões.

A carga horária total da atividade foi de 36 horas, ocorrendo entre os meses de outubro e dezembro de 2022. Os quatro primeiros módulos foram realizados no departamento de Psicologia da UFC, e os restantes no Centro de Defesa pela Vida Herbert de Souza (CDVHS), a fim de fortalecer a troca e produção de conhecimentos entre a universidade e a comunidade, visto que pelo menos 40% dos 45 participantes eram parte do GBJ.

Foram 8 módulos propostos:

1.  Gênero: aspectos históricos, conceituais e seus atravessamentos nas trajetórias e experiências juvenis;
2.  Relações Raciais: aspectos históricos, conceituais e seus atravessamentos nas trajetórias e experiências juvenis;
3.  Efeitos psicossociais do racismo e da LGBTQIA+fobia na saúde mental de juventudes;
4.  Desigualdades de gênero e desafios para políticas públicas e garantia de Direitos Humanos;
5.  Racismo e desafios para políticas públicas e garantia de Direitos Humanos;
6.  Práticas de cuidado e enfrentamento à LGBTQIA+fobia: desafios e experimentações teórico-epistêmicos e clínico-políticos;
7.  Práticas de aquilombamento e políticas do cuidado frente ao racismo: desafios e experimentações teórico-epistêmicos e clínico-políticos;
8.  Diálogos Interseccionais entre raça, gênero, classe, geração e território: experiências e reexistências coletivas de juventudes em periferias urbanas.

### Ciclos de diálogos formativos sobre psicologia e políticas públicas

Em 2021, realizamos 2 edições do curso intitulado “Diálogos formativos sobre psicologia e políticas públicas”, ambos com carga horária de 20hs. Cada um deles será relatado a seguir.

A primeira edição recebeu o sobrenome de “Preconceito e estigma: desafios para as políticas públicas” e ocorreu nos meses de agosto e setembro de 2021. Seu objetivo foi o de fomentar o debate acerca das diversas formas de preconceito e estigma no Brasil e dos impactos destes na atuação em políticas públicas. Tal curso direcionou-se a profissionais das políticas públicas de Saúde, de Assistência Social e de Educação, bem como àquelas(es) atuantes em Movimentos Sociais, OSC e ONGs, cujo escopo fosse a defesa dos Direitos Humanos em contextos periféricos. A estrutura elaborada foi de cinco encontros semanais de 3 horas/aula via Google Meet, sendo quatro síncronos e um assíncrono, além de cinco vídeos complementares abordando as temáticas escolhidas no formulário de inscrição. Foi solicitado ainda que as(os) participantes registrassem um relato (anônimo ou não) de situações de discriminação vivenciadas, observadas ou relatadas por terceiros às/aos profissionais no contexto das políticas públicas. Esse material foi utilizado como disparador de discussões no final do segundo, terceiro e quarto encontro, em que foram tratados temas específicos de discriminação.

Os módulos desse primeiro ciclo foram:

1.  “Preconceito e Estigma, Direitos Humanos e políticas públicas”;
2.  “Homofobia e Estigma em relação a pessoas LGBTQIAP+”;
3.  “Racismo, preconceito e estereótipos de raça/cor”;
4.  “Sexismo e Classismo”; e
5.  “Agravamentos dos efeitos do preconceito e do estigma no contexto da COVID-19”.

Já a segunda edição do curso recebeu o sobrenome “Avaliação, monitoramento de políticas públicas e estratégias a partir da psicologia social”. Seu objetivo foi apresentar ferramentas e estratégias para conhecer as políticas públicas e suas(seus) usuárias(os), fomentando diálogos a partir da psicologia social. O diferencial dessa segunda edição, que estava direcionada ao mesmo público da primeira, foi apresentar uma perspectiva psicossocial de avaliação e monitoramento de políticas públicas com ênfase na proteção dos Direitos Humanos, trazendo exemplos de estratégias alternativas de monitoramento e avaliação, bem como fornecendo ferramentas para sua aplicabilidade.

As temáticas abordadas nos 5 módulos dessa edição foram as seguintes:

1.  “Monitoramento e avaliação de políticas públicas e outras estratégias para conhecer as políticas públicas e suas(seus) usuárias(os)”;
2.  “Políticas públicas e Direitos Humanos”;
3.  “Diálogo, planejamento e ação: experiências de levantamento e as caravanas do conhecimento”;
4.  “Estigma e preconceito: impactos negativos para as políticas públicas”; e
5.  “Dificuldades e potencialidades da implementação das estratégias”.

Esses ciclos formativos tiveram um desdobramento prático, especialmente em decorrência da segunda edição, que foi a colaboração, por parte do VIESES, com a avaliação e o monitoramento das políticas de assistência social (CRAS e CREAS) no território do Grande Bom Jardim (GBJ), por parte da Rede DLIS. Essa rede é uma instância cívica popular territorializada de luta por direitos fundada em 2003, que articula 26 entidades locais, movimentos da sociedade civil organizada e parceiros externos da sociedade civil e das entidades acadêmicas.

Para esse processo, formou-se um grupo de trabalho composto por pessoas da rede, do território e do VIESES, com encontros periódicos pelo Google Meet. O objetivo principal daquele grupo foi construir e realizar uma proposta de avaliação e monitoramento dos CRAS e do CREAS do território, no contexto das limitações impostas pela pandemia, tomando como base a estratégia da Caravana do Conhecimento, adotada em uma experiência de avaliação e monitoramento anterior realizada pela rede DLIS. O alcance delimitado para a Caravana 2021 foi o de um CREAS e três CRAS, totalizando 100 usuárias dessas políticas.

### "De(s)colonizando o campo da saúde mental e da atenção psicossocial no Ceará"

Tal curso ocorreu nos meses de abril e maio de 2022, contando com a participação de 15 pessoas, e foi destinado a profissionais negros/as atuantes na Rede de Atenção Psicossocial do estado do Ceará (Atenção Básica, CAPS, Residência Terapêutica, Hospitais com leitos psiquiátricos, Unidades de Desintoxicação, Unidades de Acolhimento, Upas, Consultórios na e da rua, etc). O espaço se apresentou como dispositivo de pesquisa, de partilha, de educação permanente, de fortalecimento das redes e das lutas antirracista e anticolonial, além de ser também ambiente de compartilhamentos de novos horizontes a partir do encontro de trabalhadoras/es negras/os.

Com a carga-horária de 20 horas/aula, os módulos foram inspirados nos resultados do estudo 1 da tese de doutorado “Por uma de(s)colonização da Saúde Mental: vozes negras na produção do campo da Atenção Psicossocial no Ceará”, produzida no Programa de Pós-Graduação em Psicologia da UFC. Os módulos se organizaram em quatro partes, quais sejam:

a.  aspectos históricos, epistemológicos e políticos da saúde mental e da Reforma Psiquiátrica Brasileira;
b.  efeitos do racismo nas condições de saúde mental de negros/as e nas práticas institucionais produzidas no campo da atenção psicossocial;
c.  gênero, raça, sexualidade, classe, geração e território como determinantes em saúde mental e;
d.  práticas de(s)coloniais e interseccionais de cuidado com populações negras.

Considerando a problemática do colonialismo e do racismo, que produzem efeitos na saúde mental da população negra, expressando-se em diferentes dispositivos de poder, buscamos questionar a ausência do debate étnico-racial e colonial na proposta da Luta Antimanicomial, da Reforma Psiquiátrica Brasileira e do Sistema Único de Saúde (SUS). Partindo dessa problematização e da proposta de um movimento contra colonial frente a espaços acadêmicos embranquecidos, que historicamente negaram/ocultaram/apagaram epistemologias negras, pretendemos dialogar com profissionais negros/as afirmando politicamente outras epistemologias apagadas na formação em saúde.

## Tecnologias sociais de promoção de saúde junto a sujeitos e grupos inseridos em contextos periféricos

Destacaremos, nesta seção, tecnologias sociais que articulam diferentes projetos do VIESES-UFC.

### Tecnologia social de produção de cuidado desenvolvida pelo projeto “Histórias desmedidas: grupos de apoio psicossocial e cuidado compartilhado a pessoas em situação de vulnerabilidade social”

Desde 2020, o Projeto de Extensão Histórias Desmedidas, ligado ao VIESES, ao qual também estão articuladas diversas pesquisas de dissertação e tese no âmbito do PPG Psicologia UFC, desenvolveu, sob a coordenação do Prof. João Paulo Barros, uma série de grupos de apoio psicossocial e cuidado compartilhado com diversos segmentos sociais em contextos diferenciados de vulnerabilização social, a saber: lideranças comunitárias, mães de jovens assassinados/as e pessoas LGBTQIAP+. Consideramos tais experiências como ações de inserção social de atenção à saúde e abordaremos, sucintamente, cada uma delas a seguir.

O primeiro desses grupos foi o Grupo Virtual de Apoio Psicossocial a Referências Comunitárias de Fortaleza. Ele aconteceu entre abril e junho de 2020, em parceria com o Projeto Ser Ponte Fortaleza, criado em março daquele ano, com a deflagração da pandemia, para ajudar, por meio de renda básica, núcleos familiares chefiados por mulheres na capital cearense que não contavam com auxílios do governo nem de organizações não-governamentais. Com o agravamento das situações de precarização das comunidades onde vivem tais famílias, as próprias lideranças comunitárias parceiras do Ser Ponte Fortaleza passaram a relatar a agudização de seus sofrimentos psicossociais, demandando ações de cuidado em saúde mental daquele projeto. Por isso, a organização daquele projeto mobilizou profissionais de psicologia dispostos a atuar junto a tais referências no formato remoto, fosse na forma de atendimentos individuais, fosse na de grupos de apoio psicossociais. Assim, o projeto Histórias Desmedidas colaborou com o Ser Ponte Fortaleza por meio da proposição de um grupo de apoio psicossocial a referências comunitárias atuantes em periferias de Fortaleza em condições de sofrimento decorrentes ou agravadas pela pandemia da COVID-19. Esse grupo aconteceu em 7 encontros, facilitados pelos Professores Emanuel Meireles e João Paulo Barros, por meio da plataforma Google Meet, e contou com a participação de 10 referências comunitárias.

Outro dispositivo grupal desenvolvido durante a pandemia da COVID-19 foi o grupo de escuta, apoio psicossocial e produção de cuidado compartilhado com o coletivo “Mães da Periferia”, composto por mulheres que tiveram seus/suas filhos/as assassinados/as pela violência policial no Estado do Ceará. A ação articulou a prática extensionista ao desenvolvimento de uma pesquisa de doutorado ligada ao VIESES-UFC. A facilitação do grupo se deu em parceria do VIESES com o Observatório de Direitos Humanos da UNIFANOR, coordenado pela Profa. Dra Ana Vládia Holanda Cruz. Os encontros do grupo ocorreram quinzenalmente, no período de março a dezembro de 2021, pela plataforma Google Meet, e buscaram trabalhar questões em torno de temáticas levantadas em conjunto com as mulheres a cada encontro. O grupo visava fortalecer não só o coletivo em suas lutas por memória e justiça, mas também os processos coletivos e singulares de elaboração da experiência de perda dos filhos/as e de produção de cuidado em saúde mental das participantes.

Outra tecnologia social realizada pelo Histórias Desmedidas durante a pandemia foi a criação de grupos de escuta, acolhimento e produção de cuidado compartilhado com pessoas LGBTQIAP+. Tal produto técnico e tecnológico, desenvolvido remotamente, contou com duas edições: a primeira entre maio e julho de 2021, a segunda entre novembro e dezembro do mesmo ano. A partir destes dispositivos grupais, buscou-se potencializar a ressonância de vozes LGBTQIAP+ a partir da criação de um espaço de compartilhamento de narrativas e histórias de vida e de acolhimento coletivo. Os encontros do grupo aconteceram pela plataforma Google Meet. No total, foram realizados 8 encontros síncronos na primeira edição e 5 encontros síncronos na segunda, com uma média de 10 participantes, entre 16 e 39 anos, em cada uma das edições.

Em 2022, o Projeto desenvolveu também um grupo presencial de apoio psicossocial com jovens LGBTQIAP+ em uma escola pública de Ensino Médio do Grande Bom Jardim que compõe o Fórum de Escolas pela Paz do GBJ. Seu objetivo foi viabilizar um espaço de escuta, produzir cuidado em uma perspectiva da coletividade e da promoção de direitos humanos, a fim de que essas juventudes pudessem ser acolhidas e compartilhar suas experiências, suas vivências de sofrimento atravessadas não somente pela LGBTQIAP+fobia como também pelo racismo e pelas outras discriminações e violências, perpassadas por condições de invisibilidade, precarização da vida e dificuldade na permanência escolar. O grupo contou com a participação de 11 jovens do Ensino Médio, entre 15 e 17 anos, e foram realizados 6 encontros.

### Projeto escutas sensíveis: atenção às urgências subjetivas de juventudes inseridas em periferias urbanas

Também nessa perspectiva de criação de produtos técnicos e tecnológicos ligados à promoção de cuidado em saúde mental em periferias urbanas, podemos situar outro projeto desenvolvido pelo VIESES, intitulado Escutas Sensíveis, criado em 2018, no início da inserção do VIESES nos bairros que compõem a região periférica de Fortaleza conhecida como Grande Bom Jardim. O referido projeto surgiu quando da elaboração de um plano de trabalho coletivo para a atuação de extensão e pesquisa do nosso laboratório naquele contexto. Essa elaboração contou com a participação de referências comunitárias, jovens moradores, trabalhadores sociais, representantes de organizações governamentais e não governamentais atuantes no Grande Bom Jardim. O Escutas Sensíveis, nome proposto por uma das referências comunitárias do território, surgiu a partir da demanda de que fossem criados espaços individuais e grupais de atenção à saúde de pessoas do Grande Bom Jardim em condições de sofrimento agravadas ou desencadeadas pelo acirramento das dinâmicas de violência e desigualdade naqueles bairros.

O Escutas Sensíveis tem funcionado, desde 2020, em parceria com o Centro Cultural do Bom Jardim (CCBJ), sob a coordenação conjunta da Profa. Vládia Jucá e do Prof. João Paulo Barros, como um projeto voltado para o cuidado em saúde mental dos jovens matriculados nos cursos ofertados pela instituição nas seguintes áreas: dança, teatro, audiovisual e música. Essa ação de inserção social do VIESES tem adotado, desde seu surgimento, então, a perspectiva de construir as estratégias de cuidado com esses grupos – e não para eles – a partir das potencialidades e necessidades de seus territórios, realizando uma escuta das questões referentes ao sofrimento psíquico sensível à sua dimensão sociopolítica. Além disso, visa colaborar, a partir dessas escutas, com a produção coletiva de enfrentamentos às violências e violações de direitos que matam e mortificam as juventudes periferizadas, juntando-se às mobilizações que historicamente têm sido criadas por movimentos sociais, entidades e coletivos do Grande Bom Jardim.

Desde sua criação, o projeto foi estruturado com duas vertentes de ações: a realização de espaços coletivos de discussão sobre o sofrimento psíquico com seus atravessamentos diversos e a oferta de um espaço de acolhimento individual em até oito encontros para aqueles que estavam em uma situação de urgência subjetiva. Vale ressaltar que essa foi nossa oferta primeira, mas o Escutas, baseado no pressuposto do fazer com os jovens e com os educadores, sempre esteve aberto a construir outros dispositivos de cuidado, a partir das trilhas delineadas no cotidiano de trabalho.

Como foi assinalado anteriormente, a parceria com o Centro Cultural do Grande Bom Jardim para direcionar as ações do Escutas Sensíveis prioritariamente a jovens atendidos por tal equipamento público teve início em 2020. Contudo, com a deflagração da pandemia, foram necessários ajustes na sua operacionalização. Passamos a realizar os acolhimentos individuais no formato remoto, bem como rodas de conversa com jovens matriculados nos cursos. Ainda em 2020, com os impactos da pandemia na saúde mental e os pedidos de ajuda oriundos de outros projetos e outras instituições do território, ampliamos nossa oferta para jovens matriculados nas escolas de Ensino Médio que compõem o fórum de escolas do Bom Jardim.

Ainda na travessia da pandemia, algumas atividades presenciais foram retomadas no segundo semestre de 2021. Em decorrência desse contexto, nos primeiros meses do ano, mantivemos os acolhimentos individuais no formato remoto e, no segundo, resolvemos sustentar essa oferta nos dois formatos (online e presencial). Fizemos algumas tentativas de retomar as rodas de conversa com as(os) estudantes do CCBJ, mas esbarramos em algumas dificuldades operacionais, visto que o Centro foi voltando às atividades de modo progressivo. Além disso, era difícil, naquele momento, mobilizar os jovens para atividades mais coletivas em função da exaustão generalizada decorrente da pandemia, além dos vários outros problemas sociais que foram agravados pelo contexto pandêmico e afetaram sobretudo os jovens em vulnerabilidade social.

Seguimos com o projeto em 2022, mas, no início do ano, passamos por outro obstáculo para as atividades coletivas, quando o CCBJ entrou em reforma, não sendo possível ocupar os espaços do Centro. Contudo, esse tem sido um ano no qual o trabalho com as escolas tem se fortalecido. No primeiro semestre de 2021, foram realizadas cinco rodas de conversa em uma escola do Ensino Fundamental II, com adolescentes de 12 a 15 anos, nas quais discutimos as questões atreladas ao sofrimento psíquico, à pandemia e à forma como esta afetou suas vidas, à rede social com a qual contavam e às estratégias utilizadas para atravessarem os momentos difíceis.

Vale destacar que chegamos até essa escola a partir do convite de uma aluna da instituição, a qual participava de outro projeto do VIESES, o “Maquinarias”. A aluna pediu que alguma intervenção em saúde mental fosse realizada na sua escola, onde muitas(os) estudantes apresentavam sinais de sofrimento psíquico. O trabalho na escola foi muito bem recebido pela comunidade escolar. Pactuamos, por fim, com as(os) adolescentes que participaram das rodas nosso retorno para realização de oficinas nas quais trabalharemos os temas apontados como produtores de mal-estar. Além disso, uma parceria com uma segunda escola, uma instituição de Ensino Médio e profissionalizante, foi realizada também em 2022. Com os estudantes dessa escola, foram realizadas oito rodas de conversa. Foi possível perceber uma diferença significativa nas questões atreladas ao sofrimento de acordo com os cursos profissionalizantes nos quais as(os) participantes estavam matriculadas(os). Dessas rodas, também surgiu a demanda de oficinas temáticas.

Além das ações descritas acima, o Escutas também tem realizado com a equipe do CCBJ outras ações mais pontuais que surgem no cotidiano de trabalho, em formatos diversos. No planejamento para 2023, é uma prioridade para o projeto fortalecer as ações nas escolas, trabalho que tem se mostrado muito profícuo. Com os jovens do próprio CCBJ, nosso intuito é repensarmos as estratégias para fazer acontecer os espaços coletivos.

## Assessoria a comitês, conselhos e comissões para o monitoramento e a proposição de políticas públicas de prevenção e enfrentamento à violência

Por fim, cabe destacar que o VIESES também tem assessorado conselhos, comissões e comitês diversos, assim como de instâncias de organização de Movimentos sociais. Para tanto, busca fortalecer a incidência social do Programa de Pós-Graduação em Psicologia no monitoramento e na proposição de políticas públicas de prevenção e combate à violência que atinge segmentos sociais em condições de maior desigualdade em contextos urbanos.

A título de exemplificação, o VIESES integra o Conselho Consultivo do Comitê Cearense pela Prevenção de Homicídios na Adolescência, uma iniciativa da Assembleia Legislativa do Ceará e do UNICEF. Colabora também com a Comissão de Monitoramento do Sistema Socioeducativo do Fórum DCA-CE e participa do Fórum Popular de Segurança Pública do Ceará, que, por sua vez, integra o Fórum Nordestino de Segurança Pública. O laboratório, em acréscimo, faz-se presente no Comitê Estadual de Combate à Tortura e foi convidado a integrar a comissão de especialistas do CREPOP, do Conselho Federal de Psicologia, para proposição e aprimoramento de referências técnicas para atuação do psicólogo em políticas públicas. Desde o ano de 2018, colabora com a Rede de Desenvolvimento Local, Integrado e Sustentável do Grande Bom Jardim (Rede Dlis), composta por coletivos, Ongs, universidades, associações e grupos comunitários, com atuação no campo da defesa e promoção de direitos humanos, pela construção coletiva e participação popular, para incidência junto às políticas públicas voltadas ao território e outras periferias.

## Considerações finais: contribuições do VIESES para o impacto social do programa de pós-graduação

As assessorias, as tecnologias sociais e os cursos de aperfeiçoamento desenvolvidos pelo VIESES e relatados ao longo deste capítulo conferem abrangência local, estadual, regional e nacional ao impacto social do Programa de Pós-Graduação em Psicologia da UFC. Consequentemente, potencializam o impacto social do Programa no que se refere à pauta do enfrentamento da violência e das desigualdades sociais no país.

Notadamente, a relevância dessas produções técnicas e tecnológicas está no fato de que a violência é um dos problemas sociais mais prementes da realidade brasileira, estruturalmente desigual, por sua herança colonial, sendo o Nordeste uma das regiões onde a violência contra segmentos infantojuvenis mais têm crescido nas últimas décadas [@barros2020violencia]. Essas várias PTTs atendem a demandas institucionais, no que tange a políticas públicas, e sociais, no que se refere, na sociedade civil, à produção de evidências, recomendações e intervenções acerca dos aspectos psicossociais da violência que sustentam a violência.

As PTTs supracitadas do VIESES também atendem à demanda de participação da universidade nas mobilizações por garantia de direitos humanos e à produção de cuidado em saúde mental no contexto de agravamento de sofrimentos psicossociais relacionados às tramas de opressão e desigualdades sociais. As ações relatadas possuem alto grau de complexidade, devido à sua variedade, por articularem pesquisa e extensão, reverberando em ações formativas, e por envolverem diferentes aportes teórico-metodológicos em sua execução. Requerem, ainda, articulações sociais e institucionais com organizações as mais diversas que atuam em periferias de Fortaleza com as mais elevadas taxas de letalidade da capital cearense. Além disso, as ações possuem alto potencial de replicabilidade, devido a estarem assentadas em bases sociais, institucionais e comunitárias construídas dialogicamente pelo VIESES com segmentos estratégicos nas periferias da cidade, e a serem acompanhadas por significativas sistematizações teóricas, permitindo aprendizados e aprimoramentos por parte das equipes envolvidas.
