---
author: 
  - name: João Paulo Pereira Barros
    orcid: 0000-0001-7680-576X
    affiliations: 
      - name: Universidade Federal do Ceará    
  - name: Lucia Maria Bertini
    orcid: 0000-0001-7498-6640
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Larissa Ferreira Nunes
    orcid: 0000-0001-5384-0896
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Carla Jéssica de Araújo Gomes
    orcid: 0000-0002-6979-2646
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Lívia Lima Gurgel
    orcid: 0000-0003-2095-2415
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Aldemar Ferreira da Costa
    orcid: 0000-0003-0281-9944
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Laisa Forte Cavalcante
    orcid: 0000-0002-6523-847X
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: José Dannilo Ferreira Marques Arruda
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Antônio Gabriel Miranda da Silva
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Lucas Araújo da Silva
    orcid: 0000-0002-6491-4659
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Davi Lucas Moraes
    orcid: 0009-0008-9075-8494
    affiliations: 
      - name: Universidade Federal do Ceará
language: 
  title-block-author-plural: "Autores"
filters:
  - section-bibliographies
bibliography: barros_cursos_vieses.bib
reference-section-title: Referências
---

# Cursos de extensão do VIESES-UFC: diálogos contracoloniais em Psicologia

## Introdução

Este capítulo propõe-se a relatar experiências de realização de cursos de extensão promovidos pelo VIESES: Grupo de Pesquisas e Intervenções sobre Violência, Exclusão Social e Subjetivação, entre 2019 e 2022. Tal laboratório, por sua vez, integra o Departamento de Psicologia e o Programa de Pós-Graduação em Psicologia da Universidade Federal do Ceará (UFC). A seguir, serão relatadas as experiências de processos formativos propiciados por 5 cursos de extensão que visaram fortalecer diálogos contracoloniais na seara da Psicologia, ao tocarem em temática que questiona matrizes coloniais de saber-poder-subjetivação, pautando temas como relações raciais, gênero e desigualdades na Psicologia e tensionando políticas públicas a escutar e reconhecer existências subalternizadas.

## Curso de extensão “Racismo, saúde mental e práticas de cuidado”

Este curso teve como proposta discutir os efeitos do racismo na saúde mental de negras e negros e os desafios do cuidado junto a essa população no campo da Atenção Psicossocial. Tal iniciativa se desenhou considerando a problemática do racismo estrutural, que se expressa nas relações sociais, políticas, jurídicas e econômicas, sendo uma das principais desencadeadoras de sofrimento psíquico das populações negras no Brasil [@almeida2018racismoestrutural].

Historicamente, no Brasil, a população negra foi relegada às margens da sociedade, vivenciando diferentes formas de opressão e exclusão social [@heringer2002desigualdades; @igreja2016combate; @damasceno2018saude]. No que concerne aos estudos raciais brasileiros, Nogueira [-@nogueira2006preconceito] aponta para uma tendência à negação do preconceito racial, uma espécie de apagamento das situações de racismo e abrandamento das tensões que envolvem a manutenção do privilégio branco, o que caracteriza o mito brasileiro da democracia racial [@nascimento2017genocidio].

Dessa forma, depreende-se que as relações sociais, econômicas e políticas que sustentam o racismo estrutural tendem a sofrer amenizações, de modo que os sofrimentos em decorrência das situações de opressão podem ser resumidos ao âmbito individual. Pesquisas sinalizam a necessidade de discutir os efeitos do racismo na saúde mental das populações negras [@cuevas2013mediators; @pieterse2012perceived; @faro2011raca; @jones2016future]. Isso porque, estruturalmente, o racismo tem movimentado uma distribuição desigual de recursos e um pior acesso à educação, à saúde, à habitação, à justiça e ao trabalho.

Além disso, algumas questões merecem maior atenção, como, por exemplo: 1) a associação entre racismo percebido/discriminação e alguns transtornos mentais [@tavares2018repercussoes]; 2) a maior vulnerabilidade da população negra diante de transtornos mentais e a dificuldade de autocuidado da população dessa parcela frente às violências cotidianas. Em termos de políticas públicas no Brasil, as questões étnico-raciais já vêm sendo pautadas, especialmente no âmbito do SUS, com a Política Nacional de Saúde Integral da População Negra. Entretanto, apesar de alguns avanços, reconhecem-se desafios na efetivação dessa política, assim como a necessidade de intensificação dos debates e das conquistas em torno das questões raciais e dos seus impactos.

O curso foi realizado como desdobramento de atividades de pesquisa e extensão desenvolvidas pelo VIESES-UFC, que, na condição de Programa de Extensão, tem promovido ações de médio e longo prazo que articulam pesquisa, extensão e ensino em torno dos aspectos psicossociais implicados e decorrentes das diversas expressões da violência e da exclusão social, com vistas primordialmente à produção de intercessões entre a universidade e os outros agentes sociais.

O público do curso foi constituído por trabalhadoras e trabalhadores da Rede de Atenção Psicossocial de Fortaleza, estudantes de Psicologia e/ou de outras áreas e outras pessoas da comunidade interessadas na temática. A proposta foi estruturada através de módulos, totalizando a carga horária de 44 horas/aula, ao longo das quais enfatizamos temas concernentes aos aspectos históricos e conceituais dos estudos de racismo e seus impactos:

1.    módulo I: Racismo: aspectos históricos e conceituais sob um prisma anticolonial em diálogos com a Psicologia Social (8 horas); 
2.    módulo II: Racismo e interseccionalidade (8 horas); 
3.    módulo III: Racismo e saúde mental (8 horas); 
4.    módulo IV: Práticas de cuidado frente aos efeitos do racismo na saúde mental (8 horas); 
5.    módulo V: Práticas de cuidado frente aos efeitos do racismo na saúde mental (8 horas).

Participaram do curso 45 pessoas.

Consideramos importante abordar o racismo também a partir de um prisma interseccional, uma vez que as opressões de raça se articulam às de classe, gênero e território. Por isso, utilizamos abordagens metodológicas participativas que fomentaram a troca de experiências dos participantes acerca das questões raciais e da formação de um grupo potente no qual se vivenciaram práticas de cuidado e resistência frente às expressões do racismo no cotidiano, pautadas em perspectivas crítico-reflexivas, a partir das vivências nos territórios.

Os cinco módulos do curso se orientaram pela relação: aulas-cenários de práticas, problematizando realidades vivenciadas, baseando-se, ao mesmo tempo, em diretrizes legais, conceituais, metodológicas e práticas. Foram utilizados documentos, textos, pesquisas e políticas nacionais, estabelecendo uma multiplicidade de diálogos com várias disciplinas, além do desenvolvimento de práticas de cuidado antirracistas no campo da Atenção Psicossocial.

## Curso de extensão “Psicologia e direitos humanos: experiências, diálogos e (des)construções”

O curso aconteceu no período entre 23 de março e 14 de abril de 2021 e teve como objetivo abordar criticamente temáticas que estão ligadas à Psicologia e aos Direitos Humanos, a partir de relatos de experiências profissionais, resultados de pesquisas e reflexões teóricas. Essa iniciativa se desenhou considerando os atravessamentos entre a defesa de Direitos Humanos e a produção de conhecimento e de intervenções em Psicologias, sendo relevante para a atuação profissional e acadêmica em seus mais diversos âmbitos [@bicalho2009formacao; @bock2010direitoshumanos; @coimbra2001psicologia; @scisleski2015juventude]. O campo dos Direitos Humanos tem sido território de intensa disputa por forças reacionárias, a fim de excluir diferentes existências da condição de sujeitos a quem devem ser garantidos direitos fundamentais [@barros2019criminalizacao]. Por isso, é de extrema relevância que a universidade pública, em especial os cursos de Psicologia, paute, de maneira crítica, plural e rigorosa, tais temáticas, a fim de desnaturalizar os aspectos psicossociais que corroboram historicamente a produção de sujeitos “desimportantes”, “matáveis” e “morríveis” [@barros2019juventudes], assim como expressões necropolíticas [@barros2019criminalizacao; @mbembe2017politicas] que produzem zonas de morte e modos de subjetivação indiferentes ao extermínio desses sujeitos.

A construção do campo dos Direitos Humanos é vasta e complexa, nasce a partir de uma perspectiva universalista de humanidade, a qual coloca a essência do homem no centro, fruto de uma burguesia aristocrata [@nascimento2015transvalorizando], sendo necessário pensar esse tema a partir de um posicionamento crítico-reflexivo. É preciso historicizar esse campo, fruto de uma suposta evolução em busca do progresso do gênero humano [@hunt2009invencao], para que não ocorra uma naturalização hegemônica dos Direitos Humanos, pois ele é produto de práticas sociais, transformado, muitas vezes, em campo de atuação de “especialismos”. Essa forma de controle social e enquadramento da humanidade é perpassada pelo colonialismo europeu, que historicamente se atualiza e estrutura o sistema mundo moderno/colonial [@lugones2014rumo]. Assim, uma abordagem transdisciplinar e decolonial é fundamental para ampliar o escopo dessa temática, entendendo-a como relevante para o atual contexto de desafios de defesa da democracia brasileira e enfrentamento das crescentes violências e desigualdades sociais e raciais, às quais se somam as de gênero.

O colonialismo é fenômeno econômico e político que está nas origens da estruturação das ciências e está epistemologicamente vinculado ao nascimento das ciências humanas, em que diversas opressões de gênero, de etnia e raça estão em jogo, bem como as identidades de colonizadores e colonizados criadas na sua estruturação, eurocentricamente estabelecida [@ballestrin2013america]. A superação das relações de colonização, colonialismo e colonialidade foi colocada na pauta do curso levando em conta os saberes trazidos por Fanon e Césaire, entre outros autores, que desconstroem a “produção do conhecimento no exercício de dominação sobre o outro” [@ballestrin2013america, p. 93]. Do mesmo é preciso pensar a noção de subalternidade, conforme [@figueiredo2010estudos], a respeito de pessoas e grupos que são considerados subalternos por estarem fora do poder da estrutura hegemônica nos estudos teóricos críticos asiáticos e latinoamericanos, que, com Spivak [-@spivak2020subalterno], apontam uma produção intelectual ocidental atravessada pelo imperialismo e pelos interesses econômicos internacionais, fazendo-se fundamental o exercício de decolonizar a Psicologia e a compreensão tradicional dos Direitos Humanos. Ambos estão fundados sob o poder da elite europeia que produz subjetividades capitalísticas [@guattari1996micropolitica], assim como a compreensão de uma cultura ocidental, globalizada, neoliberal e individualista da sociedade, permeada pela produção desigual de existências e epistemicídios [@santos1997concepcao]. Este quadro complexo foi referência para a proposição do curso em uma compreensão crítica do conhecimento para a decolonização da Psicologia.

A fim de se movimentar na contramão de abordagens acríticas e reducionistas sobre o assunto, o curso teve como referências teóricas os principais pensadores e pensadoras da Psicologia e das áreas afins que problematizam os padrões “cis-hetero-patriarcal-coloniais”, o racismo estrutural, as desigualdades sociais, raciais, bem como as de gênero, e os aspectos psicossociais da violência. O contexto da desigualdade, do aumento da violência urbana, do encarceramento em massa, da violência contra a população LGBTQIA+ (Lésbicas, Gays, Bissexuais, Travestis/Transexuais, Queer, Intersex, Agêneros), do genocídio negro e da desigualdade em relação aos povos tradicionais e a outros grupos vulnerabilizados precisa ser compreendido na própria produção da subjetividade, impactando nos modos de vida dos sujeitos que, embora sofram sua intercorrência, são também ativos na superação das iniquidades vivenciadas, produzindo resistência. Foi objetivo do curso, portanto, possibilitar a reflexão sobre este contexto e compreender as dinâmicas da violência que atravessam a trajetória de crianças, adolescentes, jovens, mulheres, negros e negras, que se movem entre marcadores de raça, classe e gênero, buscando produzir ainda formas de trabalho que respeitem, estimulem e ajudem na produção de resistências.

O curso ocorreu em formato virtual, com uma carga horária de 36 horas, em doze rodas de conversações, contando com a participação de convidades, sob a mediação de integrantes do VIESES. Com 450 inscritos já no primeiro dia, os encontros ocorreram três vezes por semana, contaram com a mediação de participantes do VIESES e foram transmitidos de maneira síncrona, pelo canal Pós-PsicologiaS UFC, no YouTube, viabilizando a participação e certificação de outras pessoas interessadas. Esta transmissão possibilitou o acesso posterior às Rodas, viabilizando maior participação no contexto da pandemia da COVID-19, chegando o primeiro encontro a alcançar 1.754 visualizações, e as demais rodas variando entre 500 e 1400 visualizações até o fim do curso. Durante a transmissão das rodas, quem estivesse assistindo poderia participar delas por meio do chat, sendo disponibilizada lista de frequência.

A Roda I – “Racismo, branquitude e Direitos Humanos” teve como participantes: Vera Rodrigues, professora no Programa Associado de Pós-Graduação em Antropologia da UFC-UNILAB; Ana Y. Ramos Zayas, antropóloga, Bacharela em Economia e Estudos Latino-Americanos pelo Yale College e MA/PhD em Antropologia pela Columbia University. Este tema teve repercussões ao longo de todas as Rodas, já que é tema transversal e relacionado aos principais objetivos do curso.

Da Roda II – “Direitos Humanos e Saúde Mental: Luta Antimanicomial e Redução de Danos” - participaram: Haroldo Caetano, doutor em Psicologia pela Universidade Federal Fluminense (UFF) e membro do Ministério Público do Estado de Goiás; Dassayeve Távora Lima, mestre em Psicologia e Políticas Públicas no Programa de Pós-Graduação Profissional em Psicologia e Políticas Públicas (PPGPPPP/UFC) em Sobral; Luana Silva Bastos Malheiro, doutoranda em Ciências Sociais pela Universidade Federal da Bahia (UFBA) e sócia-fundadora do Coletivo Balance de Redução de Danos.

A Roda III – “Violência e seus efeitos: Conflitos urbanos e Proteção a pessoas ameaçadas” - teve a participação de Ana Letícia Lins, pesquisadora do Laboratório de Estudos da Violência (LEV/UFC) e da Rede de Observatórios da Segurança; Erick Rastelli, doutorando em Psicologia Clínica pela Universidad de Ciencias Empresariales y Sociales, de Buenos Aires, Argentina; Renato Roseno, presidente da Comissão de Direitos Humanos da Assembleia Legislativa do Ceará, membro titular do Comitê Estadual de Prevenção e Combate à Tortura e do Conselho Estadual de Direitos Humanos; Marcus Giovani Moreira, doutorando em sociologia na UFC e membro do VIESES.

Da Roda IV – “Memória, Justiça e enfrentamento à prática de tortura” -  participaram: Helena Vieira, bacharela em Humanidades na Universidade Federal de Integração da Lusofonia Afrobrasileira (UNILAB); Pedro Paulo Bicalho, Professor Associado do Instituto de Psicologia da Universidade Federal do Rio de Janeiro (UFRJ), representante do Conselho Federal de Psicologia no Comitê Nacional de Prevenção e Combate à Tortura (CNPCT) e presidente do Conselho Regional de Psicologia do Rio de Janeiro.

A Roda V – “Psicologia, Direitos Humanos e Justiça Criminal no Brasil” - teve a participação de Luciano Goes, doutorando em Direito na Universidade de Brasília (UnB); Ana Vládia Holanda Cruz, Doutora em Psicologia, professora no Centro Universitário FANOR Wyden (UNIFANOR WYDE); e Franciane Santos, pesquisadora do Laboratório de Estudos e Pesquisas em Afrobrasilidade, Gênero e Família (NUAFRO/UECE).

Na Roda VI – “Povos tradicionais e Direitos Humanos: questões indígenas”, tivemos a participação da Cacica Adriana Tremembé, liderança indígena do povo Tremembé da Barra do Mundaú/CE; Juliana Alves, indígena do povo Jenipapo Kanindé e mestranda em Antropologia pela Universidade Federal do Ceará (PPGA/UFC); Leonardo Barros Soares, professor da Faculdade de Ciências Sociais e do Programa de Pós-Graduação em Ciência Política da Universidade Federal do Pará (UFP) e membro do Laboratório e Grupo de Estudos em Relações Interétnicas da Universidade de Brasília (LAGERI/UnB).

Na Roda VII – “Educação em Direitos Humanos”, contamos com a participação de Cláudia Mayorga, professora do Departamento de Psicologia da Universidade Federal de Minas Gerais (UFMG) e do Programa de Pós-Graduação em Psicologia, membra da Comissão de Direitos Humanos do Conselho Federal de Psicologia e Coordenadora da Cátedra Itinerante em Direitos Humanos da Asociación de Universidades Grupo Montevideo; Letícia Carolina, transfeminista, professora da Universidade Federal do Piauí (UFPI), doutoranda em Educação na UFPI e integrante do Núcleo de Estudos e Pesquisas em Educação, Gênero e Cidadania (NEPEGECI/UFPI).

A Roda VIII – “Juventudes LGBTQIA+ e resistências coletivas” - contou com a participação de Jô Costa, artista não binárie, coordenadora do“Gueto Queen”, 1° coletivo LGBTQIA+ do Bom Jardim , coordenadora da Cia Viv'arte e integrante do Maracatu Nação Bom Jardim; Talles Azigon, escritor, poeta e mediador de leituras, criador da Livro Livre Curió Biblioteca Comunitária.

Na Roda IX – “Infâncias, adolescências, juventudes e Direitos Humanos”, contamos com a presença de Camila Holanda Marinho, Professora e Pesquisadora da Universidade Estadual do Ceará (UECE) do curso de Ciências Sociais, campus Itapipoca, e do Programa de Pós-Graduação em Políticas Públicas, pesquisadora do Laboratório de Estudos da Violência (LEV) e do Laboratório das Artes e das Juventudes (LAJUS), líder do Grupo de Pesquisa Travessias e pesquisadora da Rede de Estudos e Pesquisas sobre Ações e Experiências Juvenis (REAJ); Leo Suricate, co-criador do “Suricate Seboso”, página humorística originalmente criada no Facebook, em 2012, que retrata cultura nordestina e hoje acumula mais de 6 milhões de seguidores.

A Roda X – “Gêneros e Direitos Humanos” - teve participação de Luma Nogueira, pesquisadora visitante no Centro de Investigação e Estudos de Sociologia (CIES-ISCTE) do Instituto Universitário de Lisboa e professora Adjunta da Universidade da Integração Internacional da Lusofonia Afro-Brasileira (UNILAB); Kaciano Barbosa, Professor adjunto de Sociologia na Universidade Federal do Rio Grande (FURG) e membro do Núcleo de Estudos Afro-Brasileiros e Indígenas da FURG; Anna Paula Uziel, professora da Universidade do Estado do Rio de Janeiro (UERJ) e pesquisadora associada do Centro Latino-Americano em Sexualidade e Direitos Humanos (CLAM/IMS/ UERJ).

A Roda XI – “Pessoas em Situação de Rua (PSR) e Direitos Humanos” - foi composta por Deivison Miranda, mestrando em Psicologia pela Universidade Federal do Delta do Parnaíba (UFDPar); Eugênia Maciel, representante da Pastoral do Povo da Rua, agente da Pastoral na Arquidiocese e na casa do povo da Rua Dom Luciano Mendes e trabalhadora no Centro Pop de Fortaleza; Antônio Arlindo, artesão, militante da luta pela vida e renda da população em situação de rua, representante do Movimento Nacional de Pessoas em Situação de Rua (MNPR); Carlos Eduardo Esmeraldo Filho, psicólogo, doutor em Psicologia pela UFC, professor do curso de Psicologia do Centro Universitário UniFanor e integrante do Núcleo de Psicologia Comunitária (NUCOM).

Na Roda XII – “Arte, cultura e re-existências”, tivemos a presença de Glória Diógenes, professora do Programa de Pós-Graduação em Sociologia da UFC, pesquisadora do Conselho Nacional de Desenvolvimento Científico e Tecnológico – CNPQ e coordenadora do Laboratório das Artes e das Juventudes (LAJUS); Rômulo Silva, doutorando pelo Programa de Pós-graduação em Sociologia da Universidade Estadual (PPGS/UECE), integrante do Laboratório de Estudos da Conflitualidade e Violência (COVIO/UECE), em que coordena a linha de pesquisa "Estudos afro-atlânticos", e pesquisador-colaborador no Laboratório de Arte Contemporânea (LAC/UFC).

Diante de nossas análises, o curso teve o potencial de produzir em alunos e alunas a capacidade crítico-reflexiva e o engajamento da Psicologia nas questões circunscritas no campo de Direitos Humanos. Ao historicizar esse campo, discutimos sobre a universalização dos Direitos Humanos e da racionalidade neoliberal nas relações de poder em torno da noção de humanidade. Por isso, debatemos no curso sobre o contexto de desigualdade, o aumento da violência urbana, o encarceramento em massa, a LGBTfobia, o racismo estrutural, o sexismo à brasileira, o extermínio de povos tradicionais e minorias étnico raciais e sociais, e a forma como isso impacta nos modos de subjetivação.

A grande adesão ao curso – cujas inscrições foram todas preenchidas nas primeiras duas horas iniciais da oferta pública – mostrou o interesse por espaços formativos que proporcionam conexões entre diferentes correntes epistemológicas e, diante do modelo virtual, possibilitou o intercâmbio com diferentes pensadores da Psicologia no Brasil, assim como com estudantes e integrantes de coletivos e movimentos sociais que atuam nesses campos plurais e complexos.

De modo geral, a realização do curso, envolvendo diferentes atores, consolidou-se como um importante dispositivo de tensão e reinvenção do que se entende por Direitos Humanos na Psicologia, sobretudo na Psicologia Social. O curso contribuiu também para uma formação integral, decolonial e crítico-reflexiva de estudantes diante do enfrentamento aos contextos de vulnerabilidades e de precarização da vida, além de colaborar para a (re)formulação de estratégias locais frente à violação de Direitos Humanos na cidade de Fortaleza.

## Curso “De(s)colonizando o campo da saúde mental e da atenção psicossocial no Ceará”

Esta experiência formativa sucedeu-se entre os meses de abril e maio de 2022 de maneira remota e teve a participação de 15 pessoas. O curso foi voltado a profissionais negros/as atuantes na Rede de Atenção Psicossocial do estado do Ceará (atenção básica, CAPS, residência terapêutica, hospitais com leitos psiquiátricos, unidades de desintoxicação, unidades de acolhimento, UPAs, consultórios na e da rua, etc.), visto que se tratava de dispositivo-interventivo, isto é, fazia parte de uma estratégias metodológica de uma pesquisa de doutorado vinculada ao Programa de Pós-Graduação em Psicologia da UFC e ao VIESES-UFC, intitulada: “Por uma de(s)colonização da Saúde Mental: vozes negras na produção do campo da Atenção Psicossocial no Ceará”. Dessa forma, tal dispositivo se revelou como um espaço de trocas, de educação permanente, de cuidado coletivo, de fortalecimento das redes e das lutas antirracista e anticolonial, além de um momento de partilha de novos horizontes vislumbrados e coproduzidos a partir desses encontros entre trabalhadoras/es negras/os.

A carga horária total foi de 20 horas/aula, e os módulos propostos foram guiados a partir do estudo 1 da tese citada anteriormente e organizados em 4 momentos, a saber:

1.  Aspectos históricos, epistemológicos e políticos da saúde mental e da Reforma Psiquiátrica Brasileira;
2.  Efeitos do racismo nas condições de saúde mental de negros/as e nas práticas institucionais produzidas no campo da atenção psicossocial;
3.  Gênero, raça, sexualidade, classe, geração e território como determinantes em saúde mental;
4.  Práticas de(s)coloniais e interseccionais de cuidado com populações negras.

Sabendo que o colonialismo e o racismo, além de produzir efeitos ainda vivos e persistentes sobretudo na saúde mental das populações negras, manifestam-se em distintos dispositivos de saber e poder, o curso pretendeu pôr em análise o debate étnico-racial e colonial ainda incipiente na Luta Antimanicomial, na Reforma Psiquiátrica Brasileira e no Sistema Único de Saúde (SUS). Dessa forma, partindo desta problemática, apoiado em um viés que, afinado com movimentos contracoloniais, busca enfrentar espaços embranquecidos historicamente – a exemplo dos espaços acadêmicos, que, ao longo da história, negaram e inviabilizaram epistemologias negras e outras não brancas –, intencionamos produzir diálogos com profissionais negros/as, além de possibilitar espaços de visibilização de epistemologias outras em um posicionamento ético-politico que buscou pluralizar a formação em saúde.

## Ciclos formativos sobre Psicologia e políticas públicas

A partir do curso “Diálogos formativos sobre psicologia e políticas públicas”, realizamos duas edições em 2021, ambas com carga horária de 20 horas/aula. A primeira, denominada “Preconceito e estigma: desafios para as políticas públicas”, ocorreu em agosto e setembro do mesmo ano e foi organizada em cinco encontros remotos semanais de 3 horas/aula através da plataforma Google Meet, sendo quatro encontros síncronos e um assíncrono, além de cinco vídeos adicionais contemplando as temáticas colhidas no formulário de inscrição.

Essa edição, que teve como principal objetivo fomentar o debate acerca não só das diversas formas de preconceitos e estigmas, mas também dos impactos destes na atuação em políticas públicas no Brasil, foi voltada para profissionais de políticas públicas em Saúde, de Assistência Social e de Educação, bem como para indivíduos atuantes em Movimentos Sociais, membros de Organizações da Sociedade Civil (OSCs) e Organizações não-governamentais (ONGs), cujas principais ações fossem pautar a defesa dos Direitos Humanos em contextos periféricos.

Esse primeiro ciclo foi dividido nos seguintes módulos:

1.  Preconceito e Estigma, Direitos Humanos e políticas públicas;
2.  Homofobia e Estigma em relação a pessoas LGBTQIAP+;
3.  Racismo, preconceito e estereótipos de raça/cor;
4.  Sexismo e Classismo e
5.  Agravamentos dos efeitos do preconceito e do estigma no contexto da covid-19.

Ademais, como parte da metodologia utilizada, foi solicitado aos participantes que registrassem um relato (podendo ser anônimo ou não) sobre situações de discriminação que foram vivenciadas por eles(as) ou que foram observadas e/ou relatadas por terceiros às/aos profissionais no contexto das políticas públicas. Esse material, assim, foi utilizado como provocador de discussões no final do segundo, terceiro e quarto encontro, em que foram tratados temas específicos de discriminação.

No tocante à segunda edição do curso, apresentada como “Avaliação, monitoramento de políticas públicas e estratégias a partir da psicologia social”, o intuito foi apresentar ferramentas e estratégias para conhecer as políticas públicas e suas(seus) usuárias(os), fomentando diálogos a partir da psicologia social. Esta edição, que também era destinada a profissionais de diversas políticas públicas, teve como especificidade apresentar uma perspectiva psicossocial de avaliação e monitoramento de políticas públicas que tivessem ênfase na proteção social dos Direitos Humanos, trazendo exemplos de estratégias alternativas de monitoramento e avaliação, além de evidenciar ferramentas para sua aplicabilidade.

Assim como a anterior, essa edição também foi segmentada em 5 módulos:

1.  Monitoramento e avaliação de políticas públicas e outras estratégias para conhecer as políticas públicas e suas(seus) usuárias(os);
2.  Políticas públicas e Direitos Humanos;
3.  Diálogo, planejamento e ação: experiências de levantamento e as caravanas do conhecimento;
4.  Estigma e preconceito: impactos negativos para as políticas públicas; e
5.  Dificuldades e potencialidades da implementação das estratégias.

É relevante salientar que tais ciclos formativos, que contaram com a participação de cerca de 40 pessoas em cada edição, tiveram não somente um desdobramento teórico-analítico, mas também, e sobretudo, um prático, principalmente no que concerne à segunda edição, a partir da colaboração do VIESES-UFC, na avaliação, e da Rede de Desenvolvimento Local, Integrado e Sustentável do Grande Bom Jardim (Rede DLIS) no monitoramento das políticas de assistência social (CRAS e CREAS) presentes no território do Grande Bom Jardim (GBJ). Esta rede se configura como uma instância de luta pela garantia de direitos no território do GBJ que atua desde 2003, articulando 26 entidades locais.

Para a efetivação desse processo, um grupo de trabalho constituído por membros do VIESES, da Rede DLIS e do território foi formado, tendo encontros periódicos via Google Meet. O intuito preponderante do grupo foi construir e implementar uma proposta de avaliação e monitoramento dos CRAS e do CREAS do GBJ, levando em consideração o contexto das limitações impostas pela pandemia e tomando como base a estratégia da Caravana do Conhecimento, adotada em uma experiência de avaliação e monitoramento realizada anteriormente pela rede DLIS. O alcance delimitado para a Caravana no ano de 2021 foi de um CREAS, três CRAS, contemplando cerca de 100 usuários desses equipamentos.

## Curso “(Re)Existir nas encruzilhadas: diálogos sobre relações raciais, gênero e juventudes”

Este curso teve como principal objetivo produzir conexões, aproximações e aperfeiçoamentos de cunho teórico-metodológico e vivencial a respeito das implicações dos atravessamentos das relações de gênero nos modos de subjetivação em contextos periferizados de áreas urbanas, que são agenciados por cenários de violência e marcados não só por contextos de opressão, mas também de reexistências de juventudes inseridas nessas territorialidades, nas dificuldades para políticas públicas que atuam no tocante à garantia de direitos humanos e para a produção e promoção de práticas de cuidado ante as violências e a mortificação produzidas pelo racismo, pela LGBTQIP+fobia e pelas interseccionalidades de outros marcadores de opressão.

O VIESES apresenta-se como uma possibilidade de fortalecimento para pessoas LGBTQIAP+ do Grande Bom Jardim. Desde o início de suas inserções no território, em 2018, o Programa já realizou diversas ações de pesquisa e conta com 4 projetos de extensão em desenvolvimento no território, junto a segmentos infantojuvenis, em parcerias com políticas públicas de cultura e educação, organizações não governamentais, movimentos sociais e coletivos do território voltadas à defesa de direitos humanos. Nossas iniciativas visam fortalecer estratégias de promoção de cuidado, considerando os efeitos psicossociais diante da discriminação sexual, da LGBTQIAP+fobia e do racismo.

Como sabido, o Brasil é o país que mais assassina pessoas LGBTQIAP+ no mundo, destacamos ainda a forma cruel e espetacularizada que essas mortes acontecem, com traços de requinte de crueldade misógina e LGBTQIAP+fóbica [@sousa2020interseccionalidade]. Quando observamos essas mortes e violações também pelo viés racial, sobretudo em contextos periferizados, como o em que pretendemos atuar, destaca-se o racismo estrutural como motor necropolítico das tramas da violência [@costa2020dispositivo]. Assim, essa realidade é reflexo de estruturas sociais que corroboram a formação do ódio contra pessoas negras e LGBTQIAP+.

Ressaltamos ainda que o cenário brasileiro, sobretudo com o avanço de ideias conservadoras, tem contribuído para a manutenção de hierarquias de raça, gênero e sexualidade, impedindo assim avanços no tocante ao entendimento e respeito diante do fenômeno do racismo e das identidades de gênero e orientações sexuais, embora, nos últimos anos, tenham sido conquistadas algumas leis, como a da união estável e a da equiparação da homofobia ao crime de racismo.

No que se refere ao público alvo, o curso foi direcionado a estudantes de Psicologia e áreas afins, profissionais e gestores atuantes nas políticas públicas, integrantes de organizações da sociedade civil, juventudes LGBTQIAP+ do Grande Bom Jardim (GBJ) e comunidade em geral com interesse em discutir temáticas propostas. O curso teve carga horária total de 36 horas e ocorreu durante os meses de outubro a dezembro de 2022. Importante pontuar que os quatro primeiros encontros dos módulos iniciais aconteceram no departamento de Psicologia da UFC, enquanto os módulos finais, numa perspectiva de territorialização, foram realizados no Centro de Defesa pela Vida Herbert de Souza (CDVHS), com intuito de fortalecer o intercâmbio e a produção de conhecimentos no diálogo realizado entre universidade e comunidade, dado que 40% das 45 vagas foram reservadas a participantes que moram ou atuam em equipamentos voltados para as juventudes do GBJ.

Foram oito módulos propostos:

1.  Gênero: aspectos históricos, conceituais e seus atravessamentos nas trajetórias e experiências juvenis;
2.  Relações Raciais: aspectos históricos, conceituais e seus atravessamentos nas trajetórias e experiências juvenis;
3.  Efeitos psicossociais do racismo e da LGBTQIA+fobia na saúde mental de juventudes;
4.  Desigualdades de gênero e desafios para Políticas públicas e garantia de Direitos Humanos;
5.  Racismo e desafios para políticas públicas e garantia de Direitos Humanos;
6.  Práticas de cuidado e enfrentamento à LGBTQIA+fobia: desafios e experimentações teórico-epistêmicos e clínico-políticos;
7.  Práticas de aquilombamento e políticas do cuidado frente ao racismo: desafios e experimentações teórico-epistêmicos e clínico-políticos;
8.  Diálogos interseccionais entre raça, gênero, classe, geração e território: experiências e reexistências coletivas de juventudes em periferias urbanas.

A partir dos acúmulos construídos pelas experiências de extensão desenvolvidas pelo VIESES desde 2015 em diversas periferias da cidade de Fortaleza e das propostas formativas já experimentadas pelo laboratório, o curso adotou metodologias ativas, dialógicas e colaborativas, primando pela leitura crítica da realidade, pela troca de experiências entre a diversidade de participantes e pelo aprofundamento contextualizado de conteúdos relacionados ao tema das relações de raça e gênero, trajetórias juvenis em territorialidades urbanas, políticas públicas de garantia de direitos humanos e práticas clínico-políticas de cuidado. Para tanto, foram utilizadas estratégias pedagógicas, tais como: exposição dialogada, rodas de leituras a partir de textos, técnicas de trabalho na perspectiva grupal, compartilhamento das experiências sociais, profissionais e acadêmicas trazidas pelos(as) participantes.

## Considerações finais

As produções técnicas relatadas neste capítulo (cursos de extensão promovidos pelo VIESES-UFC) têm em comum o intuito de abordar criticamente temáticas que estão ligadas à práxis em Psicologia na defesa de Direitos Humanos, na proposição de políticas públicas para o enfrentamento à violência e na produção de conhecimentos a partir do diálogo da universidade com diferentes setores e grupos sociais.

Outro aspecto comum a tais produções técnicas é que todos os cursos partiram de metodologias que propiciaram o compartilhamento de vivências, relatos de experiências profissionais, resultados de pesquisas e reflexões teóricas da psicologia e das suas interlocuções com áreas afins. Essas iniciativas se desenharam também considerando possíveis intervenções em Psicologia, sendo relevante para a atuação profissional e acadêmica em seus mais diversos âmbitos.

A criação de tais produções técnicas, no contexto de pandemia da COVID-19 e da ascensão de valores e práticas neofascistas, partiu do pressuposto de que pautar o campo multifacetado dos Direitos Humanos é fundamental para a promoção de uma formação em Psicologia eticamente comprometida com transformações no contexto brasileiro, que ainda convive com marcas e práticas fortes da colonialidade. A fim de se movimentar na contramão de abordagens acríticas e reducionistas sobre o assunto, tanto os produtos de comunicação quanto o curso de extensão relatados puderam socializar realidades e referências teóricas de pensadores e pensadoras da Psicologia e das suas áreas afins que problematizam padrões cis-hetero-patriarcal-colonial-capitalistas.

Acreditamos que essas produções técnicas ligadas ao VIESES tiveram o potencial de fortalecer e estimular reflexões sobre o enfrentamento às desigualdades e opressões no Brasil. Outrossim, buscaram contribuir para ampliação do impacto do Programa de Pós-Graduação em Psicologia da UFC na sociedade, a partir da potencialização das ressonâncias das discussões que são caras ao VIESES desde sua criação. Isso porque, com os cursos de extensão, em especial os que se deram remotamente, essas problematizações puderam alcançar desde estudantes de graduação e pós-graduação, passando por profissionais, fossem de Psicologia, fossem de áreas afins, a gestores de políticas públicas e integrantes de coletivos, movimentos sociais e organizações da sociedade civil de diferentes regiões do Brasil e até de fora do território nacional.
