---
author: 
  - name: Pamella Beserra de Melo
    url: http://lattes.cnpq.br/5559146180799726
    orcid: 0000-0003-0255-4122
    email: pambmelo@gmail.com
    affiliations: 
      - name: Universidade Federal do Rio Grande do Norte
      - name: Universidade Federal do Ceará
  - name: Francisco Pablo Huascar Aragão Pinheiro
    url: http://lattes.cnpq.br/8266089190930601
    orcid: 0000-0001-9289-845X
    email: pablo.pinheiro@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Francisca Valéria de Sousa
    url: http://lattes.cnpq.br/0363852725072024
    orcid: 0000-0002-5232-8812
    email: valeriasousa0140@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
language: 
  title-block-author-plural: "Autoras"
filters:
  - section-bibliographies
bibliography: beserra_de_melo_assessoria.bib
reference-section-title: Referências
---

# Os desafios da saúde do servidor público: relato de uma assessoria

## Introdução

Observa-se uma uma dificuldade no estabelecimento da relação entre o trabalho e o adoecimento de servidores públicos [@ramminger2007saude]. Até 2009, a saúde dos servidores públicos de Universidades e Institutos Federais esteve relacionada à perícia médica e odontológica. As ações de promoção e prevenção à saúde e aos seus agravos eram praticamente inexistentes antes da implementação da Política de Atenção à Saúde e Segurança do Trabalho do Servidor Público Federal (PASS). As reivindicações desse público, até então, voltavam-se para melhorias na remuneração e na formação. Após a estruturação e consolidação do plano de carreiras dos cargos de técnicos-administrativos em educação, a partir da Lei n° 11.091, de 12 de janeiro de 2005 [-@brasil2005lei11091], passou-se a dar maior visibilidade às questões de saúde. Destaca-se, assim, a necessidade de se pensar e problematizar as formas de organização do trabalho e as relações socioprofissionais no serviço público [@ramminger2007saude].

O caso aqui apresentado relata uma intervenção em promoção à saúde no trabalho realizada no setor de contabilidade e finanças de uma universidade federal. Trata-se, portanto, de uma assessoria prestada a este setor, que era responsável por coordenar e supervisionar o orçamento da instituição, bem como por gerir contratos e convênios. Dentre outras atribuições, os trabalhadores desse setor conferiam diariamente todos os pagamentos realizados pela instituição, de modo a evitar lançamentos indevidos ou incorretos; emitiam notas de empenho, que garantiam a reserva de recursos para o pagamento a empresas ou pessoas que tinham contratos firmados com a Universidade; e lidavam com o pagamento de bolsas e ajudas de custo.

A demanda inicial pela intervenção partiu do coletivo de trabalhadores encaminhados à Pró-reitoria de Gestão de Pessoas da universidade, após sete servidores pedirem remoção do setor devido a conflitos com os gestores. A queixa dizia respeito ao difícil relacionamento com as chefias e com a imposição de novas normas. Os servidores também destacavam a ausência de autonomia, pois as decisões eram tomadas unilateralmente pelas chefias, de forma autoritária, sem diálogo com o grupo. Houve, ainda, mudanças nos processos de trabalho sem que houvesse uma comunicação prévia com a equipe. Estas questões refletiam na baixa motivação para o trabalho e no interesse de vários servidores em mudar de setor. Contudo, a remoção de todos os servidores de um setor para outro, mesmo que dentro do mesmo órgão da administração pública, não era uma solução plausível.

Em face disso, o que justificaria uma intervenção de promoção à saúde a partir dos problemas apresentados, na medida em que eles não estavam relacionados diretamente a doenças físicas ou mentais? Isto se deve a uma compreensão de que a saúde não é o oposto da doença: é possível perder a saúde antes mesmo de adoecer. Ter saúde, dessa forma, é ser capaz de agir e, principalmente, ser capaz de se reinventar diante das dificuldades encontradas na atividade que se realiza no trabalho. Em face disso, a saúde é prejudicada quando o poder de ação do trabalhador é limitado [@clot2010trabalho].

Vê-se, portanto, que a capacidade dos servidores do setor de contabilidade e finanças de reorganizar suas atividades diante dos limites impostos foi cerceada ao ponto de eles avaliarem que o único caminho possível era sair do setor. Nesse sentido, era necessária uma intervenção de promoção à saúde que permitisse a recuperação do poder de agir desses trabalhadores. Diante disto, uma psicóloga do trabalho e um grupo de extensionistas estudantes de Psicologia vinculados à Pró-Reitoria de Gestão de Pessoas da instituição acolheram a demanda e promoveram uma intervenção que pôde, como se verá adiante, reposicionar os trabalhadores diante da própria atividade e das demandas apresentadas, assim como abrir um canal de comunicação com os gestores.

A intervenção realizada teve como fundamento a Clínica da Atividade, que se propõe a ser uma teoria da ação e da transformação nos contextos de trabalho. Esta perspectiva ressalta a importância do fortalecimento e do desenvolvimento do coletivo de trabalho. Para compreender a Clínica da Atividade, é importante elucidar o conceito de ofício, definido como a estrutura resultante do conflito entre quatro dimensões, quais sejam: impessoal, transpessoal, pessoal e interpessoal [@clot2010trabalho].

A dimensão impessoal compreende as regras e as condições às quais estão submetidos os trabalhadores, como horários de chegada e saída, materiais e instrumentos de trabalho, normas de segurança e manuais para a realização de procedimentos. A dimensão transpessoal (ou gênero profissional) também diz respeito a normas. Neste caso, entretanto, são aquelas formuladas pelo próprio coletivo de trabalho, constitutivas de uma cultura profissional implícita que, mesmo não estando formalmente registrada, orienta a ação dos trabalhadores em momentos de dificuldade. Cada profissional, por sua vez, imprime sua história na atividade que realiza e também elabora novas regras a partir de suas experiências. Por isso o ofício é também pessoal. Por fim, o trabalho é feito na interação com outras pessoas (colegas, chefias, consumidores, dentre outros), o que caracteriza o nível interpessoal [@clot2010trabalho].

Também é pertinente entender a distinção entre atividade realizada e real da atividade [@clot2006funcao]. A primeira é constituída pelas ações que o trabalhador efetivamente realiza no seu posto de trabalho e que, em muitos casos, são visíveis a um observador externo. O real da atividade, por sua vez, é o conjunto de possibilidades que, em algum momento, se colocaram no horizonte de ação do trabalhador, mas que não foram realizadas. É a partir do real da atividade que se torna possível renovar as possibilidades de agir nos contextos de trabalho.

Compreendendo essas definições, a psicóloga do trabalho que atua a partir da Clínica da Atividade pode ajudar os trabalhadores a revitalizar as culturas profissionais e também a procurar novas formas de ação a partir do real da atividade. Dessa forma, é possível desenvolver o poder de agir sobre o meio de trabalho, sobre a organização e sobre si, o que implica, portanto, promover saúde.

A partir deste horizonte, vê-se que não cabe à psicóloga fazer um diagnóstico e inventariar os riscos psicossociais aos quais os trabalhadores estão expostos. Caberá a ela mediar reflexões sobre a atividade, de modo que os profissionais possam encontrar recursos psicossociais e pessoais para realizar um trabalho de qualidade. É, assim, sua função auxiliar na busca por capacidades de ação imprevisíveis em meio à atividade e ajudar a redescobrir os prazeres do trabalho bem-feito, tido como a mola propulsora da saúde [@clot2017clinica]. Para tanto, a Clínica da Atividade movimenta e promove o diálogo, a fim de retomar a criação coletiva e, com isso, cuidar do trabalho. Promovem-se, assim, debates entre os trabalhadores, detentores do saber sobre a própria atividade, e, posteriormente, destes com as suas chefias [@clot2017clinica].

## Método

### Participantes

Participaram da intervenção quatro contadores, uma contadora, um técnico em contabilidade e uma técnica em contabilidade, bem como as gestoras imediata e superior, ambas contadoras, totalizando nove participantes. Todos os servidores exerciam o cargo de Técnico-Administrativo em Educação (TAE) da IES e, como dito anteriormente, atuavam no setor de contabilidade e finanças.

### Procedimentos, instrumentos e percurso da intervenção realizada

Antes de iniciar a apresentação sobre os instrumentos e procedimentos utilizados na intervenção, é importante recuperar a ideia de que, em Clínica da Atividade, não se realiza um diagnóstico preliminar que dará subsídios para a psicóloga apontar prescrições que os trabalhadores devem seguir para resolver os problemas implicados com a atividade ou para que possam ter mais saúde e satisfação. Também não é o objetivo dela produzir uma lista com riscos, sejam eles físicos, sejam ergonômicos, sejam psicossociais, de modo a produzir uma avaliação externa sobre o trabalho.

Pretende-se, a partir do protagonismo dos trabalhadores, colocar a ação em movimento, dialogar sobre ela e, com isso, romper as barreiras das atividades cristalizadas, aquelas que já estão estabelecidas e não conseguem mais dar conta dos desafios enfrentados pelos trabalhadores. Objetiva-se, dessa maneira, redescobrir novas formas de agir na atividade e no seio das discussões com o coletivo de trabalho (portanto na dimensão interpessoal do ofício), facilitar a reflexão dos trabalhadores para ampliar seu poder de agir [@clot2006funcao]. Dito isto, também cabe esclarecer que todas as etapas descritas a seguir fazem parte da intervenção e que os procedimentos e instrumentos apresentados são utilizados como mediadores para atingir o objetivo indicado acima.

Inicialmente foram realizadas duas reuniões com os gestores do setor de contabilidade e finanças para explicar a proposta de trabalho. Nessas ocasiões, foram apresentados os objetivos da ação e a metodologia que seria empregada. Procedeu-se de forma análoga com os servidores, e, posteriormente, foi criado um grupo de trabalho com aqueles que aceitaram participar. A intervenção foi dividida em três etapas:

1.  análise documental;
2.  observação das atividades e
3.  realização de instruções ao sósia (IS).

Na primeira etapa, foram buscados documentos que caracterizavam, regulamentavam e normatizavam as atividades dos trabalhadores. Também foram analisadas as atribuições do setor, os seus objetivos e a sua estrutura organizacional. Visaram-se, ainda, os processos técnicos desenvolvidos e as tarefas explicitamente atribuídas aos servidores, além de cargos e funções do setor. Pretendia-se, desta maneira, compreender as prescrições das atividades, das normas e dos modos de proceder, bem como as características gerais da organização do trabalho, ou seja, visou-se a dimensão impessoal do ofício. Tencionava-se, de tal modo, construir as bases do diálogo entre o grupo de trabalho e a equipe da intervenção, assim como entre os próprios trabalhadores, por meio do qual o conflito sobre a qualidade do trabalho poderia ser pensado e debatido [@clot2013oficio]. Entretanto, como se verá adiante, algumas dessas normativas não estavam claramente definidas tanto para gestores quanto para trabalhadores.

Na segunda fase, foram realizadas observações, de modo que se pudessem acessar as atividades realizadas. Tal procedimento gera um duplo resultado. O primeiro deles está ligado à produção de conhecimento sobre o objeto observado, a atividade, acompanhando uma tradição já bem desenvolvida pela ergonomia e pelas outras abordagens que valorizam os estudos do trabalho situado. O segundo, por sua vez, relaciona-se ao fato de que a observação já gera uma intervenção no campo ao produzir um diálogo interno no trabalhador [@clot2010trabalho]. Nessa perspectiva, foi possível conhecer e analisar os processos de trabalho, bem como identificar problemas e potencialidades relacionados ao engajamento dos profissionais com as transformações a serem realizadas nos modos de proceder.

Foram acordados previamente com os servidores os dias e horários das observações, e, ao final de cada visita, a equipe produziu um relatório a partir daquilo que foi visto e que foi falado pelos funcionários do setor. Sete momentos de observação, com duração média de 3 horas cada, foram realizados. Finalizado este processo, realizou-se uma reunião com todos os servidores para debater as sistematizações produzidas. Foi possível, então, discutir sugestões e melhorias propostas pelos trabalhadores, que foram negociadas e debatidas com a chefia do setor. Estabeleceu-se, assim, uma parceria entre gestores e servidores para operar os encaminhamentos necessários.

Concluída essa etapa, iniciou-se o terceiro momento, no qual foram realizadas duas reuniões para a realização da IS, que consiste numa técnica na qual o clínico da atividade emite a seguinte diretriz ao trabalhador: “suponha que eu seja seu sósia e que amanhã vou substituí-lo em seu local de trabalho. Quais instruções você deveria me transmitir para que ninguém perceba a substituição?” [@clot2006funcao p.144]. Para a realização dessa etapa, o grupo foi dividido em dois, conforme a natureza das atividades que eram realizadas.

Em cada subgrupo, foi solicitado que um servidor se voluntariasse a ser o instrutor do sósia, que era um membro da equipe de intervenção. Após o término da instrução, abriu-se um espaço para os demais membros do grupo, que estavam na posição de observadores, participarem. A partir disso, eles puderam explanar discordâncias, questionamentos e complementações em relação à fala do trabalhador que estava na posição de instrutor. Ao serem finalizadas as instruções ao sósia, as falas que, naquela ocasião, haviam sido gravadas, foram transcritas e devolvidas aos servidores para que pudessem ler e retirar alguns pontos para discussão.

Em seguida, foram realizadas reuniões com cada subgrupo a fim discutir os pontos destacados por eles a partir da leitura do material transcrito. Dentre as temáticas abordadas pelos servidores nessas reuniões, discutiu-se sobre natureza das atividades; retrabalho e sobrecarga; necessidade de treinamento; cumprimento de metas; relacionamento com as chefias; controle do uso do sistema de cadastramento de informações, dentre outras. Por fim, foram feitas reuniões de discussão dessas questões com todos os integrantes do grupo de trabalho.

Finalizou-se a intervenção com uma reunião geral em que trabalhadores e gestores discutiram as demandas levantadas em cada etapa e as mudanças empreendidas que foram favoráveis ao grupo no desenvolvimento de suas atividades. Também houve um debate sobre melhorias sugeridas, mas que não foram alcançadas por diversos motivos, dentre os quais se podem citar os limites delimitados por questões legais impostas ao setor público.

## Resultados e discussões

A seguir, serão apresentados os impedimentos discutidos pelos servidores para a realização de um trabalho bem-feito, bem como as potencialidades vislumbradas para reconstrução da própria atividade e do ofício, que foram construídos a partir dos procedimentos e das técnicas apresentados anteriormente, bem como das discussões realizadas com o coletivo de trabalho. Observou-se o desenvolvimento do poder de agir e o fortalecimento dos trabalhadores em torno de questões relacionadas às dimensão impessoal, especificamente no que diz respeito às condições de trabalho e à organização laboral, e ao relacionamento interpessoal.

No que tange às condições de trabalho, os servidores afirmaram que havia pouco espaço para circulação na sala em que atuavam, pois ela era pequena para a quantidade de móveis de que dispunha. Em relação aos instrumentos disponíveis para execução das atividades, eles apontaram que a maioria não tinha mousepad com apoio para o braço, que é importante quando se mantém longos períodos usando computadores e realizando movimentos continuamente. Aventou-se, ainda, a possibilidade de que isto poderia levá-los a desenvolver lesões por esforços repetitivos.

Além disso, havia a falta de materiais importantes para realização das atividades, como marca texto, para destacar, nas notas, os valores importantes a serem lançados no sistema, e réguas e canetas em condições de uso, pois as que eram disponibilizadas pela universidade tinham qualidade inferior e logo ficavam inutilizadas. Diante disso, os trabalhadores acabavam por comprar estes e outros materiais por conta própria. Diante dessas questões e dos impedimentos que elas impunham para a realização de suas atividades, ao longo da intervenção, o coletivo pôde debater propostas que foram discutidas com os gestores, tais como a reorganização das mesas e cadeiras para melhorar a circulação na sala e a solicitação dos materiais de consumo diretamente pela pró-reitora junto ao setor de almoxarifado, de modo que os pedidos fossem atendidos em tempo hábil, pois o prazo de resposta às solicitações individuais era muito longo.

No que se refere aos aspectos relacionados à organização do trabalho, a falta de prescrição clara e definida era umas das principais queixas apontadas pelos servidores, visto que o setor não tinha um fluxograma de trabalho estabelecido que orientasse sobre como as atividades deveriam ser exercidas. A prescrição consiste na tarefa, nas normas, nos valores, nas obrigações e nos procedimentos previamente antecipados pela organização. Dessa forma, compreende-se que a falta de clareza quanto a isto gera dúvidas e incertezas para o desempenho das atividades. Nesse sentido, enquanto o excesso de prescrição impede criações e estilizações, sua falta deixa o trabalhador sem um guia pelo qual pode orientar suas ações, o que pode paralisá-lo [@pinheiro2016clinica].

Diante dessa carência, os facilitadores da intervenção tentaram remeter o grupo às prescrições informais estabelecidas pelo coletivo de trabalho, a dimensão transpessoal do ofício. Tentou-se explicitar, portanto, orientações tácitas que guiavam as ações de modo que fosse viabilizado um suporte mútuo em relação a dúvidas e imprevistos que surgiam a partir daquilo em que a prescrição formal se mostrava insuficiente. Foi possível, dessa maneira, fortalecer o grupo de trabalho a partir da explicitação de um gênero profissional [@clot2010trabalho] que os guiava, o que permitiu o estabelecimento de algumas diretrizes, em especial em relação às atribuições de cada um, aos fluxos dos processos do setor e aos encaminhamentos a serem dados quando eram identificados problemas nos processos. Percebe-se, assim, que “o poder de (re)criação no meio de trabalho se desenvolve a partir da apropriação dos recursos para ação elaborados no coletivo” [@souto2015reflexoes, p. 13], ou seja, no gênero profissional podem ser mobilizados recursos para a realização das atividades.

Ainda sobre a organização do trabalho, o coletivo debateu sobre metas estabelecidas para o setor. Percebeu-se que estas foram construídas de forma inapropriada, pois não levavam em conta o fluxo das atividades. Reclamava-se que as metas, irrealizáveis, eram definidas sem a participação do grupo e impostas hierarquicamente. A própria forma de mensuração dos resultados não condizia com a realidade. Os servidores criaram, então, uma planilha de acompanhamento das atividades para, a partir dela, estabelecerem as metas futuras junto com a chefia, considerando, portanto, a realidade e as necessidades do setor.

Outra demanda trazida pelos trabalhadores dizia respeito à falta de diálogo que havia entre eles e suas chefias. Em muitos casos, a autonomia dos servidores era constantemente podada por decisões vindas dos superiores. Desse modo, sentindo-se alheios à sua atividade, os servidores encontravam-se desmobilizados para o cumprimento das tarefas e as realizavam de maneira desimplicada, receosos de que, a qualquer momento, outras mudanças poderiam ser impostas à revelia do coletivo. Somada a isso, a inabilidade das chefias para dialogar também fazia com que os próprios trabalhadores tivessem entre si uma comunicação apenas necessária, pouco amigável ou, até mesmo, hostil.

Isto gerava um enrijecimento das relações e uma exacerbação das individualidades, tendo como consequência solicitações de remoção frequentes, o que causava uma alta rotatividade de trabalhadores do setor, a qual era agravada pela prática da gestão de mudar constantemente os servidores de função. Observou-se que essas mudanças eram impostas hierarquicamente, sem a participação daqueles que iriam deixar de exercer sua função anterior e passar a desempenhar uma nova, sem nenhum debate ou consulta prévios sobre o interesse na realização dessa nova atribuição. Quando se consideravam aptos para exercer uma função, por meio, por exemplo, da leitura de legislações específicas, e estavam treinados e habituados à sua atividade, eram realocados em nova função sem qualquer justificativa.

Tudo isso acarretava dificuldades para o grupo se reconhecer como um coletivo de trabalho, uma vez que os servidores não viam no outro um par a quem se reportar ou a quem recorrer numa situação de dificuldade. Isso traz à tona a menção de que a sensação de pertencimento a um coletivo permite a conservação do ofício. O conjunto de ações possíveis e impossíveis, os acordos tácitos firmados entre o grupo constituem um recurso genérico que atua como baliza para a atividade individual. Quando a renovação do gênero é impedida, o coletivo está exposto aos imprevistos do real, e os sujeitos não podem mais se reconhecer naquilo que fazem [@clot2010trabalho].

No decorrer da intervenção, houve a troca de uma das gestoras. Ao longo dos debates na instrução ao sósia, os trabalhadores afirmaram que a nova chefia tinha formação na área de atuação e estava sempre à disposição, sensível ao acolhimento das demandas do grupo, o que impactou positivamente este relacionamento. A nova chefia acatou, por exemplo, a proposta de realização de rodízio anual junto aos servidores que desenvolviam atividades mecânicas e repetitivas, nas quais utilizavam os mesmos comandos no teclado e na tela do computador ao analisar diversos processos diariamente. Alguns chegavam a fazer essas operações em 50 processos diários, o que a tornava “maçante, repetitiva e cansativa”, nas palavras de um dos técnicos em contabilidade.

Outra mudança implantada pela nova gestão, a partir da solicitação do coletivo, foi a descentralização de algumas atividades para outros setores, o que diminuiu a sobrecarga de trabalho. Foi suspensa, ainda, a prática de designar os trabalhadores da contabilidade para as funções de servidores de outros setores que tiravam férias, o que também gerava sobrecarga de trabalho, assim como descontentamento entre o grupo, pois a nova função não estava dentro de suas atribuições e deveria ser executada por alguém do setor de origem.

## Conclusões e limitações da intervenção

A intervenção foi realizada em um contexto marcado pela desmotivação dos servidores e pelos diversos problemas referentes à organização e às condições de trabalho, bem como à relação dos servidores entre si e destes com as chefias. Foram promovidos inúmeros debates sobre a atividade e sobre o ofício, o que permitiu aos trabalhadores encontrar novos modos de proceder e dialogar com as chefias sobre as dificuldades encontradas, o que contribuiu positivamente para as relações interpessoais do grupo. Houve, assim, uma ampliação do poder de agir, o que, a partir da Clínica da Atividade, significa promover saúde. Como limitação, observou-se a dificuldade inicial de sensibilização das chefias sobre a importância de considerar as propostas trazidas pelos trabalhadores como necessárias ao bom desenvolvimento das atividades.

Outra limitação dizia respeito a algumas legislações federais antigas e, portanto, desatualizadas, que não acompanharam as mudanças e os processos de modernização da instituição, o que gerava uma contradição entre as inovações impostas pela gestão e a rigidez das normatizações, dificultando o desenvolvimento de alguns processos que se tornavam mais morosos devido à burocracia, ao passo que poderiam ser mais ágeis. Porém, a modificação ou atualização da legislação é realizada por instâncias superiores, externas à própria universidade, pois que atrelada à mobilização de órgãos ministeriais federais.
