---
author: 
  - name: Zulmira Áurea Cruz Bomfim
    orcid: 0000-0002-1874-8821
    url: http://lattes.cnpq.br/1210419516945897
    email: zulaurea@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará    
  - name: Nara Maria Forte Diogo Rocha
    orcid: 0000-0001-5040-1492
    url: http://lattes.cnpq.br/8711220429784748
    email: narafdiogo@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Fábio Pinheiro Pacheco
    orcid: 0000-0003-4139-1506
    url: http://lattes.cnpq.br/7580641163210143
    email: fabio.pacheco@uece.br
    affiliations: 
      - name: Universidade Estadual do Ceará
  - name: Andie de Castro Lima
    orcid: 0000-0003-1469-8529
    url:  http://lattes.cnpq.br/5263513220053487
    email: lima.castro94@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Cícera Mônica da Silva Sousa Martins
    orcid: 0000-0003-1773-0061
    url: http://lattes.cnpq.br/4057474289308489
    email: monicamartins_sousa@hotmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Halaine Cristina Pessoa Bento
    orcid: 0000-0002-2247-5096
    url: http://lattes.cnpq.br/1306220024705448
    email: halainecristinapessoa@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Elcides Hellen Ferreira Landim Barreto
    orcid: 0000-0003-1284-5679
    url: http://lattes.cnpq.br/0406518963460217
    email: hellenbarreto0@hotmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Graciella Faico Ferreira
    orcid: 0000-0001-9075-5180
    url: http://lattes.cnpq.br/1642574960298281
    email: graciella@ufrj.br
    affiliations: 
      - name: Universidade Federal do Rio de Janeiro
      - name: Universidade Federal Fluminense
language: 
  title-block-author-plural: "Autoras"
filters:
  - section-bibliographies
bibliography: bomfim_metodologias_part.bib
reference-section-title: Referências
---

# Curso de extensão “Abordagens e metodologias participativas socioambientais”: relato de uma ação interdisciplinar em ensino, pesquisa e extensão

## Introdução

Este capítulo objetiva relatar a experiência de construção e facilitação do curso de extensão "Abordagens e Metodologias Participativas Socioambientais", desenvolvido pelo Laboratório de Pesquisa em Psicologia Ambiental (Locus) da Universidade Federal do Ceará (UFC). O Locus, vinculado ao Departamento de Psicologia da UFC, tem como marca de sua produção acadêmica a articulação entre pesquisa, ensino e extensão, proporcionando a concretização do tripé universitário, tal como descrito pelo Ministério da Educação.

O laboratório surgiu em 2003, trazendo uma perspectiva socioambiental, por meio de uma visão ambiental, psicossocial e sócio-histórica, para compreender a relação pessoa-ambiente, abrangendo as dimensões física, social, cultural, psicológica e política, e direcionando seus estudos e intervenções às demandas emergentes da sociedade [@pacheco2021revisao]. Teórica e metodologicamente, o Locus adota uma perspectiva interdisciplinar, considerando a complexidade dos fenômenos estudados e a multiplicidade de fatores envolvidos nas interações pessoa-ambiente, estabelecendo contatos com as áreas da Psicologia, da Educação, da Geografia, da Arquitetura, do Urbanismo, da Sociologia, da Antropologia, das Ciências Políticas, dentre outras.

No âmbito do ensino, o Locus se relaciona com disciplinas de Psicologia Social e de Psicologia Ambiental, na graduação e pós-graduação. No âmbito da pesquisa, o laboratório vincula-se ao Programa de Pós-Graduação em Psicologia da UFC (PPGP-UFC/Fortaleza), desenvolvendo pesquisas de mestrado e doutorado. Já na extensão, executa ações junto à comunidade universitária e à sociedade em geral, tendo como principais projetos:

1.  Vida no Campus, que se volta para a melhoria da qualidade de vida de alunos, professores e demais funcionários no ambiente universitário [@bomfim2019afetividade];
2.  Diagnóstico-Ação pelos Mapas Afetivos, que realiza diagnósticos e intervenções socioeconômicos, infraestruturais, psicossociais e ambientais em grupos e comunidades da cidade de Fortaleza e da região metropolitana [@lima2021psicologia];
3.  Nas Trilhas da Psicologia Ambiental, que busca facilitar processos de apropriação e identificação dos espaços de Fortaleza, utilizando como ferramenta as trilhas urbanas e ecológicas; e
4.  Programa Locus, que desenvolve ações interdisciplinares, tendo suas atividades de pesquisa e extensão, desde 2015, voltadas para etnias indígenas [@pacheco2021revisao] e, a partir de 2020, juntamente com o Projeto Sankofa, abrange também comunidades quilombolas, debatendo questões étnico-raciais.

Em 2020, o Locus esteve presente no desenvolvimento do curso de extensão “Aspectos Psicossociais das Vulnerabilidades no Contexto da Pandemia da COVID-19”, organizado pelo PPGP-UFC/Fortaleza e pelo Programa de Pós-Graduação Profissional em Psicologia e Políticas Públicas da UFC (PPGPPPP-UFC/Sobral), responsabilizando-se por elaborar e ministrar um módulo intitulado “Metodologias ativas e participativas no enfrentamento da COVID-19 junto a populações indígenas”. A partir dessa atividade, considerando a necessidade de aprofundamento de discussões realizadas no módulo, surgiu a iniciativa de desenvolver outro curso de extensão para partilhar as experiências de pesquisa, de ensino e de extensão do Laboratório.

Desenvolveu-se, então, o curso "Abordagens e Metodologias Participativas Socioambientais", com o intuito de ampliar as discussões surgidas no curso anterior. E, assim, foram abarcados outros cenários, tais como a cidade e os seus aspectos paisagísticos, os povos originários e as questões transculturais, os processos de desenvolvimento humano e aprendizagens, além das experiências em políticas públicas de assistência social e de saúde. O curso se propôs a apresentar ao público-alvo (estudantes de graduação e de pós-graduação, profissionais de diversas áreas e demais pessoas da sociedade) metodologias socioambientais com base na Psicologia Social e na Psicologia Ambiental, com o objetivo de capacitar pessoas interessadas no enfrentamento das vulnerabilidades ambientais e sociais.

Dentre os principais objetivos do curso, buscou-se:

1.  Trabalhar a partir de diferentes realidades e abordagens da psicologia, em uma perspectiva socioambiental e transdisciplinar, de acordo com o contexto atual;
2.  Facilitar processos de ensino-aprendizagem pautados em metodologias ativas e participativas que favoreçam a vivência e a integração dos aspectos socioculturais e afetivos de populações segregadas socioespacialmente, tradicionais, originárias/indígenas e quilombolas, considerando os sentidos decoloniais [@santos2009epistemologias] dentro do fazer da psicologia;
3.  Ampliar as interlocuções entre o âmbito acadêmico e a comunidade em geral: líderes comunitários, indígenas, quilombolas, trabalhadores de políticas públicas, representantes de organizações da sociedade civil e demais atores sociais, visando ao enfrentamento da pandemia da Covid-19 e à potência de ação [@sawaia2009psicologia] desses públicos, efetivando um espaço de debate e troca de conhecimentos que se estenda para além do curso em si e ocorra de forma permanente; e
4.  Introduzir aos/às cursistas noções básicas sobre abordagens em psicologia socioambiental e suas possibilidades de utilização.

Com isso, organizou-se o curso em cinco módulos principais, nos quais se abordou área do conhecimento diferente, problemática do contexto, aspectos teóricos, metodologias participativas e pesquisas desenvolvidas no âmbito do Locus, do PPGP-UFC/Fortaleza e do PPGPPPP-UFC/Sobral. Mais adiante, apresenta-se detalhadamente cada um dos módulos.

## Delineamento e organização do curso

O curso de extensão constituiu-se de um espaço de reflexão sobre conteúdos previstos pelas disciplinas de Teorias e Práticas em Psicologia Social III, Psicologia Ambiental, entre outras da graduação e pós-graduação. Para além do ensino, o curso também dialogou diretamente com as pesquisas realizadas por mestrandos e doutorandos do PPGP e do PPGPPPP.

Considerando a necessidade de distanciamento físico, por conta da pandemia da Covid-19, o curso ocorreu na modalidade remota com momentos síncronos e assíncronos. Assim, os encontros foram realizados de forma online, uma vez por semana, em todas as sextas-feiras do mês de agosto e na primeira sexta-feira do mês de setembro de 2020, no horário das 16h às 18h, pela plataforma Google Meet, com duração de 2 horas/aula. A fim de contabilizar a carga horária de 20h para emissão de certificado, além das 10h em encontros síncronos, foram disponibilizadas leituras e atividades na Plataforma do Google Classroom (Sala de Aula do Google) para complementar as discussões e reflexões de forma assíncrona.

Quanto às inscrições do curso, estas foram realizadas de forma virtual pela plataforma Google Formulários, em julho de 2020. Inicialmente, a equipe de organização do curso planejou disponibilizar 100 vagas, contudo, diante da alta procura identificada, foram realizadas 162 inscrições. Com relação ao perfil de inscritos, além de estudantes de graduação, especialização, mestrado e doutorado, também foi registrada a participação de profissionais de políticas públicas, integrantes de organizações não-governamentais e participantes de movimentos sociais, de coletivos, além de líderes comunitários. A seguir, o quadro 1 sintetiza o perfil dos estudantes inscritos quanto às áreas de formação.

+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Graduação**      | Psicologia; Pedagogia; Sociologia; Direito; História; Nutrição; Finanças; Medicina; Gestão de Turismo; Arquitetura e Urbanismo; Geografia; Ciências Ambientais; Ciências Biológicas; Engenharia de Pesca; Engenharia Ambiental; Gestão Ambiental; Física. |
+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Especialização** | Saúde; Legislação Social, Políticas Públicas e Trabalho Social.                                                                                                                                                                                           |
+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Mestrado**       | Psicologia; Interdisciplinaridade em Humanidades; Ciências Marinhas Tropicais; Desenvolvimento e Meio Ambiente.                                                                                                                                           |
+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Doutorado**      | Psicologia; Saúde Coletiva; Sociedade e Meio Ambiente.                                                                                                                                                                                                    |
+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Quadro 1 - Áreas de formação (graduação e pós-graduação) dos estudantes inscritos no curso.

Quanto às localizações dos participantes, o curso chegou a 52 cidades, distribuídas entre 17 Estados, nas 5 regiões do Brasil. O quadro 02 apresenta a localização das cidades conforme as regiões do país:

+-----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Regiões do Brasil** | **Estados e cidades brasileiras**                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+-----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| \                     | Ceará (Fortaleza, Caucaia, Cascavel, Quixadá, Guaiúba, Maracanaú, Aquiraz, Maranguape, Itapajé, Mauriti, Sobral, Pacatuba, Tabuleiro do Norte, Crato, Horizonte, Morrinhos, Pacajus, Limoeiro do Norte, Juazeiro do Norte, Palmácia, Canindé, Umirim, Tianguá, São Gonçalo do Amarante, Tauá e Barreira), Rio Grande do Norte (Natal, Apodi, Santa Cruz, Mossoró e Acari); Bahia (Ipirá); Paraíba (João Pessoa); Pernambuco (Camaragibe); Piauí (Floriano); Sergipe (Aracaju e São Cristóvão). |
| \                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| **Nordeste**          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
+-----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Sudeste**           | Rio de Janeiro (Rio de Janeiro, Niterói, Magé); São Paulo (São José do Rio Preto, Ribeirão Preto, São Carlos); Minas Gerais (Ouro Preto, Juiz de Fora).                                                                                                                                                                                                                                                                                                                                        |
+-----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Norte**             | Amazonas (Manaus); Pará (Redenção); Roraima (Boa Vista).                                                                                                                                                                                                                                                                                                                                                                                                                                       |
+-----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Centro-Oeste**      | Brasília (Distrito Federal); Goiás (Anápolis).                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
+-----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Sul**               | Rio Grande do Sul (Guaíba); Santa Catarina (Florianópolis).                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+-----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: Quadro 2 - Localização dos participantes do curso

No que tange às instituições, organizações e/ou movimentos sociais vinculados aos inscritos, foram registradas 55 vinculações diferentes, distribuídas entre associações (03), movimento social, hospital e clínica (02), institutos (05), secretarias e prefeituras (07), centros de referência e saúde (06), escolas e universidades públicas (17), centros educacionais e faculdades particulares (14).

Quanto à sistematização dos encontros, no total foram realizados cinco módulos, a saber:

1.  Perspectivas teóricas e metodológicas participativas (88 participantes);
2.  Desenvolvimento humano, formação profissional e participação (101 participantes);
3.  Povos originários e questões transculturais (92 participantes);
4.  Políticas públicas de saúde e assistência social (83 participantes); e
5.  Cidades, movimentos socioculturais e participação (77 participantes).

A facilitação foi realizada pela coordenadora do Locus e pelos pesquisadores de pós-graduação (mestrado e doutorado) que compõem o laboratório, além de convidados. As pesquisas e experiências foram apresentadas e discutidas, possibilitando a construção coletiva do conhecimento.

Uma bibliografia foi disponibilizada previamente para que os participantes pudessem trazer questionamentos para os encontros. O material utilizado como referência em cada aula foi disponibilizado em uma pasta pública no Google Drive, sendo organizado em uma Sala de Aula do Google (Google Classroom). Por fim, após contabilizar as frequências e atividades respondidas pelos participantes, 74 certificados foram emitidos e enviados por e-mail.

## Facilitação dos eixos temáticos: trocas de experiências e ensino

Ao longo do curso de extensão, debateu-se sobre como as perspectivas socioambiental e histórico-cultural contribuem para a compreensão das problemáticas sociais do contexto nacional. Foram abordados conceitos de áreas específicas (Psicologia, Geografia, Educação, Arquitetura e Urbanismo, Sociologia, etc.) relacionando-os com os contextos estudados, métodos e processos de facilitação que contribuem para inserção no campo, levantamento de necessidades, desenvolvimentos de ações, construção e partilha de conhecimentos, etc., a partir de uma perspectiva participativa, envolvendo profissionais, estudantes e residentes dos contextos em estudo.

Essas experiências, a partir de um posicionamento histórico-cultural [@vygotsky1996teoria; @lane1989psicologia], decolonial [@santos2009epistemologias] e ético-político [@sawaia2009psicologia; -@sawaia2011sofrimento; @martinbaro2011desafios; -@martinbaro2017critica], permitiram o desenvolvimento de modos de aproximação e de ações em diversos campos de pesquisa e de intervenções que configuraram propostas metodológicas ativas e participativas [@montero2007hacer; @freire1980conscientizacao]. Estas metodologias desenvolvidas originam-se das necessidades de chegar até as populações em situação de vulnerabilidade social e ambiental, de desigualdades e de sofrimento ético-político.

As metodologias apresentadas no curso também foram além de uma centralidade somente na ciência psicológica, para buscar uma transdisciplinaridade como caminho de criação de um campo novo que abarque várias disciplinas que propiciem uma compreensão global dos problemas ambientais, sociais e humanos, possibilitando a emergência de saberes que conectem Psicologia, Educação, Geografia, Ciências Ambientais, Ciências Sociais, dentre outras áreas, para abarcar a diversidade cultural e metodológica demandada.

Devido ao contexto da pandemia da Covid-19, foi feita uma readaptação à realidade do isolamento social, demandando uma maior inserção do curso na comunidade de forma mais acessível pelas plataformas online, alcançando um grande número de pessoas. Ao todo, o curso teve cinco encontros, cada um correspondente a um módulo, dentro de grandes eixos temáticos. A seguir, apresentamos as principais características de cada módulo.

### Perspectivas teóricas e metodológicas participativas

Esse módulo contou com a facilitação de Andie de Castro Lima (mestranda no PPGP-UFC/Fortaleza), Fábio Pinheiro Pacheco (doutorando no PPGP-UFC/Fortaleza) e Zulmira Bomfim, autora do instrumento e coordenadora do Locus. No total, participaram 88 cursistas.

Neste encontro, buscou-se apresentar a construção do curso, contextualizando o modo como a ideia surgiu e a forma como foi organizado. Realizou-se, também, uma introdução às bases teóricas e metodológicas da Psicologia Social Sócio-histórica [@lane1989psicologiasocial] e da Psicologia Ambiental de vertente transacionalista [@garciamira1997aportacion; @bomfim2010cidade], destacando a forma como essas duas se combinam para a construção de uma perspectiva socioambiental dentro do Locus. Discutiu-se, ainda, sobre os aspectos participativos na articulação entre o ensino, a pesquisa e a extensão. Neste momento, enfatizou-se a importância dos métodos participativos na facilitação de ações psicossociais voltadas para a transformação social [@montero2007hacer; @freire1980conscientizacao].

Na ocasião, também foi apresentado o Instrumento Gerador de Mapas Afetivos [@bomfim2010cidade; @bomfim2014affective], desenvolvido pela coordenadora do Locus, Zulmira Bomfim, a partir de sua tese de doutorado, em 2003. Integrando as bases teóricas supracitadas, Bomfim [-@bomfim2010cidade] delineou um instrumento capaz de elaborar mapas afetivos, por meio dos quais se pode captar a síntese socioafetiva do encontro do indivíduo com o lugar, seja ele a casa, seja o bairro, seja a cidade, etc.

### Desenvolvimento humano, formação profissional e participação

Neste segundo módulo, a discussão voltou-se para o diálogo entre desenvolvimento pessoal e coletivo, a participação na cultura, o desenvolvimento ao longo da vida e as repercussões disso nos processos educativos. Buscou-se, ainda, discutir os aspectos psicossociais da formação em Psicologia e o trabalho do psicólogo na educação e arte como proposta intercultural. A facilitação do módulo se deu por Nara Maria Forte Diogo Rocha (Professora do Departamento de Psicologia da UFC-Fortaleza e do PPGPPPP-UFC/Sobral), Helenira Fonseca de Alencar (Doutora em Educação), Janaína Farias de Melo (doutoranda no PPGP-UFC/Fortaleza) e Benedito Rodrigues (mestrando no PPGPP-Sobral). No total, participaram 101 cursistas.

Para a discussão entre o desenvolvimento pessoal e coletivo e a participação na cultura, a dinâmica da “Vida em Verso” (Haicai) foi realizada com o objetivo de expressar a relação entre o ser humano e a natureza a partir de um olhar para as mudanças possíveis na vida. Além disso, foi relevante abordar, no campo da educação, sobre a experiência da sala invertida (realização de atividades e exercícios em grupo e atendimento do professor), diferente da sala tradicional (realização de explanações pelo professor aos alunos). Por fim, foram abordadas a experiência do psicólogo escolar ao criar espaços para circulação das falas dos alunos e a ressignificação do cotidiano com novas atividades criadas em grupos.

### Povos originários e questões transculturais

A discussão do terceiro módulo voltou-se para o processo de inserção comunitária [@montero2007hacer] em aldeias indígenas e outras comunidades tradicionais. Enfatizou-se como são estabelecidos os primeiros contatos e os modos de delineamento de pesquisa e extensão participativas, considerando a participação dos sujeitos. O módulo foi ministrado por Maria Zelfa de Souza Feitosa (pós-doutoranda no PPGP-UFC/Fortaleza), Francisco Jésus Dias Mota Araújo (mestrando no PPGP-UFC/Fortaleza), Janaína Farias de Melo (doutoranda no PPGP-UFC/Fortaleza) e Halaine Cristina Pessoa Bento (mestranda no PPGP-UFC/Fortaleza). No total, estiveram presentes 92 cursistas.

No módulo, Francisco Jésus optou por trazer uma discussão sobre interculturalidade a partir de um diálogo decolonial [@santos2009epistemologias] na Serra dos Encantados (Aratuba), Pacatuba, Ceará: os afetos e fazeres com o povo Pitaguary. A partir do Programa Locus e da sua tese de doutorado, Zelfa Feitosa apresentou a própria experiência como pesquisadora dentro da aldeia indígena Pitaguary, abordando o processo de inserção na comunidade e o delineamento de sua tese de doutorado, que estudou os direitos dos povos indígenas, compreendendo os afetos e os conflitos implicados nas vivências de lideranças indígenas [@feitosa2019liderancas]. Ademais, Zelfa também apresentou o "Jogo como intervenção sociocultural, colaborativa e de potência para ação" [@feitosa2019liderancas], atividade desenvolvida com crianças indígenas da referida aldeia.

Nesse sentido, buscando novas possibilidades metodológicas dos mapas afetivos [@bomfim2010cidade], Janaína de Melo abordou o delineamento de sua pesquisa de doutorado no campo da transculturalidade entre Ceará e Japão sob um viés dos jovens cearenses. Dessa forma, trouxe uma reflexão acerca dos sujeitos a partir dos seus aspectos sociais e culturais, entendendo os espaços como dinâmicos, em constante processo de construção simbólica [@tavares2014comunicacao].

Dando continuidade às discussões sobre culturas no Brasil, Halaine Pessoa apresentou a sua pesquisa de mestrado com a população migrante e refugiada venezuelana, que chega pelo estado de Roraima em busca de melhores condições de vida. Assim, foi apresentando um olhar da Psicologia Ambiental na esfera da experiência, da vivência, dos sentidos e da apropriação dos espaços dos venezuelanos com o território brasileiro [@moser1998psicologia], além da sua experiência com este público em um abrigo para refugiados venezuelanos da Operação Acolhida, na cidade de Boa Vista (RR).

### Políticas públicas de saúde e assistência social

O módulo quatro apresentou as áreas de Assistência Social e Saúde, fazendo uma interlocução com a Psicologia Ambiental e Psicologia Social. As metodologias participativas utilizadas nesses contextos, nos âmbitos do trabalho, da pesquisa e do ensino, enfatizaram questões relacionadas à importância da territorialização nas práticas profissionais nas políticas públicas elencadas e à compreensão dos elementos afetivos envoltos em situações promotoras de vulnerabilidade social e risco vivenciadas pelos usuários da política.

A facilitação do módulo ficou a cargo de Andie de Castro Lima (mestranda no PPGP-UFC/Fortaleza), José Reginaldo Feijão Parente (doutorando no PPGP-UFC/Fortaleza), Elcides Hellen Ferreira Landim Barreto (doutoranda no PPGP-UFC/Fortaleza) e Cícera Mônica da Silva Sousa Martins (doutoranda no PPGP-UFC/Fortaleza). No total, o módulo contou com a participação de 83 cursistas.

A atividade foi realizada partindo de experiências de pesquisa e intervenção em dois campos de políticas públicas: Saúde e Assistência Social. A escolha por essas temáticas se deu a partir do entendimento das políticas de saúde e de assistência social como principais campos de atuação do profissional da psicologia no setor público, tanto na linha de frente, atendendo a população, quanto nos processos de gestão e capacitação de trabalhadores do Sistema Único de Saúde (SUS) e Sistema Único da Assistência Social (SUAS).

Para isso, a aula foi realizada em duas etapas: um momento teórico conceitual, sobre as bases fundamentais para a compreensão do funcionamento do SUS e do SUAS, e, posteriormente, a apresentação do uso do Instrumento Gerador de Mapas Afetivos - IGMA [@bomfim2010cidade; @bomfim2014affective], como ferramenta de pesquisa e intervenção nos dois campos supracitados. Os dois facilitadores do primeiro momento não só focaram na discussão da estrutura organizacional e dos serviços prestados pelas políticas de Saúde e de Assistência Social, como também iniciaram um debate sobre a importância do compromisso social do psicólogo na atuação no campo de políticas públicas [@sawaia2009psicologia].

Em seguida, foram apresentadas duas situações de aplicação da metodologia IGMA em dois equipamentos: Unidade Básica de Saúde (UBS), na cidade de Icó, e Centro de Referência em Assistência Social (CRAS), na cidade de Maracanaú, região metropolitana de Fortaleza. Inicialmente, Hellen Barreto apresentou o processo de construção e os resultados de sua pesquisa, discutindo sobre como a compreensão dos afetos presentes na UBS pode ampliar as possibilidades de ações e serviços mais eficazes, uma maior implicação do usuário com um modo de viver saudável [@barreto2017estima].

Em seguida, Andie Lima e Mônica Martins trouxeram a discussão sobre os afetos para o âmbito da assistência social. Neste ponto, foram apresentados os principais resultados das pesquisas e ações desenvolvidas no CRAS, tendo como foco de abordagem a importância da territorialização e da compreensão dos elementos afetivos que perpassam a apropriação desse território pelos moradores [@lima2019estima]. Os exemplos apresentados mostraram o potencial do IGMA tanto para diagnóstico dos vínculos de moradores com os equipamentos das políticas públicas acessadas, como para intervenção e evocação de reflexões acerca da importância da compreensão dos afetos no processo de implementação e condução de uma política pública.

### Cidades, movimentos socioculturais e participação

Na última etapa, foi realizada uma discussão sobre espaços culturais, construção de participação e resistência em movimentos sociais urbanos. Este módulo foi ministrado por Fábio Pinheiro Pacheco (doutorando no PPGP-UFC/Fortaleza), José Reginaldo Feijão Parente (doutorando no PPGP-UFC/Fortaleza), Cícera Mônica da Silva Sousa Martins (doutoranda no PPGP-UFC/Fortaleza) e Daniel Welton Arruda Cabral (doutorando no PPGP-UFC/Fortaleza). No total, estiveram presentes 77 participantes. O módulo apresentou métodos e processos de facilitação de pesquisa, ensino e extensão, destacando as trilhas socioambientais [@morais2011nas] e culturais como possibilidades de reflexão-ação e construção coletiva; e a organização de movimentos sociais de luta [@cabral2015relacao; @martins2020afetividade] e resistência às situações de segregação socioespacial [@pacheco2018afetividade].

Inicialmente, Reginaldo Parente partiu de uma discussão sobre patrimônio cultural e afetividade para abordar a experiência no delineamento de sua pesquisa de doutorado. Em sua tese, debruçou-se sobre o fenômeno dos afetos vivenciados em relação ao patrimônio cultural no contexto da cidade de Sobral-Ceará, discutindo sobre as implicações sociais e o desenvolvimento infraestrutural presentes nas relações pessoa-ambiente [@parente2020patrimonio]. Em seguida, Daniel Cabral abordou a organização dos moradores da Prainha do Canto Verde, discutindo sobre os modos de vida, os laços de solidariedade, a cooperação e os processos reivindicatórios na construção de luta e participação política e social [@cabral2015relacao].

Por fim, Fábio Pacheco e Mônica Martins trouxeram uma discussão sobre os processos de desapropriação do espaço. Fábio Pacheco abordou a importância da pesquisa-ação [@montero2007hacer] e o desenvolvimento de atividades comunitárias [@gois2005psicologia]. Com base em sua pesquisa de mestrado, discutiu as implicações psicossociais presentes nos processos de desapropriação do espaço [@pacheco2020contribuicoes], ao reafirmar que a especulação imobiliária acentua o caráter segregacionista do desenvolvimento urbano, impactando a vida da parcela pobre da população que se torna o alvo de remoções [@pacheco2018afetividade]. Levando a discussão para o contexto rural, Mônica Martins apresenta sua experiência de inserção comunitária e delineamento de pesquisa ao discutir sobre os impactos psicossociais das obras do cinturão das águas do Ceará e as práticas de resistência desenvolvidas pela população (Martins, 2020).

Todos os módulos se fundamentaram em perspectivas teóricas e metodológicas nas áreas apontadas considerando o contexto de desigualdades sociais e vulnerabilidades sociais, bem como a dialética exclusão-inclusão social, as teorias decoloniais e os povos originários (Santos & Meneses, 2011). Apresentou-se como a Psicologia Social latino-americana [@lane1989psicologia; @martinbaro2011desafios] e a Psicologia Ambiental de base transacionalista [@garciamira1997aportacion; @bomfim2010cidade] contribuem para a compreensão de fenômenos socioambientais de forma teórico-prática. A categoria afetividade [@sawaia2011sofrimento] destacou-se como eixo de observação, de investigação, de intervenção e de análise para superar as dicotomias próprias da ciência psicológica que separam a subjetividade da objetividade, a racionalidade dos afetos, o indivíduo do social, dentre outras que se aproximam de uma postura prescrita e que naturalizam a dialética da exclusão-inclusão social.

## Processo de aprendizagem e avaliação

Ao final do quinto módulo, foi pedido aos alunos para preencherem uma ficha de avaliação, com o intuito de compreender como se deu o processo de aprendizagem ao longo do curso e, também, de mensurar o impacto das temáticas trabalhadas no decorrer da trajetória profissional dos discentes. A ficha de avaliação foi criada na plataforma do G Suite (Google Forms) em formato de questionário eletrônico, sendo avaliados cinco aspectos: Ambiente Virtual, Aspectos Pedagógicos, Suporte Técnico, Equipe Docente e Moderação e Autoavaliação. Em cada um dos cinco tópicos supracitados eram apresentadas questões objetivas, com cinco alternativas da escala de concordância, com números entre 1 (discordo totalmente) e 5 (concordo totalmente).

No final do formulário, havia um tópico de comentários, com perguntas sobre o interesse em participação em outras ações promovidas pelo Locus, sugestões de temas para próximas formações e demais colocações. Embora a adesão à ficha de avaliação fosse voluntária, 45 inscritos preencheram esse instrumento avaliativo. Os resultados foram analisados e compilados pela comissão organizadora do evento.

Acerca do primeiro tópico, ambiente virtual, as oito alternativas versavam sobre a utilização das plataformas virtuais escolhidas para a condução do curso (Google Classroom, Google Forms e Google Meet). Em todas as alternativas, mais de 90% dos alunos avaliaram a escolha e condução de forma satisfatória, marcando “concordo” e “concordo totalmente”. Na pergunta final, em que foi pedida uma opinião geral sobre a vivência nos ambientes virtuais do curso, o índice de satisfação foi unanimemente positivo, obtendo as seguintes porcentagens, concordo (19,5%) e concordo totalmente (80,5%).

Na sessão de comentários adicionais acerca do tópico “ambiente virtual”, os alunos afirmaram que estão em processo de adaptação a essas ferramentas, em especial em atividades realizadas nesse período pandêmico. Como sugestão, foi apontada a necessidade de trazer mais indicações de leituras disponíveis para download no Classroom e foram elogiados os avisos recebidos por email a cada conteúdo postado.

No tópico dois, referente aos aspectos pedagógicos, as nove afirmativas versavam sobre o formato, a duração e o conteúdo das aulas apresentadas nos cinco módulos. As taxas de satisfação, no que se referia aos conteúdos, ao formato e ao dia de realização, obtiveram níveis de satisfação de 82,9%, o que se equipara ao que foi apresentado nos comentários adicionais e nas sugestões. Neste espaço, os discentes apontaram que os conteúdos escolhidos contemplavam suas necessidades e que a metodologia dos docentes fora efetiva.

Porém, houve uma queixa em comum sobre a duração das aulas de cada módulo. Os discentes consideraram a duração de duas horas curta e visualizaram que isso limitou o tempo de fala dos docentes. Foi pedido pelos inscritos que, nos próximos cursos ofertados pelo Locus, as aulas tenham duração maior e que, se for preciso, o tema seja dividido em mais de um dia, para uma maior absorção do conteúdo. Alguns também sugeriram novos cursos para aprofundamento das temáticas apresentadas, como território, políticas públicas e sustentabilidade.

No terceiro tópico avaliativo, foram contemplados aspectos da efetividade e da prestação de serviços fornecidos pelo suporte técnico do curso. As cinco alternativas versavam sobre o tempo e a efetividade da resposta do suporte, bem como sobre a qualidade do serviço prestado. Na alternativa avaliativa final, obteve-se resultado de mais de 90% de satisfação com os serviços. Na caixa de comentários adicionais, foram elogiadas a presteza, a rapidez nas respostas de demandas, a atenção e o acolhimento dos discentes. Alguns dos inscritos relataram não ter precisado dos serviços de suporte, já outros relataram satisfação com o serviço quando buscado.

O quarto tópico abordou o desempenho da equipe docente e mediadora, com onze alternativas voltadas a avaliar as temáticas expostas pelos docentes, a metodologia de ensino, a interação docente-aluno, os esclarecimentos de dúvidas e o papel da moderação no processo. A média de resposta por alternativa é de mais de 90% de satisfação com os docentes e mediadores, levando em consideração o apanhado das porcentagens de cada questão. No espaço de comentários adicionais, os inscritos relataram que não só aprovaram o modo de condução das aulas de cada módulo, como também notaram o esforço e a dedicação da equipe, assim como o cuidado e estudo dedicados a cada tema. Também foi mencionado que seria interessante, em próximos cursos, ter uma pasta com materiais bibliográficos complementares sobre a temática de cada módulo, para ampliar os conhecimentos adquiridos.

No último tópico avaliativo, a autoavaliação, as treze afirmativas versavam sobre questões técnicas, pedagógicas e vivenciais dos alunos perante sua experiência como discente do curso. Fatores como motivação para participar das aulas, contribuição do curso na formação profissional, interesse nos conteúdos abordados, participação e compreensão dos conteúdos apresentados foram avaliados, em sua maioria, de forma positiva. A maior parte dos alunos não teve dificuldades em manejar a plataforma Classroom e o Meet, ainda que 19,5% dos alunos tenham tido problemas com o acesso à internet.

No que se refere à aplicabilidade dos conteúdos apresentados em sua carreira profissional e no seu currículo, a maioria dos alunos se mostrou favorável a reaplicar o que foi aprendido em suas atividades cotidianas, sendo registrados 22% de concordância e 78% de concordância total. Nos comentários adicionais, os alunos relataram que ficaram felizes em participar do curso, bem como consideram a utilização das metodologias apresentadas perante o percurso em suas atividades profissionais e acadêmicas.

Além disso, alguns mencionaram a relação dos temas abordados com seus trabalhos de conclusão de curso e suas linhas de pesquisa, reafirmando o interesse em temáticas voltadas a metodologias ativas em psicologia ambiental. Na caixa de sugestões, foi pedido para, nos próximos cursos, haver módulos com maior duração em horas/aula e com intervalos durante as aulas. Foram também sugeridos alguns temas esperados para as próximas formações do Locus, tais como pesquisas em ambientes urbanos, afetividade e território, comportamento pró-ambiental, compromisso ecológico, práticas em psicologia ambiental; houve também a sugestão de um curso intensivo sobre IGMA, ambientes restauradores, bem viver e questões ambientais atuais.
