---
author: 
  - name: Gabriele Sousa Costa
    orcid: 0000-0003-2905-4144
    email: gabrielesousa304@gmail.com 
    affiliations: 
      - name: Universidade Federal do Ceará    
  - name: Nayana Rios Nunes da Silva
    orcid: 0000-0001-5182-2344
    email: nayanarios87@gmail.com 
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Francisco Pablo Huascar Aragão Pinheiro
    orcid: 0000-0001-9289-845X
    email: pablo.pinheiro@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Marinara Nobre Paiva
    orcid: 0000-0003-4084-5289
    email: marinaranobre@alu.ufc.br
    affiliations: 
      - name: Faculdade Anhanguera
  - name: Renata Guimarães de Carvalho
    orcid: 0000-0002-3592-7709
    email: renatagui.carvalho@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Kallyne Rose da Silva Rodrigues
    orcid: 0009-0001-0697-4493
    email: kallynerose@alu.ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Quitéria Alves Melo
    orcid: 0000-0002-2831-1631
    email: quiterialvesm@gmail.com 
    affiliations: 
      - name: Universidade Federal do Ceará
      - name: Universidade Federal do Rio Grande do Norte
  - name: Francisca Valéria de Sousa
    orcid: 0000-0002-5232-8812
    email: valeriasousa0140@gmail.com 
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Giovana Mayra Liberato de Lima
    orcid: 0000-0002-6442-8917
    email: giomayra@alu.ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Luiza Silva de Lima
    orcid: 0009-0009-8400-6381
    email: luizasilvv@alu.ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
language: 
  title-block-author-plural: "Autoras"
filters:
  - section-bibliographies
bibliography: costa_assessoria_saae.bib
reference-section-title: Referências
---

# “Se eu pegar o atendimento e não resolver, ele pensa que o problema sou eu”: relatório técnico conclusivo de assessoria sobre uma intervenção em Clínica da Atividade com profissionais de atendimento ao público

## Introdução

O serviço de atendimento ao público mostra-se essencial para a mediação de interesses entre a organização e os clientes. Apesar de parecer uma atividade de fácil desenvolvimento, ela promove significativos embates no espaço laboral. Em relação ao trabalho de mediação, são percebidas diferentes compreensões, por exemplo, a da instituição, que busca transformar o atendente em uma personificação dos interesses da empresa, e a do usuário, que, muitas vezes, não reconhece a singularidade do trabalhador e o responsabiliza por todas as suas demandas [@ferreira2000serv_atend_publico].

Os operadores de teleatendimento, em particular, têm um roteiro, chamado de script, que descreve os procedimentos a serem realizados no contato com o público. Entretanto, de acordo com estes trabalhadores, esse script não condiz com a realidade encontrada ao exercer a atividade, tendo em vista problemas não previstos a priori que são trazidos, principalmente, pelos usuários [@ziliotto_oliveira_2014].

Em pesquisa realizada com ex-profissionais de telemarketing de duas empresas em Salvador, Jesus et al. [-@jesus_benevides_dutra2019prejuizo_alforria] encontraram que os trabalhadores consideravam inadequadas as condições de trabalho no setor de atendimento. Foram apontadas pressões relativas ao atendimento de metas e intimidações de gestores com ameaças de demissão. Os autores afirmaram que, apesar de os participantes julgarem importantes as relações construídas no ambiente de trabalho, principalmente no suporte entre os colegas, muitos ressaltaram que tal sentimento de pertença com o coletivo era incapaz de combater o medo que sentiam das regras das instituições. Além disso, destacaram algumas repercussões à saúde, como desgaste físico e mental.

Teixeira e Moreira [-@teixeira_moreira_2021] apontam que o controle das empresas de call center sobre a produtividade e as relações interpessoais dos atendentes têm contribuído para o sofrimento psíquico destes. A ausência de liberdade na realização das atividades e as punições por não conseguir reproduzir o script da empresa mostraram-se prejudiciais à saúde dos trabalhadores, que passaram a manifestar sentimento de raiva, medo, exaustão mental e ansiedade. Destacaram-se, ainda, os impactos causados pela jornada laboral, como a pouca disponibilidade de tempo para ir ao banheiro ou realizar suas refeições. Pereira [-@Pereira_2022], em pesquisa sobre as experiências e perspectivas de ex-trabalhadores de call centers em Pernambuco, também constatou que os operadores tinham um tempo limitado para irem ao banheiro e que, na maioria das vezes, precisavam dar explicações para os supervisores quando demoravam.

De acordo com Pacheco e Rosa [-@pacheco_rosa2016estresse_fatores], em estudo realizado com atendentes de uma clínica médica, em Brasília, os principais fatores de estresse no ambiente laboral estavam relacionados à falta de reconhecimento na realização das atividades, aos conflitos no setor, à pressão dos gestores e à sobrecarga de trabalho. Além disso, verificaram que a forma violenta com que os clientes se expressavam e as reclamações do atendimento também contribuíam para o estresse dos trabalhadores. Foi visto, contudo, que a maioria dos participantes lidava de maneira positiva com tal condição, uma vez que não se deixava abater facilmente com os problemas e costumava dar o máximo para atingir as metas propostas pela empresa.

Ainda no contexto brasileiro, Rocha e Aguillera [-@rocha_aguillera_2016] apontaram que a rotatividade no departamento de call center estava associada ao abuso de cobranças, ao controle sobre os corpos dos trabalhadores e ao baixo salário. Os autores destacaram ainda os desafios para o crescimento profissional, como a priorização do trabalho robótico e estatístico, os quais desconsideram os conhecimentos e as potencialidades dos atendentes. Observou-se, para além disso, que muitos deles permaneciam no setor como uma forma de sustentar a vida pessoal ou a formação acadêmica.

Ribeiro et al. [-@Ribeiro2019] realizaram uma pesquisa com 363 operadores de call centers em empresas de Montes Claros-MG. Sendo assim, identificaram maiores níveis de estresse entre as operadoras de call centers. Isto pode ser explicado por questões de gênero, na medida em que as mulheres são sobrecarregadas com o trabalho reprodutivo, ou seja, os cuidados exercidos no ambiente doméstico. Além disso, os níveis de estresse desses operadores, sejam do sexo masculino, sejam do feminino, são mais elevados quando comparados com os de profissionais que tendem a lidar com pressões maiores, como médicos e policiais militares.

Em relação ao trabalho durante a pandemia da covid-19, a pesquisa de Brandão e Ramos [-@brandao_ramos_2023] com teletrabalhadores em Portugal apontou que a modalidade virtual possibilitou que as empresas dessem seguimento às suas atividades econômicas mesmo em um cenário difícil. Sobre a percepção dos participantes, estes apresentaram, como ponto positivo, o sentimento de bem-estar ao receberem boas condições de trabalho das instituições e, como negativo, a menor interação entre os pares.

Ademais, Santos et al. [-@dos_santos_saraiva_da_silva_marolla_2022], em pesquisa realizada com 652 gestores e liderados brasileiros, apontaram que muitos trabalhadores passaram a se sentir despreparados na realização das suas tarefas durante a pandemia. Os autores observaram que um dos motivos para a insegurança dos profissionais estava relacionado ao pouco tempo que as organizações tiveram para transmitir suas atividades presenciais para a modalidade virtual.

O presente trabalho relata uma assessoria prestada ao setor de atendimento ao público de um Serviço Autônomo de Água e Esgoto (SAAE). Este SAAE estava localizado em uma cidade no interior do estado do Ceará. A intervenção foi realizada pela equipe do Laboratório de Práticas e Pesquisas em Psicologia e Educação (LAPPSIE) da Universidade Federal do Ceará, Campus Sobral.

O SAAE contava com duzentos e cinquenta trabalhadores, os quais eram responsáveis por manter o abastecimento de água para 72 mil residências e cuidar do tratamento de esgoto de mais de 45 mil domicílios. O setor de atendimento contava com quatorze trabalhadores que eram distribuídos nas modalidades presencial, virtual e central telefônica. O atendimento presencial era responsável por mediar a relação entre os usuários e a instituição, acolhendo demandas como serviços de ligação e fiscalização de água, serviços de esgoto, emissão de segunda via de conta, extratos de débitos e negociações, por exemplo.

O atendimento virtual foi criado em 2020, durante a pandemia da covid-19, com o objetivo de dar continuidade aos serviços já realizados pelo atendimento presencial e ampliar a comunicação com os usuários. Apesar do fim da necessidade de isolamento social, esta modalidade de atendimento foi mantida. Em relação ao atendimento pela central telefônica, eram acolhidas reclamações, solicitações, sugestões, bem como realizados esclarecimentos aos usuários.

Diante desse cenário, foi identificada pelo setor de gestão de pessoas do SAAE, a partir de relatos dos funcionários, uma demanda relacionada a adoecimento e sofrimento decorrentes do contexto de trabalho. Dentre as dificuldades apontadas pelos trabalhadores estavam a ausência de prescrição das tarefas e de treinamentos. As orientações e as regras sobre como proceder eram repassadas por outros atendentes que já estavam há mais tempo no setor, o que gerava impasses, pois a maneira como cada um lidava com as demandas era diferente.

Dessa maneira, após avaliar as demandas, a equipe de intervenção propôs utilizar a elaboração de um manual de procedimentos como forma de mediar a discussão entre os trabalhadores sobre a atividade realizada. Como se verá adiante, esse processo de reflexão coletiva sobre o trabalho e a construção de novas formas de agir implicam melhoria da saúde. Ademais, o documento produzido poderia auxiliar na construção de prescrições para os trabalhadores, assim como orientar novos atendentes que chegassem ao setor.

### Fundamentação teórica: Clínica da Atividade

A equipe interventiva teve a Clínica da Atividade como referencial teórico e metodológico. Esta é uma metodologia que tem como premissa a transformação e a compreensão do trabalho, como processos indissociáveis [@clot2017clinica_atividade]. Nesse sentido, diferente das abordagens tradicionais em psicologia do trabalho, o interveniente não ocupa uma posição de expert, não dita nem estabelece normas procedimentais. Em contraponto, coloca-se como mediador do processo de análise do trabalho, que deve ser realizado em conjunto com os trabalhadores, na medida em que estes desenvolvem suas atividades [@clot2013oficio_saude].

Nesse caso, à equipe de intervenção não coube somente descrever as atividades que deveriam ser realizadas pelos atendentes e transpô-las para o Manual. Seu objetivo foi, de fato, mobilizar o coletivo de trabalhadores para assumir a posição de experts de suas próprias atividades para, assim, construírem, em conjunto, formas bem sucedidas de realização do trabalho. Firmada essa posição, a transformação do trabalho se estabelece a partir do desenvolvimento do poder de agir dos profissionais, que, por sua vez, é fundamental para a promoção da saúde do trabalho.

Diante dessa perspectiva, entende-se que o trabalho se estrutura através da arquitetura do ofício. Este é responsável por dar forma às particularidades de cada atividade profissional. Para tanto, essa arquitetura se desenvolve através de quatro dimensões, a saber: impessoal, que corresponde às prescrições estabelecidas pela organização; interpessoal, que se refere às relações entre pares, usuários do serviço e chefias; pessoal (estilo), que diz respeito ao trabalhador, à sua singularidade, sua subjetividade e sua atividade individual; e, por fim, transpessoal, a qual corresponde à cultura do coletivo de trabalho. Esta dimensão se estabelece através de normas implícitas construídas pelos trabalhadores as quais orientam a atividade de forma similar às prescrições oficiais [@clot2010trab_poder].

A transpessoalidade se dá através da memória do coletivo de trabalho. Portanto, ao mesmo tempo em que não possui um mandante determinado, permite que todos os trabalhadores se apropriem dela e realizem seu trabalho sem estar, a todo instante, se reinventando diante de cada imprevisto [@clot2010trab_poder].

## Método

### A Clínica da Atividade como aporte metodológico

Clot [-@clot2010trab_poder] distingue a abordagem realizada pela Clínica da Atividade das estratégias tradicionais de intervenção. Enquanto as últimas compõem-se apenas por recomendações, o objetivo da primeira consiste na introdução de uma ferramenta metodológica que possa vir a ser um dispositivo de ação para o próprio grupo de trabalhadores. Nesse sentido, a análise do trabalho busca ajudar o coletivo a restabelecer o seu poder de agir, que se desenvolve a partir da apropriação de ferramentas para a ação construídas conjuntamente. Desta forma, os métodos empregados almejam revitalizar a atividade profissional assim como a elaboração de conhecimento em torno dessa dinâmica.

Nesse ponto, é mister estabelecer a distinção entre atividade realizada e real da atividade para a compreensão da perspectiva desta abordagem clínica. Tal diferenciação deriva de uma anterior: aquela realizada entre tarefa prescrita e atividade. A noção de tarefa remete ao que deve ser feito em determinada situação de trabalho sob as condições e regras definidas pela organização [@souto_lima_osorio_2015]. A despeito disso, a atividade realizada, que contempla a dimensão observável da ação, não abarca o real. Dito de outro modo, aquilo que de fato é feito pelo trabalhador trata-se de um grupo de ações que venceram um conflito entre diversos possíveis. É justamente sobre tais possibilidades que repousa o conceito de real da atividade.

Nesse sentido a atividade já não está reduzida ao que se faz, ou seja, o realizado não detém o monopólio do real. O conjunto de ações suspensas e impedidas formam, junto com as atividades efetuadas, uma unidade discrepante. Ampliar o poder de agir, nesse ponto, significa “servir-se de suas experiências para fazer outras experiências” [@clot2010trab_poder, p. 147]. Clot [-@clot2010trab_poder] afirma que, no trabalho, o sujeito, quando não impedido, não para de reinventar suas ferramentas, deixando clara a assimilação dessa natureza criativa pela Clínica da Atividade para a compreensão da atividade laboral [@souto_lima_osorio_2015].

É por esta razão que a Clínica da Atividade se vale de métodos indiretos de análise. O real da atividade não pode ser acessado de maneira direta, seja pelo interlocutor seja pelo próprio sujeito. O termo indireto evidencia a proximidade entre a proposta aqui apresentada e a perspectiva histórico-cultural que tem Lev Vygotsky como principal expoente [@souto_lima_osorio_2015].

Desta forma, a intervenção utilizou a construção do manual de procedimentos para mediar a reflexão dos atendentes sobre seu fazer, de modo a acessar o real da atividade e viabilizar a construção de novos meios de ação. Nesse sentido, pretendeu-se que as interações do coletivo de trabalho, ao longo da intervenção, ajudassem no fortalecimento do gênero profissional, tendo em vista as soluções estilísticas encontradas por cada trabalhador que pudessem ser compartilhadas.

#### Clínica da Atividade e a Psicologia Histórico-cultural

Vygotsky [-@vygotsky1995obras] se interessa, entre outras questões, pelo desenvolvimento humano e afirma que as bases para esse processo são fornecidas pelas relações sociais, especificamente a interação e a transmissão da história humana, possíveis pela existência da linguagem. Nesse sentido, a atividade individual tem o social como fonte, a partir do qual se desenvolve. A partir disso, o indivíduo desprende-se dos modos sociais de conduta e cria sua própria ação.

Para Vygotsky, o sistema de signos, uma produção humana, ocupa posição privilegiada pelo papel que desempenha na instituição e na evolução social e cultural dos indivíduos [@pino1995semiotica_cognicao]. Além disso, para o autor russo, objeto e método mantêm uma relação estreita entre si. A definição do problema de pesquisa e das ferramentas de investigação ocorrem simultaneamente, de modo que o método é, ao mesmo tempo, princípio e produto da investigação. Nesse sentido, é preciso reconhecer a atribuição da mediação semiótica para o psiquismo humano, de sorte que, se a relação dos indivíduos com o mundo é indireta e intermediada por instrumentos psicológicos, a investigação deve levar isto em conta e utilizar métodos indiretos, nos quais se assuma um princípio histórico desenvolvimentista [@vygotsky1995obras].

Vygotsky [-@vygotsky1995obras] assinala três princípios os quais constituem as análises desenvolvidas nesta perspectiva. A primazia do processo sobre o produto é o primeiro deles. O objeto não pode ser concebido como uma forma estável e, já que é instituído historicamente, deve ser investigado em movimento, a partir do desdobramento do fenômeno nos principais momentos que o compõem. O segundo princípio diz respeito à contraposição das tarefas descritivas e explicativas de análise. É necessário ir além da mera descrição do fenômeno para explicar as relações que o originam, uma vez que o ponto central a ser alcançado é a gênese do processo, e não as suas manifestações externas. Dito de outro modo, o que se deseja alcançar é a emergência histórica e social do fenômeno. Esta última assertiva indica o terceiro e último fundamento desta abordagem: análise genotípica em detrimento da fenotípica [@vygotsky1995obras; @zanella_reis_titon_urnau_dassoler_2007].

O princípio histórico-desenvolvimentista propõe a investigação de condutas ou processos fossilizados, uma vez que estes detêm indícios de estruturas históricas complexas dos antepassados, ao mesmo tempo em que anunciam novas formações. Todavia, não se trata de tomá-los em sua forma acabada. É preciso impor-lhes movimento para que sejam compreendidos em uma perspectiva genética. Essa diretriz aponta para uma investigação baseada numa perspectiva social e histórica do psiquismo do sujeito, entendido como um processo, não como aquilo que é, mas como aquilo que está sendo baseado no que já foi [@vygotsky1995obras; @zanella_reis_titon_urnau_dassoler_2007].

De maneira análoga, na Clínica da atividade, a atividade dirigida é definida como a unidade base da análise psicológica. Como dito anteriormente, a atividade realizada é apenas um conjunto de reações vencedoras, de modo que as possibilidades descartadas, apesar de não serem acessadas diretamente, continuam agindo sobre a ação do sujeito. Em consonância com a metodologia histórico-desenvolvimentista, para conhecer o real da atividade, é necessário favorecer o desenvolvimento da atividade realizada, descristalizando-a. Nesse sentido, não se deve apenas compreender para transformar, mas transformar para compreender. A experiência só pode ser observada a partir desta transformação, não enquanto objeto, mas como processo [@clot2010trab_poder].

Diante disso, o interesse recai sobre a história do desenvolvimento, assim como suas possibilidades, seus impedimentos e seus princípios. Portanto, os dispositivos técnicos utilizados na Clínica da Atividade, como autoconfrontação, instrução ao sósia, oficina de fotos [@osorio_pacheco_barros2013oficinas_fotos] e carta ao remetente, esta última recentemente desenvolvida por estudante do Mestrado Profissional em Psicologia e Políticas Públicas desta universidade e seus colaboradores [@Oliveira2022], atuam como mediadores e transformam, indiretamente, a atividade do sujeito, deslocando-as para um novo contexto. Os recursos utilizados autorizam uma reentrada na ação, por meio da linguagem, que reorganiza e modifica a atividade já realizada pelo indivíduo e pelo coletivo de trabalho [@clot2010trab_poder].

### Participantes

A tabela 9.1 ([-@tbl-participantes]) apresenta a quantidade de atendentes que participaram do processo de intervenção, sendo nove mulheres e três homens. São apresentados, ainda, a idade dos trabalhadores, o tipo de atendimento que assumiam no setor, o tempo de carreira e o vínculo com a instituição.

|   Nome   | Idade | Tipo de atendimento |  Tempo  |   Vínculo    |
|:--------:|:-----:|:-------------------:|:-------:|:------------:|
|  Aline   |  26   |       Virtual       | 8 meses | Terceirizado |
|  Carla   |  22   |     Presencial      | 8 meses | Terceirizado |
|  Dário   |  55   |     Presencial      | 31 anos |   Efetivo    |
|  Flávia  |  40   |     Presencial      | 10 anos |   Efetivo    |
|  Joana   |  37   |     Presencial      |  1 ano  | Terceirizado |
| Leonardo |  26   |       Virtual       | 2 anos  | Terceirizado |
|  Marina  |  25   |     Presencial      | 8 meses | Terceirizado |
|  Marta   |  28   |     Presencial      | 8 anos  |   Efetivo    |
|   Rita   |  49   |     Presencial      | 8 anos  |   Efetivo    |
| Roberto  |  59   | Central telefônica  | 38 anos |   Efetivo    |
|   Sara   |  50   |     Presencial      | 2 anos  | Terceirizado |
|  Talia   |  26   |       Virtual       |  1 ano  | Terceirizado |

: Dados dos participantes {#tbl-participantes}

## Percurso da intervenção

A intervenção teve início em meados de abril de 2022 e terminou em julho do mesmo ano. Nesse período foram realizados 10 encontros semanais, com duração média de 1h30 cada, os quais ocorreram presencialmente no SAAE, durante o horário de expediente dos profissionais. As reuniões foram mediadas por cinco facilitadoras, registradas em áudios e transcritas pela equipe de intervenção.

### Encontro 1 

No primeiro encontro, os trabalhadores e a equipe de facilitadores se apresentaram. Em seguida, houve a exposição dos objetivos da intervenção. O primeiro método utilizado foi o "Curto/não curto” [@osorio_pacheco_barros2013oficinas_fotos]. Ao longo de cinco rodadas, os participantes jogaram os dados e comentaram sobre as atividades do setor. Marta, por exemplo, citou que gostava de realizar o serviço de transferência, mas que isso só era possível quando os usuários entregavam os documentos corretamente. A declaração hidrossanitária era uma atividade que Aline realizava com satisfação, porque conseguia resolver a demanda dos usuários de forma imediata.

De modo geral, ao longo dos diálogos, os participantes disseram que não conseguiam realizar algumas atividades a contento por falta de experiência e de orientações sobre como proceder em relação a elas. Esta era justamente a demanda que originou a intervenção: a ausência de prescrições. Também houve relatos de terem sido agredidos pelos clientes, física e verbalmente. Em um caso específico, um cliente chamou a reportagem de um site sensacionalista local para denunciar Joana. Já neste primeiro encontro, os trabalhadores elencaram estratégias para evitar agressões dos clientes, dentre elas, indicar o atendimento para a Marina, considerada a atendente mais calma da equipe. A estratégia de Marina era concordar com tudo que o usuário dizia, assim como sempre pedir desculpas pelos contratempos.

### Encontro 2

No segundo encontro, houve uma continuação da dinâmica "Curto/não curto”. Ao longo da atividade, Marina afirmou que não gostava de lidar com as demandas dos clientes que necessitavam da atuação das equipes que iam a campo executar serviços operacionais, como ligação de água, esgoto e reparo de vazamentos nas ruas. Estas equipes não cumpriam os prazos estabelecidos, e isso gerava insatisfação nos usuários do SAAE. Para Roberto, a redução das equipes de campo durante a pandemia contribui para tal situação. Ademais, Talia e Marina relataram que acabavam sendo responsabilizadas pelos atrasos. Elas relataram que os clientes eram demandados a avaliar o serviço de atendimento ao público do SAAE. Assim, elas recebiam avaliações negativas, não pelo trabalho delas em si, mas pelo fato de a empresa não conseguir atender aos clientes a contento.

Essa discussão sobre a avaliação dos clientes provocou grande envolvimento dos trabalhadores. Talia, por exemplo, ressaltou que, por um lado, o contato direto no atendimento presencial facilitava a compreensão dos clientes, já no virtual, contudo, os atendentes eram cobrados por mais agilidade na resolução dos problemas. Por outro lado, Leonardo comentou que não gostava de realizar o serviço de análise de água, mas considerava cômodo quando recebia essa demanda virtualmente. Esse serviço, que consistia basicamente em determinar se a água era própria para o consumo, era rapidamente realizado pelo SAAE, o que evitava o desgaste entre cliente e atendente.

Nos momentos finais deste encontro, relembraram outros episódios de violência que haviam sofrido, por exemplo, o dia em que duas usuárias jogaram papéis em Carla e Marina, pois não aceitavam os valores das faturas e exigiam que fossem revistas as cobranças. Além disso, ressaltaram que um cliente ameaçou agredir todas as atendentes, após ter recebido a notícia de que teria de pagar uma conta com valor alto. Leonardo ressaltou que as mulheres eram mais agredidas, pois, quando trabalhava no atendimento presencial, dificilmente era desafiado ou constrangido.

### Encontro 3

O terceiro encontro teve início com uma exposição da equipe de facilitadores sobre tarefas que deveriam ser realizadas pelos atendentes. O rol de atribuições, que tinha 71 itens, foi obtido com a gerente do setor a partir dos serviços que estavam cadastrados no sistema utilizado para registrar as demandas dos clientes. Ao se deparar com esta lista, por um lado, os participantes ficaram surpresos, pois não imaginavam que faziam tantas atividades. Por outro lado, também afirmaram desconhecer vários dos procedimentos. 

Diante disto, o senhor Roberto explicou que ali estavam serviços que já não eram mais realizados. Também foi notada a existência de serviços similares que estavam cadastrados com nomes diferentes. Além disso, havia vários que não estavam presentes na lista. Esta confusão, apontava, mais uma vez, para a demanda inicial da intervenção: a falta de prescrição adequada das tarefas. 

Os atendentes reorganizaram a lista, de modo que ela se aproximasse do que, de fato, eles performavam cotidianamente. Ao longo desse processo, questionamentos a respeito de algumas atividades foram levantados. Carla, por exemplo, perguntou como se fazia o serviço de recolocação do lacre de hidrômetro. Logo, um dos participantes mais antigos no setor, Roberto, lhe descreveu que isto acontecia quando era feita a leitura do hidrômetro e observa-se que o lacre estava violado, o que demandava a aplicação de uma multa no cliente.

Após isso, foi proposta uma atividade na qual eles teriam que sinalizar com marcadores vermelhos e dourados, respectivamente, quais as atividades eram mais complexas e quais eram as mais frequentes. Finalizada esta etapa, iniciou-se a discussão a respeito das atividades. Foi questionado por uma das facilitadoras o porquê de, por exemplo, a ligação de água ser uma dentre as mais complexas de serem realizadas. Roberto respondeu que era um serviço que envolvia as equipes de manutenção do SAAE e que, por isso, era mais difícil de ser concluído. 

Depois desse momento, a última atividade do encontro foi separar os serviços em categorias, cada um com sua especificidade. Obteve-se a seguinte classificação: no que tange ao objeto, relacionados à água e relacionados ao esgoto; no que considera a frequência, raros; e, no que diz respeito ao local, internos. Os relacionados à água eram: ligação de água, corte solicitado e religação. Os ligados à categoria esgoto: ligação de esgoto, desobstrução de esgoto, limpeza de fossa e fiscalização de esgoto. Os serviços raros, aqueles que não se faziam com frequência, se dividiam da seguinte forma: tarifa social, retirada de carro pipa, análise completa de água, deslocamento de ramal e recolocação de lacre e hidrômetro. Por fim, os serviços internos, que não precisavam da equipe externa do SAAE para serem realizados, eram: segunda via de conta, mudança de titularidade, declaração hidrossanitária, parcelamento de débito, verificação e extrato de débitos.

### Encontro 4 

Este encontro deu continuidade à categorização dos serviços. As facilitadoras apresentaram as categorias definidas anteriormente com uma projeção de slides. Entretanto, ainda houve mudanças, pois Flávia, que não estava no encontro anterior, levantou questionamentos, e a classificação passou por uma revisão. Depois desse momento, foi proposto que o grupo escolhesse uma atividade para que eles descrevessem seu passo a passo.
 
Coletivamente, a ligação de água foi escolhida como a atividade a ser descrita. Para dar início, a facilitadora explicou como seria essa descrição: os participantes teriam que elencar todos os procedimentos que faziam para lançar um serviço nos sistemas utilizados e listar a documentação demandada aos clientes. Depois dessa atividade, os participantes iriam se dividir e realizar o mesmo procedimento com os outros serviços. 

A discussão em conjunto culminou com uma das facilitadoras questionando o grupo sobre a utilização dos sistemas informatizados que os atendentes operavam: Poseidon, versão antiga; Poseidon, versão nova; e Ninfas. Neste diálogo, uma das participantes, nova na equipe, relatou ter tido dificuldades em utilizá-los. Os trabalhadores, então, tentaram descrever como cada um funcionava e afirmaram que os três sistemas, na maioria das vezes, eram complementares. Observou-se, ainda, que o uso dos sistemas também variava se o atendimento fosse presencial ou virtual.

No final do encontro, uma das facilitadoras questionou qual dos atendimentos era mais prático para os usuários: presencial ou online. Flávia respondeu que dependia do perfil do cliente, pois havia os que preferiam o online, pela praticidade, e os que gostavam de ir ao SAAE. Ela também afirmou que a demanda pelo atendimento online cresceu devido à pandemia da covid-19 e constatou que, antes dela, a fila de espera presencial era grande, o que exigia mais trabalho do setor. Depois da pandemia, percebeu que as idas dos clientes ao SAAE diminuíram. 

### Encontro 5

No quinto encontro, continuaram as descrições dos serviços realizados, mas, agora, isto era feito em duplas de trabalhadores. Ao final do encontro, cada dupla apresentaria sua descrição ao grupo, e uma nova discussão seria realizada. Para tanto, foram entregues roteiros nos quais os atendentes escolhiam um serviço para descrever: o nome, o respectivo código no sistema, os requisitos para pessoa física ou pessoa jurídica, os documentos necessários e os procedimentos.

Roberto propôs que as duplas fossem compostas por um trabalhador que atuasse no atendimento presencial e outro no virtual, pois considerava diferente a atuação em cada modalidade. O diálogo entre os pares teve duração de, em média, 15 minutos.

Ao longo do debate no coletivo de trabalho, um  tópico gerou uma controvérsia entre os participantes: a necessidade de arquivamento dos documentos solicitados aos usuários. Aline informou que, no atendimento virtual, os documentos eram arquivados no sistema e, Dário disse que, no atendimento presencial, havia a necessidade de arquivamento na empresa. Procedimentos diferentes eram adotados, uma vez que, no virtual, os documentos eram recebidos via WhatsApp e que, no presencial, os clientes precisavam apresentar os documentos originais e entregar as cópias. Flávia, por sua vez, relatou que tinha outro procedimento: caso o usuário fosse o titular da conta e esta estivesse atualizada, solicitava apenas o seu documento de identificação. O debate gerou uma controvérsia entre os participantes do grupo, uma vez que atuavam de maneira distintas em relação à solicitação e ao arquivamento dos documentos.

### Encontro 6

As descrições acerca dos serviços tiveram continuidade no sexto encontro. Carla e Leonardo comentaram sobre a fiscalização de esgoto, que tinha como finalidade verificar se havia rede coletora próxima à residência do usuário, bem como informar se a taxa do serviço estava sendo cobrada indevidamente. Questionados sobre a devolução do dinheiro em cobranças indevidas, Flávia respondeu que o ressarcimento precisava ser solicitado pelo usuário, já que a sugestão nunca partia do SAAE. Tal afirmação fez com que a atendente descrevesse o processo de reembolso, no qual o cliente produzia a punho um requerimento informando o período da cobrança, documento que era enviado para a diretoria, e, por fim, o desconto era lançado no sistema para ser efetuado na fatura seguinte. A facilitadora perguntou se eles foram orientados pelo SAAE sobre o uso dessa estratégia. Flávia, então, respondeu que não, pois pensava que induzir o usuário a produzir um requerimento era se opor à instituição em que trabalhava.

Próximo ao encerramento do encontro, Carla apresentou o serviço de fiscalização de água clandestina e destacou que, quando há comprovação de infração, o setor de cadastro e fiscalização fica responsável pela aplicação da multa, e o setor de atendimento pelo parcelamento e pedido de religação. A partir da discussão, a facilitadora perguntou se a quantidade de parcelas era determinada pelos atendentes, uma vez que expressavam empatia pelos usuários. Por exemplo, quando a participante compreendeu o caso de um cliente que não sabia que estava cometendo uma infração ao colocar uma torneira antes do medidor. Flávia explicou que isso fica a critério da gerência. Além disso, ressaltou que, com as mudanças na gestão, a equipe sempre precisa estar se adaptando às novas formas de proceder. Ademais, Leonardo concordou com a colega e afirmou que essas informações não eram repassadas para todos, precisando, consequentemente, os desinformados se adequar à medida que casos apareciam.

### Encontro 7 

Nesse encontro, iniciaram-se as apresentações das atividades. Dario iniciou a atividade descrevendo dois serviços: o cavalete e a falta de água. Nesta exposição, alguns problemas sobre a atividade de inserção do cavalete foram discutidos. Rita citou uma situação em que um usuário não queria pagar pelo serviço e denominou o momento como estressante.

Na sequência, a discussão girou em torno de prazos. Rita explicou que não costumava dar prazos exatos para os usuários. De acordo com ela, alguns serviços eram realizados pela equipe externa, dessa maneira os atendentes não tinham controle se a atividade seria realizada dentro da data prevista. Já Talia denominou que a atividade de troca de cavalete era uma das mais complicadas, pois, na maioria das vezes, os prazos não eram cumpridos, e isso causava o descontentamento do usuário. A atuação da participante, contudo, mostrou-se diferente da de Rita, visto que gostava de informar os prazos para os clientes.

No final do encontro, o mesmo debate ocasionou controvérsias entre o grupo. Marta relatou que, em algumas situações, os atendentes informavam datas diferentes para os usuários. Ela citou a situação em que Carla deu um prazo de 15 dias. Dias depois, o cliente retornou com o mesmo problema, e Marina informou outro prazo. De acordo com o relato delas, o cliente se mostrou insatisfeito com a situação.

### Encontro 8

No início do oitavo encontro, foram apresentados os serviços internos e a descrição do último serviço pendente: serviços eventuais. Essa atividade os atendentes escolheram fazer individualmente, mas Rita e Dario optaram por realizá-la em dupla. 

No decorrer da exposição dos serviços internos, discutiu-se como foram realizados os atendimentos durante a pandemia. Marta citou que foi algo inesperado, devido a nunca ter atendido aos usuários de forma virtual. Flávia relatou também que, no começo, foi bastante desafiador, pois houve muitas reclamações, principalmente pela demora no atendimento virtual, mas que, de forma geral, o SAAE conseguiu superar as limitações do contexto, oferecendo um serviço de qualidade.

Nessa perspectiva, Dario citou que as pessoas ainda tinham medo da covid-19, por isso preferiam o atendimento online. Continuamente, uma das facilitadoras o questionou sobre como ele reagiu ao modelo virtual. O participante relatou que precisou se adaptar para acompanhar as evoluções no seu trabalho, mas que preferia o presencial. Ele chegou a denominar as ferramentas tecnológicas, celular e computador, como “frias”, já que não tinha a mesma interação com os usuários como no guichê. 

No final da atividade, Flávia citou que, durante a semana, um usuário se irritou e foi presencialmente reclamar sobre a demora no atendimento via WhatsApp. Ela explicou que por conter uma grande demanda e realizar o atendimento por ordem de recebimento das mensagens, é normal a demora. Além disso, relatou ainda que fez amizade com esse usuário, o que facilitou a resolução do problema, na medida em que conseguiu lidar com a irritação.

### Encontro 9

No início do nono encontro, o grupo discutiu acerca da validação do manual, o qual foi intitulado de Procedimento Operacional Padrão. A facilitadora apresentou o andamento da primeira versão e retomou questões que haviam surgido nos encontros anteriores, como a exigência de cópias de documentos e o estabelecimento de prazos. Na sequência, a facilitadora questionou sobre o prazo estabelecido para a ligação de água, já que os participantes não entraram em consenso nos últimos encontros. Marina respondeu que costumava dizer entre 45 a 60 dias, como uma estratégia de não deixar o cliente chateado em ter que retornar ao SAAE quando o prazo era descumprido. Os participantes deram continuidade à discussão e ressaltaram outras habilidades acerca dos prazos. Por exemplo, Flavia e Marta explicavam ao usuário que a demanda de serviço era alta e que isso exigia mais tempo de espera. Carla esclarecia que a ligação de água não dependia somente do setor de atendimento, mas também da equipe de campo. Já Marina pontuou que a instituição atendia a cidade e os distritos, por isso o atraso na conclusão do serviço.

A discussão culminou com questionamentos sobre como interagir com os usuários ao determinar o tempo de espera. A facilitadora perguntou o que motivava a equipe a elaborar essas estratégias. Flávia respondeu que eram criadas como mecanismo de defesa, pois, na maioria das vezes, o usuário esperava um retorno imediato do atendimento, então eles precisam ser criativos para solucionar os problemas. Marta concordou com a colega e afirmou se sentir envergonhada quando o usuário retornava pela terceira vez ao SAAE.  

Já no final da atividade, os participantes relataram que a cobrança do usuário repercute também na sua vida pessoal. Por exemplo, Flavia relatou que foi abordada por um cliente na igreja e questionada se poderia ceder seu número particular para resolver questões do trabalho. Carla relembrou o dia em que estava doente na Unidade de Pronto Atendimento e precisou explicar à usuária que não seria possível tirar suas dúvidas. Por fim, Rita e Marta disseram que foram perseguidas na rua por uma usuária com dúvidas, após terem sido observadas pelas câmeras de segurança. De modo geral, ao longo da discussão o grupo apontou que os desafios enfrentados no setor de atendimento estavam associados à falta de organização do setor administrativo, visto que as equipes de campo não cumpriam os prazos estabelecidos pela instituição. Ademais, Carla ressaltou que observar o estilo de trabalho dos colegas era uma forma de evitar constrangimentos futuros no atendimento presencial.

### Encontro 10

No último encontro, houve a continuação da validação do manual. A atividade começou com a apresentação do serviço de corte solicitado e a análise dos procedimentos adotados nos demais serviços. No decorrer da validação, houve uma discussão acerca da definição do serviço de religação de água, uma vez que a maioria dos participantes falou diferentes definições. Rita propôs não colocar uma definição no documento, já que cada um o entendia de forma distinta. Na ocasião, uma das facilitadoras informou que iria falar com a gerência sobre esse caso específico e depois daria um retorno a eles.

Nos momentos finais da atividade, o coletivo decidiu mudar alguns procedimentos. Uma das facilitadoras comentou sobre a complexidade dos serviços, visto que tinham muitos detalhes. Rita concordou, afirmando que muitos procedimentos iam mudando no decorrer do tempo. Além disso, a participante pontuou que, quando realizava as atividades, tudo parecia um processo simples, contudo descrevê-las estava demandando bastante esforço. Tal afirmação também foi corroborada pelos demais atendentes. Por fim, foram informados a respeito da finalização dos encontros, bem como sobre a apresentação do manual para a gerência da instituição.

## Discussão
Alguns temas se destacaram ao longo dos encontros, como a falta de prescrições e as agressões dos usuários, em especial contra as atendentes. Também foi tematizado o trabalho durante a pandemia da covid-19.

Notou-se que as prescrições precárias, mutáveis, a depender das chefias, e, por vezes, restritas a um regulamento institucional criado há mais de trinta anos levavam a uma ausência de padronização dos procedimentos. Os trabalhadores, desse modo, tinham de se valer, quase que exclusivamente, das orientações que eram compartilhadas entre si. Dessa forma, a dimensão interpessoal do ofício acabava sendo um substituto da dimensão impessoal. Os trabalhadores se valiam de regras informais, mas não havia, ainda, um gênero profissional fortemente estabelecido.

Isso implicava em prover informações imprecisas – por vezes, contraditórias – para os usuários do serviço, como possibilidade de parcelamentos de contas em atraso, prazos para a realização de serviços, dentre outros. Leal et al. [-@leal_almeida_bauer2015vivencias_prazer_sofrimento] encontraram situação similar ao constatar que a ausência de treinamentos nos serviços de atendimento ao público causava nos trabalhadores um sentimento de incapacidade em relação às formas de proceder. 

No que diz respeito às agressões dos usuários, os trabalhadores do SAAE, notadamente as mulheres, se mostravam extremamente cordiais para evitar conflitos mais graves. Em situações como essas, pediam desculpas ou direcionavam o atendimento para a profissional que era considerada a mais “calma” do setor. Tais comportamentos se aproximam dos achados de Sznelwar e Abrahão [-@sznelwar_abrahao_2012]. Os autores apontaram que, quando constrangidos ou impedidos de agir, os profissionais assumiam uma postura mais automatizada em relação aos clientes, de modo a evitar que a agressividade destes incorresse em situações mais danosas.

Posto isso, a dimensão transpessoal do ofício se manifestava através de estratégias que faziam parte da memória do coletivo e que contribuíam para o enfrentamento das adversidades. No entanto, mesmo utilizando esse conjunto de saberes construído por elas ao longo dos anos, consideravam que outras habilidades precisavam ser empregadas para amenizar os constrangimentos no trabalho. Nesse sentido, passaram a descrever ações singulares que ajudavam a desenvolver as atividades cotidianas, por exemplo, falar da grande demanda de serviços a serem atendidos e da dependência do setor em relação às equipes de campo.

Mediante estes relatos, que descreviam as ações empreendidas durante os contextos de violência, a intervenção também deu visibilidade à dimensão pessoal do ofício. Na medida em que os modos de agir do grupo tornavam-se insuficientes para lidar com as situações, o estilo profissional aparecia para transformar e revitalizar o gênero [@clot2010trab_poder].

Há que se considerar, ainda, que a desorganização do setor administrativo também repercutia na vida pessoal das profissionais, visto que o seu tempo de lazer era invadido por demandas oriundas do trabalho. Para Leal et al. [-@leal_almeida_bauer2015vivencias_prazer_sofrimento] os comportamentos dos clientes deveriam ser atribuídos às instituições, dado que a irritação deles, na maioria das vezes, tinha relação com o longo tempo de espera.

Soma-se ao que foi exposto um recorte sobre o gênero feminino nos setores de atendimento. Venco [-@Venco2009] considerou que a acentuada contratação de mulheres estava associada a características que socialmente eram atribuídas a elas, por exemplo, paciência, delicadeza e empatia, ou seja, rebaixava-se o seu agir a atributos tidos como femininos. Além disso, Nogueira [-@Nogueira2009] apontou que era imposto às trabalhadoras um controle exacerbado sobre o tempo, a quantidade de tarefas executadas e os resultados obtidos. Ressaltou, ainda, que a busca pela satisfação dos clientes proporcionava maiores riscos à saúde, já que precisavam ter um esforço emocional extra para superar as dificuldades cotidianas sem abandonar as regras da instituição.

Ao discutirem sobre o trabalho durante a pandemia da covid-19, o atendimento virtual foi citado como complexo pelos atendentes. A abrupta adaptação à nova modalidade era tida como um fator que dificultava o desenvolvimento das atividades, já que muitos participantes não tiveram experiências anteriores com o teletrabalho ou não estavam acostumados com as ferramentas digitais. Geralmente, essas adversidades implicavam no desgaste e na sobrecarga do trabalho.

A situação exposta se aproxima do resultado encontrado por Filardi et al. [-@filardi_castro_zanini2020vantages_desv_teletrab]. Os autores apontaram que a ausência de treinamentos tornou o processo de apropriação do trabalho por meio da internet mais desagradável para os trabalhadores. De outra forma, Brandão e Ramos [-@brandao_ramos_2023] verificaram que, quando foram ofertadas capacitações, se proporcionou a eles uma concepção positiva sobre a sua atuação, principalmente na sensação de independência e satisfação com a atividade.

Por se tratar de um novo arranjo laboral, também houve queixas relacionadas à mudança na interação com os usuários. Desse modo, demonstravam que o contato remoto não garantia a compreensão dos clientes, já que não se conseguia atendê-los de maneira mais afetuosa, como no presencial. No entanto, havia atendentes que aprovavam o atual atendimento, ao considerarem que o retorno presencial do cliente ao serviço causava desgaste emocional.

Ainda em consonância com os relatos dos participantes, o estudo de Santos et al. [-@dos_santos_saraiva_da_silva_marolla_2022] apontou que o atendimento virtual impediu o estabelecimento de relações mais empáticas entre atendentes e usuários. Os autores mostraram, ainda, que o teletrabalho repercutiu negativamente na resolução das demandas, uma vez que os profissionais não conseguiam compreender as queixas dos clientes e, consequentemente, demoravam a fornecer as devolutivas. Para Baccilli e Cruz [-@baccili2021virtualizaccao], outro aspecto negativo estava relacionado à sobrecarga de trabalho, decorrente do aumento no número de demandas que passaram a chegar via WhatsApp e E-mail. Todavia, os operadores sentiam-se mais seguros, pois as plataformas digitais conseguiam registrar os diálogos empreendidos e, assim, havia a possibilidade de recuperar as interações com os clientes caso necessário.

De modo geral, ao se avaliar a proposta metodológica da intervenção, viu-se que as técnicas empregadas ampliaram o diálogo no grupo. Têm-se como exemplo que as diversas mudanças que ocorriam no setor, como existirem nos sistemas serviços que não eram mais prestados, foram notadas a partir das interações que a intervenção permitiu ao coletivo de trabalho. 

Ademais, os diálogos permitiram um retorno à atividade que transcendia a sua realização imediata, na medida em que os atendentes se deram conta das decisões que tomavam na realização das atividades, mas que não eram reconhecidas imediatamente. Isso foi destacado quando uma das participantes relatou o esforço necessário para descrevê-las e avaliar o que se fazia para além da execução imediata. 

No que diz respeito às interações com os clientes, observou-se que os atendentes, a partir das discussões que ocorreram durante a intervenção, foram confrontados com as próprias atividades, na medida em que puderam narrar não só aquilo que desempenhavam, como também aquilo o que não conseguiam fazer. Desta forma, pôde-se acessar o real da atividade, que não se reduz à atividade realizada,  mas compreende o processo que leva o trabalhador a tomar as decisões sobre como se deve proceder. Nesse sentido, o real da atividade se refere “...ao que não se faz, ao que não se pode fazer, ao que se deveria fazer, ao que se gostaria de fazer e àquilo que se faz sem se ter necessidade.” [@clot2007func_psic, p. 216].

Ademais, a construção do manual possibilitou um espaço de controvérsias entre os trabalhadores, sobretudo nos diálogos relativos à adoção de diferentes procedimentos para a realização das tarefas. Notou-se que durante as disputas, o gênero profissional se fortalecia, na medida em que era possível debater sobre o ofício de atendente, o que divergia da postura do coletivo antes da intervenção. Dessa maneira, a controvérsia implicou a ampliação do diálogo, garantindo que outras experiências fossem desenvolvidas e transformadas [@clot2017clinica_atividade].

## Considerações finais

O trabalho objetivou relatar uma assessoria realizada no setor de atendimento ao público do Serviço Autônomo de Água e Esgoto (SAAE), no qual se utilizou a construção do manual de procedimentos como um mediador de diálogo entre os trabalhadores. Para mais, visou um espaço onde eles pudessem refletir sobre o ofício de atendente, os diferentes modos de agir, bem como as condições de trabalho e suas repercussões à saúde. Foi utilizada a Clínica da Atividade como aporte teórico e metodológico no intuito de observar a renovação do gênero profissional e a transformação do trabalho de maneira coletiva. 

Dentre os resultados encontrados, alguns ocuparam centralidade no debate empreendido pelos participantes. Notou-se a ausência de prescrições, o que implicava o repasse de informações imprecisas aos clientes. Soma-se a isso adversidades relacionadas à violência vivenciada pelas participantes mulheres e as estratégias desenvolvidas para lidar com essas situações. Além destes, emergiram no discurso dos atendentes o incômodo sobre a adoção do atendimento virtual durante a pandemia da covid-19 e as suas repercussões na interação com o usuário.

Nessa investigação, notaram-se forças e potencialidades. O engajamento do grupo foi prevalente em todos os encontros, e os trabalhadores se colocaram à frente das discussões, ocupando o lugar de experts sobre o ofício. Além disso, houve o reconhecimento do grupo em relação às trocas de experiências e estratégias. Nesse bojo, os trabalhadores aprendiam uns com os outros, independente do tempo de trabalho na instituição. Essa dinâmica aponta para uma ampliação no poder de agir dos participantes. Observou-se, também, que a intervenção proporcionou uma maior interação entre os profissionais das modalidades de atendimento presencial e online, uma vez que, cotidianamente, estes não possuíam um contato direto para que pudessem compartilhar e discutir os diferentes modos de agir.

No que diz respeito às limitações do estudo, destaca-se o tempo reduzido que os trabalhadores tinham para discutir suas atividades, visto que houve mudanças no cronograma que foi inicialmente idealizado, por conta de feriados e outros contratempos em relação ao campo. Soma-se a isso, ainda, o cansaço dos atendentes, já que as atividades ocorriam às sextas-feiras, no final do expediente da semana. Ademais, o espaço oferecido pela instituição para a realização do grupo se mostrou inadequado, devido a ser em um ambiente de livre acesso para outras categorias de trabalhadores. Isso comprometeu, em parte, a liberdade de expressão dos participantes. Ainda no que tange aos imprevistos da intervenção, houve uma grande rotatividade dos participantes, dado que aqueles que estavam de férias retornavam à instituição e, consequentemente, entravam nas discussões já iniciadas. 

Por fim, vale ressaltar que estudos futuros podem ser realizados no setor de atendimento do SAAE, por exemplo, analisando o poder de agir e a saúde dos trabalhadores após a validação do Manual de Procedimentos e o modo como o documento tem repercutido nas suas interações socioprofissionais. Além disso, cabem também pesquisas e intervenções relacionadas às violências contra as atendentes mulheres, considerando que apontam para uma questão de gênero que merece ser discutida de forma mais aprofundada.

