---
author: 
  - name: Érica Atem Gonçalves de Araújo Costa
    orcid: 0000-0002-4341-8138
    email: ericaatem@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará    
  - name: Eliandra Estevam Abreu
    orcid: 0009-0003-6822-9848
    email: eliandraestevam.ufc@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Vitor Batista de Melo
    orcid: 0009-0003-3866-2341
    email: vitorbdmelo@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Laryssa Ferreira Rabelo
    orcid: 0009-0001-5241-3611
    email: rabelolaryssa05@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Milena Araújo Bezerra
    orcid: 0000-0002-2589-7876
    email: milenaaraujo@alu.ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Ingrid Rabelo Freitas
    orcid: 0000-0002-8365-6245
    email: ingrid.rbfreitas@gmail.com
    affiliations: 
      - name: Centro de Defesa da Vida Herbert de Souza
  - name: Rogério da Costa Araújo
    orcid: 0000-0003-3508-362X
    email: rio.costa50@gnail.com
    affiliations: 
      - name: Centro de Defesa da Vida Herbert de Souza
  - name: João Paulo Pereira Barros
    orcid: 0000-0001-7680-576X
    email: joaopaulobarros@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
language: 
  title-block-author-plural: "Autores"
filters:
  - section-bibliographies
bibliography: costa_interv_criancas.bib
reference-section-title: Referências
---

# Intervenções psicossociais com crianças e adolescentes e territorialidades periféricas urbanas

## Apresentação

Este capítulo descreve e analisa intervenções psicossociais com crianças e adolescentes em uma periferia urbana de Fortaleza, Ceará. É escrito a muitas mãos – de estudantes, professoras/es e articuladoras/es sociais –, coadunando-se com o compromisso de escutar uma pluralidade de vozes que nos aproximam eticamente da complexidade social dos modos de existência nos mais diversos territórios. As práticas em foco realizaram-se entre os anos de 2019 e 2020 e relacionam-se ao projeto Maquinarias: Infâncias em Invenção, parte da extensão universitária em Psicologia Social, vinculada ao grupo de pesquisa e estudo em Violência, Exclusão Social e Subjetivação (VIESES) e ao Departamento de Psicologia da Universidade Federal do Ceará (UFC).

Desde 2019, a partir da articulação com a ONG Centro de Defesa da Vida Herbert de Souza (CDVHS), o Projeto de Extensão Maquinarias: Infâncias em Invenção é acolhido pelo Centro de Cidadania e Valorização Humana (CCVH) na ocupação de Nova Canudos, no bairro Canindezinho. Diante da demanda pela realização de ações, projetos e atividades com as crianças nessa área, construímos metodologias participativas como experiências que lhes fortalecessem como sujeitos políticos na comunidade. Além disso, as ações emergem também pela possibilidade de realizar atividades de formação e de pesquisas com crianças em contexto periférico. Durante o primeiro ano, consolidou-se um grupo intitulado “Invenções das Crianças de Nova Canudos”, o qual era composto, em média, por vinte e duas (22) crianças, em sua maioria negras, pobres e estudantes de escola pública com idade entre 6 e 12 anos, além de pesquisadoras/es, estudantes, articuladoras/es e militantes dos movimentos sociais, moradoras/es da ocupação.

Em 2020, a demanda, explicitada no início da parceria, manteve-se e ampliou-se pela necessidade das crianças de:

a.  manter o vínculo, o que ganhou especificidade em contexto pandêmico;
b.  contribuir efetivamente na melhoria estrutural do CCVH, espaço que vem sendo reconhecido e conquistado por elas para realizar atividades do seu interesse; e
c.  organizar o grupo e os seus modos de participação e atuação, protagonizando movimentos que lutam pela melhoria de vida em Nova Canudos.

Todas essas demandas foram atravessadas pela análise coletiva do que era possível realizar de modo virtual, dado o agravamento das desigualdades sociais, diretamente relacionadas às condições de acesso das crianças às redes sociais. Ao mesmo tempo, outros desejos foram se agenciando e sendo resistência ao apagamento gerado pela naturalização da precarização da vida em contexto periférico. Isso criou fluxos para experimentações, em âmbito de produção audiovisual, das crianças no YouTube, TikTok, Whatsapp .

Iniciamos o texto relacionando territorialidades periféricas e modos de subjetivação, bem como reposicionando problemas e modos de fazer. Em seguida, abordamos as condições de inserção no campo por uma perspectiva cartográfica e processual, assim como a criação conjunta do território existencial em que se forjam as ações de caráter inter(in)ventivo e participativo com crianças e adolescentes da ocupação de Nova Canudos. Ações essas são articuladas ao CCVH, que não só acolhe, mas também é inventado na agência política de crianças e adolescentes. Por fim, destacamos modos de fazer (dispositivo grupal) que desenham o campo de forças deste território existencial, enfatizando desafios de conduzir demandas de forma coletiva.

## Territorialidades periféricas e modos de subjetivação: atuar começa por saber inventar problemas outros

De que lugar falamos? Com quem enunciamos estas intervenções aqui destacadas? Que saberes são construídos com Nova Canudos? Estas questões nos guiam na escrita deste tópico, começando por destacar narrativas de moradoras/es e articuladoras/es acerca dessa comunidade, assim como indicadores socioeconômicos, presentes em documentos sobre o bairro que vão ganhando vida nas trocas com as crianças e adolescentes.

Nova Canudos nasceu em 1993 como uma ocupação popular influenciada pelas Comunidades Eclesiais de Base (CEBs), movimento da igreja católica orientado pela Teologia da Libertação que tentava ligar fé e vida nas ações pastorais. Isso porque uma das questões fortes na vida de muitas famílias na década de 1990, em Fortaleza, era justamente o acesso à terra na cidade para garantir o direito à moradia. Assim, com apoio da igreja local, houve a ocupação do terreno e a organização informal dos lotes de terra. Nestes, foi reservada uma área para construir um equipamento local para realizar as celebrações religiosas e a discussão dos problemas da comunidade. Essa área deu origem ao Centro de Cidadania e Valorização Humana – CCVH, mantido até hoje como referência para as atividades coletivas realizadas em Nova Canudos. Numa outra área, foi construído um outro centro comunitário com apoio de um projeto chamado Mãos Unidas, em que médicos voluntários faziam atendimento para a população. Esse equipamento foi incorporado à rede de atenção básica em saúde e hoje é sede da Unidade Básica de Saúde Abner Cavalcante Brasil, único posto de saúde público da Zona Especial de interesse social (ZEIS) do Bom Jardim, que atende Nova Canudos e outros moradores de comunidades vizinhas.

Nova Canudos situa-se no bairro Canindezinho, o qual, até 2020, era um dos bairros da região do Grande Bom Jardim (GBJ). A partir da lei municipal nº 278 de 2019, que estabelece uma nova regionalização na cidade de Fortaleza, e do decreto nº 14.590 de 2020, o bairro Canindezinho passou a compor a Secretaria Executiva Regional – SER X, tendo ficado separado do que oficialmente passou a ser considerado o GBJ – SER V. [@fortalezaEntendaNova]. A área tem elevados indicadores de violência urbana e concentração de pobreza e extrema pobreza, com uma população de 211 mil habitantes, de acordo com o Censo – IBGE (2010). Diante do descaso do Estado, a articulação política popular tornou-se forte, o que explica o engajamento dos habitantes, desde crianças a – sobretudo – jovens e adultos, em associações de moradoras/es, organizações não-governamentais (ONGs), coletivos e outros instrumentos que permitem sua participação no processo de organização, mobilização e fiscalização de políticas públicas destinadas à periferia. Dentre essas articulações presentes no GBJ, destacamos a atuação do Centro de Defesa da Vida Herbert Souza (CDVHS).

Diante do compromisso ético-político com o enfrentamento dos processos de vulnerabilização da vida das crianças, aliado ao reconhecimento das práticas de participação e organização comunitária historicamente levadas adiante no GBJ, Nova Canudos se efetivou como território periférico potente, com abertura a problematizar conjuntamente as relações entre crianças e modos de participação, numa perspectiva contextualizada e integrada aos movimentos das crianças na comunidade, destacando o fato de serem público de interesse das atividades realizadas e sediadas pelo CCVH.

Diante disso, uma Psicologia Social Decolonial [@barros2017politica; @barros2019violencias; @mayorga2014contribuicoes], como rede de saberes, subsidia as ações do Maquinarias: Infâncias em Invenção e se acontecimentaliza entre universidade e periferias. Os acontecimentos guardam a potência dos instituintes que podem desnaturalizar e produzir brechas nas percepções enrigecidas no tecido social e que se materializam numa trama racista, sexista, classista, heteronormativa, adultocêntrica. Portanto, neste trabalho, periferias e universidades não são lugares dados, prontos e acabados, mas Constituem-se mutuamente por estratégias conjugadas e esforçam-se para desnaturalizar relações históricas de distanciamento e de colonização.

Essa parceria, sobre a qual ora nos detemos, pode reposicionar estigmas sociais em torno das periferias urbanas de Fortaleza, na consonância de que estes territórios são plurais e centros de produção de vida, disputando constantemente com narrativas hegemônicas de desqualificação e criminalização. Nessa perspectiva, tem sido possível a articulação entre crianças de diferentes realidades periféricas pela integração nas atividades de outros projetos parceiros, pela criação de registros (fotografias e vídeos) da ação coletiva das crianças e pela participação em editais públicos para manutenção das atividades, com maior visibilidade de seus modos de vida, fora de visões estereotipadas que menorizam sua participação na cidade. Assim, produzem-se pistas que ajudam a desnaturalizar concepções de infância constituídas historicamente em um passado colonial, estabelecendo a elas a condição de desenvolvimento a qual deve passar pelos processos de escolarização e proteção familiar para o pleno exercício da cidadania [@castro2013infancia; @sarmento2013sociologia; @junior2020nocao].

Reposicionar-se ético-estética e politicamente opera a invenção de outros problemas com os quais movimentar o pensamento. Estar COM complexifica modos de atuar, exigindo negociações, diálogos, trocas em que relações de poder-saber possam ter postas em análise seus efeitos, a fim de não corroborar o silenciamento histórico das classes subalternizadas, o que, interseccionalmente, produz opressões de gênero, geração, classe e etnia/raça. Nestes dois anos de atuação, compomos algumas pistas para produção de problemas situados e implicados com os quais temos (des)aprendido: a) exigência de articulação com agentes do território, fortalecendo lutas e caminhos construídos coletivamente; b) necessidade de acompanhamento em rede das crianças e dos adolescentes, atentando aos vínculos, que devem ser constantemente renovados, de confiança necessários com eles e seus responsáveis ; c) abertura à experiência e criatividade metodológica para desempenhar atividades não dirigidas que respondam ao agenciamento coletivo das crianças e à singularização dos seus processos e das suas demandas.

## Condições de inserção no campo por uma perspectiva cartográfica

O Maquinarias chegou, em 2019, ao território do Grande Bom Jardim (GBJ) por intermédio dos vínculos de parceria entre os atores sociais e o VIESES. Esses atores, membros do CDVHS, foram os responsáveis pela construção e, em parte, pela manutenção da ponte que se estende entre o Maquinarias e o CCVH há 2 anos. Neste espaço comunitário em Nova Canudos, já ocorriam atividades pontuais promovidas por e para moradoras/es, como aulas de capoeira e de teatro, oficinas artesanais de construção de pulseiras e, não raramente, celebrações religiosas, que mobilizavam diferentes grupos geracionais. Apesar da desassistência do Estado, o espaço mantinha-se ativo e reverberava os efeitos das ações coletivas de moradoras/es, integrando-se à rede comunitária em Nova Canudos como ponto de apoio para atividades culturais, formativas e assistenciais à população.

Essa sua organização sinalizou a abertura do CCVH para a proposição e construção coletiva de atividades com crianças e adolescentes, sendo possível que expectativas, metodologia e objetivos emergissem como efeito dos encontros. Tal perspectiva se materializou e ressoou com a proposta de ação inter(in)ventiva e participativa a que o projeto de extensão aspirava delinear e colocar em prática [@dacosta2020reexistencias].

Na primeira visita ao CCVH, com a mediação de articuladores do CDVHS, o Maquinarias encontrou, além de um morador e membro do conselho diretor da Associação, dez crianças que, curiosas com a movimentação, se aproximaram e abriram caminho, sem deixar de “avaliar” as visitantes. Neste movimento de se conhecer e se inventar, crianças, articuladoras/es, extensionistas e pesquisadoras/es se puseram a juntar, seguindo um fluxo imprevisto, peça por peça, as engrenagens de um novo coletivo no território. O nome forjado para esse grupo pelas próprias crianças, ainda no primeiro encontro, “Invenções das Crianças de Nova Canudos”, tornou-se bastante indicativo de como intervenção, participação e agência (micro)política se entrelaçaram para consolidar modos de criar, cartografar e acompanhar processualmente um território existencial [@barros2009cartografar]. Em suas proposições, as crianças tensionam modelos de atuação adultos, centrados no PARA, os deslocam a um fazer COM, articulando e criando espaços para a concretização de suas demandas, além de habitar o centro comunitário enquanto o (re)inventavam.

A própria inserção do Maquinarias nesse território existencial se mostrou um movimento contínuo, de renovadas tentativas e conquistas da confiança e aceitação do grupo Invenções, que não permanecia estático fosse pela chegada de novas crianças, fosse pelo seu crescimento e/ou pelas mudanças de posturas. Do mesmo modo, o projeto de extensão se renovava pelos novos ciclos e compromissos entre campos de atuação e universidade. Essas mudanças impactaram a composição das forças e dos laços afetivos que constituem mutuamente o Maquinarias e o coletivo de Nova Canudos, entendidos como dispositivos grupais, inter(in)ventivos e, portanto, efeitos das insurgências cotidianas, tramadas nos encontros com as crianças e os adolescentes. Desse modo, tomando a cartografia como método de pesquisa e intervenção, aliam-se às atividades de extensão universitária o processo analítico de uma realidade complexa que se dá no campo, a partir da implicação de extensionistas e articuladores/as sociais nas ações inventadas coletivamente que produzem problema, tornando inseparável a produção de saberes e a prática. [@dacosta2020reexistencias; @passos2009cartografia].

O fato de considerarmos a processualidade que acompanha estes vínculos – universidade e periferia, Invenções e Maquinarias, crianças e extensionistas, e tantos outros – produz visibilidade para fatores importantes, como:

a.  as distâncias geográficas que principalmente as/os adultos percorriam para chegar aos encontros e a forma como essas distâncias – os lugares aos quais cada um pertence – influem na maneira que cada uma/um se conecta, ressaltando condições diferentes de vulnerabilidades e privilégios sociais;
b.  o contexto da pandemia da COVID-19, que tem perdurado desde o início do segundo ano de existência do coletivo, com todos os seus entraves, como a inviabilidade de reuniões presenciais, o acesso não democrático à internet e o agravamento das condições de vulnerabilidade social que perpassam o grupo; e
c.  o contexto de violência urbana que cerceia a ocupação de Nova Canudos. Este mapa movente requer, portanto, a inserção em campo como atitude e não apenas como um pacto fixo, com posições delimitadas e definidas anteriormente ao próprio processo de vinculação.

O território habitado, portanto, nunca esteve dado, bem como não foi fincada uma bandeira no canto do pátio do CCVH, ou em qualquer outro lugar que o Invenções ocupou, que reivindica a permanência do Maquinarias naquele local. É, todavia, a confluência dos desejos e das demandas que circulam o coletivo que enlaça seus membros e estabelece um fluxo contínuo de atividades, quer estas sejam virtuais quer sejam presenciais.

## "Invenções das crianças de Nova Canudos": ações de um coletivo intergeracional

Uma questão nos parece fundamental retomar neste momento do texto: o fato de que as intervenções psicossociais aqui em foco se realizaram no revezamento entre diferentes processos criativos, sendo fruto de agenciamentos coletivos, os quais fomos cartografando em seus efeitos de subjetivação, sem neutralidades e/ou relações hierárquicas. Elas possuem marcas que consideramos potentes para atuações que se coloquem micropoliticamente diante de processos coletivos e comunitários, que toquem diretamente os desafios da participação política em grupos intergeracionais. Vejamos:

a.  Abertura à improvisação;
b.  Disponibilidade para criação e experimentação sem roteiros fechados;
c.  Interesse na utilização e pesquisa de materiais que favoreçam modos diversos de participação, não necessariamente vinculados ao discurso oral;
d.  Interesse pelo trabalho com grupos e disposição em fazer conjuntamente, a fim de se distanciar de uma postura especialista (expert).

Desse modo, o “COM crianças e adolescentes” torna-se disparador para o planejamento conjunto do conteúdo, dos materiais, dos lugares, dos registros dos processos, das formas de divulgação e dos efeitos para o grupo e para a comunidade.

Entendemos a abertura não só à diferenciação, mas também aos devires do grupo e, consequentemente, à processualidade e à heterogeneidade das atuações em campo como um modo de intervir na complexidade dos agenciamentos grupais [@barros2007grupo]. Extensionistas e pesquisadoras/es movimentam a si e ao campo, diante da proposta de produzir COM as crianças e aprender com os encontros, encarando, também, o desafio de conduzir demandas de forma coletiva. Apostamos que essa postura (ética) é próxima àquela definida pela cartografia dos processos de subjetivação, ou seja: produz-se um território existencial pelo engajamento nas experiências cotidianas e inventadas coletivamente [@alvarez2009cartografar].

A composição do grupo é diversa quanto aos marcadores de idade, classe, raça e gênero, podendo as crianças transitarem entre os encontros, sendo o número de participantes variável, em torno de 15 a 20. Essa forma de estar junto tensiona concepções de coletivos e sujeitos que sejam homogêneas e fixadas por um ideal identitário, compreendendo uma multiplicidade dos modos de compor coletivamente que podem vir a acontecer em cada campo de forças [@barros2007grupo].

### Ações em 2019: invenção de um dispositivo grupal

As ações no primeiro ano, em um total de 16 encontros, instauraram o estar e o fazer juntos como dispositivo, sendo o Invenções uma estratégia de se fazer ver não só na comunidade pelos outros grupos geracionais (componentes das famílias, dos grupo da igreja e articuladoras/es dos movimentos sociais) e pelos próprios pares, como também em outros territórios. Além disso, agir coletivamente e ser escutadas/os mobilizou o desejo das crianças para dois tipos, ambos lúdicos e livres, de atividade: situadas, realizadas quinzenalmente na sede do CCVH, e deslocadas, realizadas em passeios pela cidade. Veremos que em 2020, em decorrência de outras relações espaço-temporais pela pandemia da COVID-19, as ações foram descritas de modo que essas condições fossem visibilizadas.

Os encontros realizados no CCVH incluíram oficinas de desenho; produção de brinquedos com materiais recicláveis; exibição de filmes; mapeamento coletivo dos lugares onde as crianças circulam na cidade; celebrações de início e término de semestre.

A presença periódica das crianças no CCVH mobilizou o conselho diretor da associação no sentido de garantir um espaço para que o grupo Invenções guardasse produções, materiais utilizados, brinquedos, entre outras necessidades. Essa conquista resultou da negociação para o uso comum do espaço com outros grupos, fomentando a participação e a visibilidade das crianças na comunidade. Além disso, as ações COM as crianças passaram a ser contínuas no território, e não apenas pontuais.

Os passeios pelo território e pelos outros locais de Fortaleza possibilitaram o encontro das crianças com a dimensão pública da cidade que a elas é vetada, muitas vezes, pelos muros da exclusão social e das desigualdades socioespaciais urbanas. Transitar por Fortaleza, para além de Nova Canudos, coadunou-se com o desejo das crianças e aconteceu pelo convite que o Invenções recebeu para participar de dois eventos: o “II Colorindo O Gênero”, programação que integra o “Curta o Gênero”, promovido anualmente pela ONG Fábrica de Imagens: ações educativas em cidadania e gênero, e que teve a edição de 2019 realizada no Centro Dragão do Mar de Arte e Cultura; e o “Festival Internacional de Teatro Infantil do Ceará” (TIC), com apresentações teatrais realizadas no Centro Cultural do Grande Bom Jardim (CCBJ), ambos equipamento da Secretaria da Cultura do Estado do Ceará (SECULT-CE). A falta de informação sobre como ter acesso a equipamentos públicos (teatro, cinema, parques, museus), além das circunstâncias dificultadoras pessoais de cada uma/um, muitas vezes as/os distancia da possibilidade de utilizá-los. Assim, os trânsitos experimentados pelas crianças problematizam os sentimentos de pertencimento à cidade e as possibilidades que ela oferece.

Poder circular com as crianças pela cidade, além de um desejo delas, mostrou-se atividade de enorme impacto e analisador importante das fronteiras existentes na cidade, que invisibilizam as pessoas moradoras de territórios periféricos. São fronteiras naturalizadas cotidianamente, que precisam ser transformadas. Nesse sentido, os passeios descritos foram oportunidades potentes para mover simbólica e concretamente nosso modo de estar nos territórios, entendido como vetor produtor de subjetividades.

### Ações em 2020: recomposição dos movimentos em meio à pandemia

A pandemia da Covid-19 atravessou as composições da extensão universitária e do grupo Invenções das Crianças de Nova Canudos, repercutindo nas temporalidades e nos modos de acompanhar e narrar as ações coletivas. Neste contexto, a participação na chamada pública lançada pelo Centro Cultural do Grande Bom Jardim (CCBJ) com recursos provenientes do Fundo de Combate à Pobreza (FECOP) possibilitou ao grupo manter-se ativo, resistente, nas suas ações coletivas durante 2020.

O Invenções das Crianças de Nova Canudos tomou a dimensão de projeto e foi contemplado no referido Edital, em que crianças, articuladoras/es sociais e membros do Maquinarias foram proponentes, resultando na ajuda de custo para manutenção das atividades realizadas e no fortalecimento de nossos vínculos com outros equipamentos do bairro. A proposição das atividades se deu em consonância com as demandas coletivas, implicando intervenções na sede do CCVH, como compra de equipamentos, realização de pintura, reparos e mobilização para limpeza e manutenção da sede.

Este período, devido à impossibilidade de realizar encontros presenciais, fertilizou movimentos nas redes sociais, interligando experiências cotidianas de todes pelas trocas e partilhas. Não obstante a pandemia, fortalecer os vínculos, fazer e inventar COM as crianças continuou como nosso horizonte ético. Para tanto, os encontros passaram a acontecer, por meio da plataforma Google Meet, sendo o grupo no Whatsapp o espaço das conversas cotidianas, dos combinados das ações, da emergência e do compartilhamento das ideias, da escuta de demandas e interesses, tornando-se, assim, território novo a explorar e construir. Tendo em vista o acesso pouco democrático à internet e as demandas específicas, conseguimos realizar alguns encontros presenciais, respeitando protocolos de cuidado para a não propagação da covid-19. O acompanhamento dessas atividades e da mobilização para que elas acontecessem acabou se dando de modo contínuo, quase que diariamente.

Intitulamos de ações virtuais aquelas que se debruçaram sobre temáticas de interesse das crianças e dos adolescentes, assim como aquelas referentes à capilarização de sua participação em eventos virtuais:

-   “I Exposição Virtual de Desenhos do Maquinarias”;
-   “Encontro para conversar sobre o uso do YouTube”;
-   “Leituras coletivas de livros”;
-   “Participação no III Colorindo O Gênero”; e
-   “Participação em Live de 30 anos do Estatuto da Criança e do Adolescente”.

A exposição virtual de desenhos nos mobilizou em meio ao cotidiano do isolamento social, mantendo-nos conectados diante da livre expressão e da situação de cada uma/um no momento. Os desenhos foram expostos nas redes sociais dos projetos e do CCVH. A oficina sobre as relações entre crianças e uso do YouTube, realizada em parceria com o Laboratório de Pesquisa das Relações Entre Infância, Juventude e Mídia (LABGRIM), vinculado ao Instituto de Cultura e Arte/ICA da UFC, surgiu das experimentações das crianças para criação de canais no YouTube e do desejo de falar sobre suas inspirações e seus objetivos. A partir disso, foi possível criar um momento para refletir sobre produção de conteúdos para/na plataforma, exposição de imagens, inspirações e canais mais acessados, cuidado de si e segurança.

Os momentos para experienciar a leitura de forma coletiva mostraram-se potentes, desde a expectativa do encontro, pela dimensão lúdica e participativa assumida pelos integrantes do grupo. Trocar percepções e sentidos acerca da obra era motivo de alegria, apesar das dificuldades impostas pela baixa qualidade das conexões e dos modos de acesso, geralmente feito pelos celulares. Durante mobilizações em torno dos 30 anos do Estatuto da Criança e do Adolescente (ECA), uma das meninas do Invenções participou de live promovida pelo Fórum Permanente de ONGs de Defesa de Direitos de Crianças e Adolescentes do Ceará (Fórum DCA Ceará), expressando sua visão sobre o racismo e sobre os desafios da pandemia, além de recitar dois poemas autorais.

Um segundo conjunto de atividades resultou de articulações no território, com membros da equipe de extensão e pesquisa, articuladoras/es do CDVHS e da Rede de Desenvolvimento Local, Integrado e Sustentável (Rede Dlis), e com as próprias crianças, a saber:

-   “Entrega de máscaras e de cartilha de orientações da Organização Mundial da Saúde”;
-   “Entrega de kits ‘Invenções e Distração’”;
-   “Duas sessões cinemas no CCVH”;
-   “Mutirão de limpeza no CCVH”; e
-   “Curso de Audiovisual”.

Todas as atividades demandaram encontros presenciais, possíveis em momentos específicos da pandemia da COVID-19 – a presencialidade desses momentos também se deveu à necessidade de escuta dos modos de enfrentamento das crianças e à sua saúde mental. O tema do cuidado de si e do outro, como questão coletiva, permeou as atividades de partilha de informações sobre a propagação do novo coronavírus e da situação do território e do país. Desse modo, o grupo efetivou-se como dispositivo de promoção da saúde, diretamente relacionado às vivências, dúvidas, dificuldades e ideias levantadas pelas crianças enquanto coletivo.

## Considerações finais

As intervenções psicossociais descritas e analisadas neste texto emergiram do acompanhamento e da proposição conjunta de atividades junto a um grupo intergeracional, do qual participam crianças em idades diferentes, adultas/os e jovens moradores/as da periferia de Fortaleza, bem como articuladoras/es e extensionistas. O trabalho requer mediação, implicação, além de escuta permanente e ativa das crianças, exigindo flexibilidade e criatividade metodológica.

Sua elaboração caracteriza um trabalho sensível, ético e contextualizado, pela construção e manutenção de espaços em que seja real o exercício do direito de participação pelas crianças. A produção coletiva de conhecimento reposiciona a universidade, que deixa o lugar imponente do centro para ocupar o lugar do partilhar, do pensar implicado, como uma das forças que produz um espaço comum. Nessa perspectiva, aprender com o “Invenções das Crianças de Nova Canudos” decoloniza o campo de pesquisa acerca da participação social das crianças e fortalece os efeitos de suas ações para o âmbito da vida comunitária e das políticas públicas incidentes em contextos periféricos da cidade de Fortaleza.

Esperamos que as pistas e trilhas partilhadas possam ser inspiração a outros atores e territórios, uma vez orientadas eticamente pelo interesse em criar condições para participação das crianças, a partir de seus contextos de vida e cotidianos, além de um convite a experimentar a criatividade e diversidade metodológicas atreladas à escuta das crianças e dos adolescentes e aos desejos que agenciam para as mudanças no corpo social.
