---
toc: false
---

# Folha de rosto {.unnumbered}

::: {style="line-height: 1;"}
**Produções Técnicas em Psicologia: Experiências Compartilhadas**

Este livro é distribuído sob os termos da [CC BY-NC-ND 4.0 DEED](https://creativecommons.org/licenses/by-nc-nd/4.0/){.external target="_blank"}.

**Publicado no Brasil**

*Programa de Pós-graduação em Psicologia (PPGPSI) - Universidade Federal do Ceará*

Av. da Universidade, 2762, Benfica - CEP: 60020-180 - Fortaleza/CE – Área 2 do Centro de Humanidades - Bloco Didático Prof. Ícaro de Sousa Moreira - 1º andar.

*Programa de Pós-graduação Profissional em Psicologia e Políticas Públicas (PPGPPPP) - Universidade Federal do Ceará*

Rua Coronel Estanislau Frota, 563 – Centro – CEP 62010-560 – Sobral – CE – Campus Sobral – Mucambinho

**Arte da capa**

Nara Maria Forte Diogo Rocha

**Diagramação da capa**

Francisco Pablo Huascar Aragão Pinheiro

**Revisão de texto**

João Paulo Silva Matos

::: {.callout-note appearance="simple" icon=false}

[joaopaulosmatos2\@gmail.com](mailto: joaopaulosmatos2@gmail.com)

:::

**Codificação para construção do livro**

Esthela Sá Cunha 

::: {.callout-note appearance="simple" icon=false}

## Beta Consultoria e Assessoria Acadêmica
<br>
[beta.consultac\@gmail.com](mailto: beta.consultac@gmail.com)

[\@beta_consultoria_academica](https://www.instagram.com/beta_consultoria_academica/ "Instagram"){.external target="_blank"}

[https://esthela.quarto.pub/beta/](https://esthela.quarto.pub/beta/){.external target="_blank"}

:::

Francisco Pablo Huascar Aragão Pinheiro

**Financiamento**

Este livro foi apoiado pela Fundação Cearense de Apoio ao Desenvolvimento Científico e Tecnológico (FUNCAP) \[processo número: BP5-0197-00046.01.00/22\].

:::
