---
author: 
  - name: Rita Helena Sousa Ferreira Gomes
    orcid: 0000-0002-2306-4264
    email: ritahelenagomes@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará    
  - name: Iratan Bezerra de Sabóia
    orcid: 0000-0003-3312-9954
    email: iratan@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Ana Cecília Carenina Machado Mourão
    orcid: 0000-0002-8569-224X
    email: ceciliamachadoodontologia@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Ana Késia Silva Faustino
    orcid: 0009-0003-3873-9214
    email: kesia.faustino.2000@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Andressa da Silva Rodrigues
    orcid: 0009-0009-2196-3694
    email: andressa20srodrigues@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Giovana Freitas Oliveira
    orcid: 0009-0005-0351-6517
    email: giovanaoll@alu.ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: José Edberto Gadelha Rocha Júnior
    orcid: 0000-0002-6660-1728
    email: edbertojunior.psi@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Vitória Brandão de Lima Borges
    orcid: 0009-0005-9397-1547
    email: vitoriabrandao66@gmail.com
    affiliations: 
      - name: Unifametro
language: 
  title-block-author-plural: "Autores"
filters:
  - section-bibliographies
bibliography: gomes_polifonias.bib
reference-section-title: Referências
---

# Polifonias: transdisciplinaridade, divulgação científica e diálogo em ação

## Introdução

Muito se tem discutido sobre o aparente distanciamento entre o conhecimento científico e a sociedade. No cenário da pandemia[^gomes_polifonias-1], e mesmo antes dele, observamos renascer manifestações anticientíficas como os movimentos antivacinas, o retorno da crença na terra plana, além do uso de medicamentos sem comprovação científica para tratamento de doenças. Igualmente, as instituições que produzem um conhecimento acadêmico, como escolas, universidades e divulgadores científicos, não têm tido sucesso em manter um diálogo com a sociedade. Diversas vezes, a linguagem utilizada não facilita a comunicação, e o uso de jargões de difícil compreensão para a grande maioria da população dita “leiga” cria uma barreira intransponível àqueles que não estão no meio acadêmico. Se o ensino técnico ainda é prevalente no ambiente acadêmico, a transdisciplinaridade e o diálogo surgem como uma forma de aproximar os conhecimentos acadêmico-científicos da realidade, das experiências culturais e dos saberes dos indivíduos, permitindo um enriquecimento e aprendizado fundamentais para o aprimoramento de ambas as dimensões, sem, contudo, negar-lhes suas especificidades.

[^gomes_polifonias-1]: Aqui nos referimos ao surgimento do SARS-CoV-2, que ocasionou a pandemia da COVID-19 no Brasil desde março de 2020.

Este capítulo objetiva apresentar aspectos que atravessam e compõem o projeto de extensão Polifonias, destacando tanto as suas práticas, que, em geral, se caracterizam como uma produção técnica do tipo “Organização de Evento”, quanto as principais diretrizes teóricas que as embasam. Com essa finalidade, o capítulo é subdividido em 2 tópicos, respectivamente:

1.  introduzir o projeto e suas atividades; e
2.  apontar elementos conceituais da transdisciplinaridade, do diálogo e da divulgação científica que são relevantes para a referida ação extensionista.

Ao final, além de serem concisamente retomados os pontos discutidos, são elencados alguns desafios para a melhoria das atividades do Polifonias.

## Conhecendo o Projeto Polifonias

O Polifonias é um projeto de extensão da Universidade Federal do Ceará – Campus Sobral o qual parte da importância de um ensino transversal, transdisciplinar, descolonizado e transformador que ultrapasse as barreiras da universidade. Só através da democratização do saber é possível contribuir para amenizar as vulnerabilidades, formando profissionais mais éticos e cientes de sua responsabilidade com a comunidade geral, bem como garantindo que diferentes atores sociais participem ativamente da produção do conhecimento. Assim, o Polifonias tem como objetivo principal a divulgação dos saberes científicos e filosóficos prezando por uma linguagem simples e acessível que facilite a aproximação e o diálogo entre os públicos acadêmico e não acadêmico.

Embora tenha sido registrado na Pró-Reitoria de Extensão apenas em janeiro de 2020, o projeto tem seu nascedouro em um encontro realizado em 31 de outubro de 2019, no auditório do Mucambinho (UFC/Sobral). O evento contou com a participação de 4 professores doutores vinculados à UFC/Sobral para dialogarem entre si e com o público presente acerca do “Tempo”. O tema foi tratado a partir da perspectiva da Música, com a Dra. Adeline Stervinou; da Física, com o Dr. João Guilherme Matias Nogueira; da Engenharia, com o Dr. José Cláudio do Nascimento; e da antropologia, com a Dra. Denise Silva. Apesar do alto nível dos convidados, solicitou-se que o tema fosse abordado de modo a ser compreensível e instigante para um público que mesclava estudantes e professores de diversos cursos de graduação e pós-graduação. Cada convidado teve entre 10 e 15 minutos de fala, e, após estas, houve abertura para comentários e questões da plateia.

O evento foi muito bem-sucedido, pois, além de estimar-se a participação de 80 a 90 pessoas, foi notório o interesse de todos (convidados e público) em trocar ideias e fazer articulações transdisciplinares em um clima em que a informalidade e o rigor científico se mostraram em perfeito equilíbrio. Professores e alunos de cursos tão (aparentemente) diferentes quanto Música, Engenharia Elétrica, Engenharia da Computação e Psicologia travaram diálogos profundos e produtivos, esquecendo-se momentaneamente de sua suposta separação disciplinar. Tamanha foi a receptividade do evento que, ao final, estudantes, convidados e professores procuraram a organização para sugerir outros temas de diálogo, demonstrando, assim, o desejo dos que ali estavam de que a atividade tivesse continuidade. Diante disso, começou-se a cogitar formas de garantir tanto a realização frequente do evento, quanto a ampliação de seu alcance para além dos muros da universidade.

Uma vez o tendo cadastrado nas instâncias devidas, os coordenadores do projeto buscaram, nos primeiros dias de março de 2020, estabelecer uma parceria com a Secretaria de Educação (SEDUC) do município de Sobral. A procura pela SEDUC não foi aleatória, mas sim reflexo do comprometimento do Polifonias em estender-se para além do público universitário, provocando debates nos quais múltiplos posicionamentos sobre um tema pudessem fluir. Pelo plano, convidados e comunidades escolares do ensino básico teriam a chance de construírem conjuntamente um ambiente de trocas no qual a marcação rígida dos lugares de poder e saber fosse permanentemente desafiada.

A SEDUC acolheu a proposta de parceria, entendendo que o aceite traria para o município: uma relevante vivência de práticas transdisciplinares e dialógicas no ambiente escolar regular; um estímulo ao estudo das disciplinas e dos conteúdos curriculares e à leitura acadêmica, por meio de temas transdisciplinares que instigam o raciocínio lógico e complexo de modo acessível, dentre outros. Em contrapartida, a secretaria contribuiria na divulgação dos eventos no interior da comunidade escolar, na concessão de espaço físico e/ou transporte ao local do evento, além de suporte financeiro para publicações derivadas de cada encontro. Contudo, no dia 16 de março de 2020, foi declarado o primeiro momento de isolamento social no município de Sobral por conta da pandemia do vírus SARS-CoV-2 (Covid-19), e, frente a esse quadro, os planos em desenvolvimento com a SEDUC foram adiados para quando a situação sanitária retornasse à normalidade.

Cabia, então, à recém-formada equipe do Polifonias – 2 docentes coordenadores e 6 estudantes de graduação –, como aconteceu com as demais atividades de tantos setores, reinventar ações planejadas para acontecerem presencialmente sem perder de vista os aspectos centrais do projeto ou a preservação da saúde e da vida de todos. Pensando nas possibilidades disponíveis e observando os exemplos existentes, o grupo optou pela realização de encontros de forma online. As redes sociais e a sua popularidade entre os diferentes públicos surgiram para os membros do Polifonias como um instrumento potencialmente interessante para atingir os objetivos do projeto na situação sanitária imposta. A aparente simplicidade das redes sociais, o seu alcance e a velocidade da disseminação de conteúdo fizeram delas a principal fonte de divulgação dos 7 eventos que aconteceram posteriormente. Verificou-se que o Instagram, rede social que originalmente seria de compartilhamento de fotos, passava a ser, para muitos, um instrumento de divulgação profissional, de publicação de tutoriais rápidos e de notícias. Era, portanto, um espaço virtual apto às mobilizações e aos contatos desejados pelo projeto.

A conta do projeto Polifonias no Instagram foi criada no dia 30 de maio de 2020 como local que congregava informações sobre o projeto e as suas atividades, sendo também um ambiente de interação virtual com o público interessado, tendo atualmente 287 seguidores. Com o tempo e amadurecimento da equipe, a página foi também sendo receptáculo de postagens com sugestões de produções artísticas (séries, livros, filmes e músicas) que se relacionassem com o tema gerador do evento mais recente. A opção pela arte justificava-se como uma forma de divulgação eficaz, democrática e convidativa para o grande público, principalmente porque sua linguagem é aberta à diversidade de visões e à subjetividade [@gomes2020artecontra]. Interessa pontuar, ademais, que a introdução da arte na mediação dialógica com o público do projeto gerou um produto, inicialmente, não-previsto: o Clubefonias, ação que, pelo WhatsApp, reúne pessoas de diferentes faixas etárias e realidades para discutir, em encontros quinzenais, uma obra que os próprios membros escolheram.

Além da página do Instagram e do grupo de WhatsApp referente ao Clube Fonias, o projeto criou, em agosto de 2020, um canal no YouTube que abriga os eventos realizados. Nessa rede social de amplo alcance, estão disponíveis 3 dos 7 encontros organizados até o momento.

Em 16 de junho de 2020, ocorreu o primeiro evento na modalidade virtual, por meio do Google Meet, reunindo professores universitários com experiências nas áreas da Arte, da Filosofia e da Psicologia, e um representante de religião de matriz africana para debater o tema "Todos os caminhos levam ao conhecimento". A escolha da temática foi feita pela equipe do Polifonias como uma forma de apresentar a proposta do projeto ao grande público sem parecer uma aula e sem impor uma maneira limitada de pensar o conhecimento. A ideia era, já pelo título do evento, indicar a abertura para o diálogo e o caráter transdisciplinar do projeto. Durante a inscrição para a "live", os participantes foram convidados a sugerir assuntos que gostariam que fossem discutidos em outras ocasiões, dessa maneira buscou-se acessar os tópicos de interesse do público, bem como um pouco da realidade dele. Ao todo, o evento contou com 86 inscritos, tendo tido uma duração total de 2 horas, que foram comprovadas por um certificado emitido pelo projeto para convidados e participantes.

Poucos dias após o evento inaugural, a equipe do projeto reuniu-se para coletivamente avaliar pontos fortes e pontos fracos, a serem melhorados nas ações seguintes. Esse momento mostrou-se essencial e, desde então, foi incorporado no calendário de reuniões do grupo extensionista. Como resultado dessas análises dos eventos, algumas modificações ou guias de ação foram implementadas: garantia, dentro do tempo destinado ao evento, de espaço para as dúvidas/os comentários do público; redução da duração do encontro de 2 horas para 1 hora, considerando que, desde a pandemia, houve um excesso de atividades realizadas virtualmente, o que afeta a adesão do público para eventos delongados; diminuição dos convidados para 2 por vez; criação de 3 perguntas geradoras distribuídas aos convidados no ato do convite, facilitando, assim, a comunicação entre as diferentes perspectivas representadas e a sua conexão com questões vinculadas aos anseios cotidianos; revezamento dos estudantes que perfazem a equipe do projeto na função de mediadores do evento, posto que essa atuação contribui para a formação profissional destes; intensificação da divulgação dos eventos pelo WhatsApp e por outros meios que permitam atingir mais pessoas de fora da universidade; alteração da nomenclatura da “live”, passando de "Roda de Conversa" para "Papo de Boteco”.

A escolha do nome “Papo de Boteco” merece um destaque, tendo em vista estar ligada à compreensão de que o “papel da divulgação científica vem evoluindo ao longo do tempo, acompanhando o próprio desenvolvimento da ciência e tecnologia” [@albagli1996divulgacao]. Em tempos de comunicação rápida e de redes sociais, entendeu-se ser importante adequar o nome ao tipo de evento realizado pelo Polifonias. Ainda que “Roda de conversa” presentifique uma disposição dialógica e informal, carrega também a imagem de uma ação acadêmica, comum e interna aos muros escolares e universitários. “Papo de boteco”, no entanto, remete a um espaço não associado ao universo científico e, nesse sentido, desperta não só a informalidade da conversa e a dialogicidade, mas suscita uma ideia de participação ativa, na qual as discussões, além de acessíveis, são estimulantes. Distanciando os eventos de uma práxis de divulgação científica caracterizada pelas dificuldades de transmissão de conhecimento que os meios acadêmicos e científicos transparecem, reforça-se a abertura para o diálogo com outros tipos de públicos e a oportunidade de entrar em contato com diversos temas. Dessa forma, a divulgação científica acaba assumindo papéis primordiais de democratização do conhecimento científico e, por consequência, abre portas para uma alfabetização científica, contribuindo com a inclusão dos cidadãos em debates de temas especializados que, mesmo sem muitos saberem, têm ligação e influências intrínsecas às suas vidas [@bueno2010comunicacao], bem como soma à educação dos ditos ‘intelectuais’ ao dar-lhes a chance de ampliar/exercitar novas linguagens e articulações a partir de suas expertises.

Vale sublinhar que as reuniões internas da equipe do Polifonias, acontecendo quinzenalmente às sextas-feiras, não são importantes apenas em virtude das decisões “técnicas” que delas brotam. De fato, os encontros do grupo têm servido como uma forma de aproximação leve e criativa dos participantes, já que a maioria dos componentes não tiveram a chance de estreitar laços presencialmente, na medida em que a pandemia se instaurou logo após a entrada deles na equipe. Aproximar-se virtualmente das pessoas foi o principal desafio encontrado no projeto, contudo a experiência interior do grupo tem sido um exemplo de sucesso de como o pensamento e a prática dialógica aliados à transdisciplinaridade são potentes para a construção de laços sociais humanizados e cheios de aprendizados.

Entre 16 de março de 2020 e agosto de 2021, momento da escrita deste capítulo, o Polifonias levou a cabo 7 eventos que, juntos, congregaram 298 participantes no total, dentre estes sendo 16 convidados (11 de origem acadêmica e 5 de filiação não acadêmica). Além do tema do primeiro encontro, já descrito, foram abordados os assuntos: Pandemia e relações familiares; Relações de trabalho na contemporaneidade; Arte e transformação social; Fake news e seus impactos na sociedade; Movimentos sociais; Linguagem – Normas, poder e transformações sociais. Essas temáticas, sempre que possível, levaram em conta as sugestões apresentadas pelo público no ato da inscrição nos eventos. Até hoje, o projeto tem em seu arquivo 17 temas trazidos pelos participantes.

Apesar dessa descrição eminentemente informativa e prática do projeto Polifonias, só é possível conhecê-lo se iluminarmos, ainda que brevemente, as colunas teóricas e éticas que subjazem às suas ações. É com esse intuito que se passa ao próximo tópico.

## Pilares teóricos e éticos do Polifonias

### Transdisciplinaridade

A transdisciplinaridade é entendida como aquilo que está, ao mesmo tempo, entre, através e além de qualquer disciplina. O termo que, segundo Guedes [-@guedes2010importancia], teria sido usado pela primeira vez por Piaget em 1970, acabou sendo formalizado apenas em 1994 com o documento chamado “Carta de la transdisciplinariedad” no Primeiro Congresso Mundial que ocorreu em Portugal. A transdisciplinaridade procura “transgredir a lógica da não-contradição, articulando os contrários: sujeito e objeto, subjetividade e objetividade, matéria e consciência, simplicidade e complexidade, unidade e diversidade” [@nicolescu1999manifesto; @santos2008complexidade]. Em outros termos, a transdisciplinaridade entende que a realidade pode ser vista de forma integrada, borrando as fronteiras entre as formas de conhecimento e suscitando a afirmativa de que o todo – realidade – é altamente complexo e integrado, e as partes – as ciências, por exemplo – estão se comunicando e sustentando-se ativamente. Essa proposta rompe com a ideia fixa e atemporal das dicotomias, compreendendo-as como agentes interativos que necessitam ser considerados a partir das relações que estabelecem entre si. Desse modo, Santos [-@santos2008complexidade] fala que “a compreensão da realidade ascende a outro nível, tomando um significado mais abrangente e sempre em aberto para novos processos” (p. 5).

Uma análise séria da história da ciência evidencia a dimensão transdisciplinar da ciência, uma vez que conhecimento científico e sociedade estão imbricados intimamente. A formação e consolidação da ciência apontam para um modo específico de responder às questões e necessidades da sociedade [@videira2004transdisciplinaridade].

Para além desse enraizamento social, que demonstra que a ciência não é exterior ao mundo, é importante aplicar a perspectiva transdisciplinar à estrutura mesma da ciência. Se, por um lado, a departamentalização da ciência permite avanços indubitáveis através de estudos altamente especializados, por outro as descobertas realizadas em cada área e subárea do saber precisam ser recolocadas na complexa teia de uma realidade que não é abstratamente fragmentada em campos de estudos. Nesse sentido, é fundamental reconhecer o conhecimento científico como constituído por diversos profissionais, com diversos saberes que se relacionam e se interpelam. Assim, a transdisciplinaridade, ao não desconsiderar os aspectos complexos da realidade ao valorizar seu caráter múltiplo, atua de modo a aprimorar o diálogo tanto entre ciência e sociedade, quanto entre as diferentes esferas que compõem o saber científico.

Sob essa ótica, pode-se, segundo Martinazzo [-@martinazzo2020pensamento], afirmar que a transdisciplinaridade se mostra um melhor caminho para alcançar uma realidade que é complexa e multidimensional, haja vista fazer uso de mecanismos que possibilitam uma adequação a essa multiplicidade do real. A transdisciplinaridade, ao considerar tanto o complexo quanto o simples para compreender a realidade, permite que campos diversos sejam contemplados no conhecimento assim como eles se articulam no mundo, abrindo espaço para que ideias contrárias sejam levadas em conta e que todas as áreas do saber exerçam a sua importância.

A transdisciplinaridade tem a pretensão de buscar a superação do universo fechado produzido pela ciência ao trazer à tona a multiplicidade dos modos de produção do conhecimento e ao reconhecer a importância da reintegração do sujeito no processo de observação científica, uma vez que existe uma forte interdependência entre observador, processo de observação e objeto observado [@martinazzo2020pensamento, p.7].

Sendo assim, a transdisciplinaridade, em sua busca por uma reintegração do conhecimento e da participação do sujeito na produção científica, facilita, também, uma disseminação cada vez maior do saber, principalmente em sociedades nas quais a difusão do conhecimento é muitas vezes barrada pelas desigualdades sociais, evidenciando o caráter elitista do acesso ao saber presente nessas culturas. De fato, essa aproximação é construída porque a prática transdisciplinar fortalece a democratização do conhecimento científico na medida em que ela não só considera que esse conhecimento é produzido para a sociedade, mas também que o conhecimento não científico é relevante para a compreensão do mundo. Além disso, a transdisciplinaridade se encontra atrelada à divulgação científica, pois, ao se adequar à complexa e multidimensional realidade, valoriza a contextualização e funda um ambiente no qual ideias e práticas divergentes têm a oportunidade de, respeitosa e rigorosamente, serem confrontadas. Desta feita, a transdisciplinaridade fomenta o diálogo tão necessário à democratização do conhecimento e às sociedades verdadeiramente democráticas e livres.

Manifestadas as qualidades e potências da transdisciplinaridade, resta aberta a questão: como é possível, a partir do cenário universitário brasileiro, promover práticas transdisciplinares?

As pistas para responder a essa pergunta estão na definição de transdisciplinaridade mencionada antes, que indica a necessidade de flexibilização das fronteiras do saber por meio de uma compreensão integrada da realidade. Com base nisso, para que ocorra uma disseminação do conhecimento científico é essencial inventar estratégias que garantam o atravessamento dos impedimentos físicos e sociais do acesso ao saber, sem negligenciar as possibilidades inerentes às tecnologias do nosso tempo. É nessa seara que o Projeto Polifonias tem atuado com seus eventos e ações.

As ações do projeto visam tratar dos mais diversos assuntos contemporâneos a partir de um viés contextualizado e multifacetado, compreendendo que mesmo o mais simples tema carrega dentro de si uma multiplicidade de informações que são estudadas sob a perspectiva de teorias e práticas plurais. Por serem plurais, elas podem ser abordadas desde diferentes referenciais, conferindo ao tema um caráter transdisciplinar. Tomemos como exemplo o primeiro evento nomeado “Todos os caminhos levam ao conhecimento”. Como dito antes, o encontro contou com a participação de 4 convidados, dentre os quais 3 professores universitários (com vinculação aos temas da Arte, da Psicologia e/ou da Filosofia) e um representante religioso. Na ocasião, cada convidado discorreu sobre um tipo de conhecimento relativo à sua área (Arte, Filosofia, Ciência e Religião), destacando não só suas especificidades, mas também suas relações com as demais esferas ali representadas. O objetivo transdisciplinar da atividade foi bem sucedido, posto que, além do entrelaçamento das falas dos convidados que, efetivamente, furou as barreiras tradicionalmente impostas entre aqueles campos de conhecimento, houve a participação do público que, lançando comentários e dúvidas, deu/ampliou o sentido do que estava em pauta, enquanto simultaneamente eram vislumbrados pontos de interação nos diversos discursos dos palestrantes. Já nessa primeira atividade, tornou-se evidente a força e, consequentemente, a necessidade de práticas transdisciplinares no meio científico e não científico como ferramenta de potencialização da disseminação de um conhecimento integrado com a sociedade.

### Divulgação científica

Para falar de divulgação científica é de suma importância que se volte alguns séculos para se pensar no próprio fazer ciência. Conforme destaca Moreira [-@moreira2002revolucao], em meados do século XVII ocorreu a conhecida revolução científica, influenciada por diversos fatores sociodemográficos, trazendo ao cerne do momento o nome de muitos pensadores que hoje se tornam referência no pensamento científico, como Kepler e Galileu. No entanto, mesmo com o crescente reconhecimento da relevância científica e com o desenvolvimento de tecnologias que ampliaram o acesso aos produtos intelectuais, a ciência continua nas mãos de grupos específicos e pequenos – ainda que, claro, significativamente maiores e mais diversos do que nos séculos anteriores –, enquanto a maior parte da população segue leiga sobre o processo de produção do saber científico e tecnológico que subjaz aos modos de vida que lhe são apresentados.

Como pontuado antes, apesar dos muitos conhecimentos que são produzidos dentro dos centros de pesquisas e das academias universitárias, a conexão deles com o público externo deixa a desejar. A difusão do que é produzido, via de regra, não alcança as pessoas que não fazem parte da esfera científica, embora isso pareça ocorrer de forma involuntária, posto nada indicar que pesquisadores tenham interesse nessa segregação. O problema da má distribuição do saber já inquietava Lima Vaz [-@limavaz2000escritos], que sublinhava:

> As grandes revoluções científicas do nosso século, ao mesmo tempo que impelem vertiginosamente o progresso técnico, tornam mais enigmática aos olhos do homem comum, usuário dos objetos que a técnica oferece ao seu consumo e satisfação, a compreensão das articulações teóricas profundas entre o pensamento científico e o fazer técnico. (p. 278).

Uma das consequências dessa má distribuição do saber pode ser vista nos movimentos anticientíficos hodiernos que, usando recursos que só existem por causa do desenvolvimento da ciência e da tecnologia, propagam informações distorcidas e falsas que propulsionam teorias conspiratórias infundadas, porém com possíveis efeitos devastadores que se materializam nas esferas da política, da saúde, da economia, do meio ambiente, etc.

Isso revela a urgência de revermos os modos como tem ocorrido – ou deixado de ocorrer – a propagação do conhecimento científico. Mais do que nunca, é essencial criar espaços nos quais ciência e sociedade possam permanentemente interagir com fluidez. Uma interação fluida e capaz de disseminar eficazmente o conhecimento acadêmico requer que se tenha sempre presente que o público, ao qual se endereça o saber, será composto por pessoas ditas como “leigas”. Isso implica, portanto, que se leve em consideração não somente o meio de divulgação, mas também a linguagem a ser utilizada.

Tradicionalmente, as ciências adotam um tipo de discurso que visa à difusão do conhecimento para um público restrito. Assim, costumeiramente, a comunicação científica interpares não precisa fazer concessões em seu discurso especializado, já que, apesar de usar uma linguagem restrita, encontra como interlocutor primordial um público muito específico que é familiarizado com aquele vocabulário e forma de apresentação dos dados. Todavia, ao pretenderem se expandir para fora daqueles grupos versados no glossário acadêmico, cientistas e intelectuais, normalmente, agem acreditando, como aponta Bueno [-@bueno2010comunicacao], “que seu público compartilha os mesmos conceitos e que o jargão técnico constitui patrimônio comum” (p. 3). Contudo, a pressuposição de que as próprias palavras escolhidas para compor o discurso já carregam em si determinados significados e funções não pode ser dissociada da noção de que é a partir do contato com o ouvinte que esses significados e funções tomam forma. Logo, no contato com os sujeitos fora do ambiente científico, palavras que demandam uma concepção que é restrita aos círculos dos pesquisadores não se comportam significados [@authierrevuz2015dialogismo] e põem por terra o esforço de divulgação da produção.

Nesse contexto, o Polifonias pretende trabalhar com a prática de divulgação científica, compreendendo-a como um processo de recodificação do discurso especializado com o objetivo de tornar o conteúdo acessível a uma extensa audiência [@bueno2010comunicacao], um esforço de traduzir e decodificar as informações moldadas nos códigos e jargões acadêmico-científicos, para uma linguagem mais habitual e passível de entendimento pelo público não alfabetizado cientificamente [@bueno2010comunicacao]. O projeto assume que a disseminação do saber é cabível em “toda atividade de explicação e difusão dos conhecimentos, da cultura e do pensamento científico e técnico, sob duas condições: fora do ensino oficial ou equivalente e sem o objetivo de formar especialistas” [@marandino2002educacao, p. 5], e, com base nisso, propõe uma conversa coloquial entre os diferentes atores ligados ao tema selecionado para o encontro. Nessa interação, impulsionada por perguntas previamente enviadas aos convidados, pesquisadores, praticantes (profissionais, participantes de movimentos sociais, etc.) e público têm a chance de ajustar e ampliar seus diferentes vocabulários, tecendo coletivamente um glossário que sintoniza teorias, práticas e vivências. Eis que do compromisso com a divulgação científica decorre o comprometimento com o diálogo como um pilar nevrálgico do Polifonias.

### Diálogo

Com a ideia de dialogismo, Mikhail Bakhtin colocou luzes nas interações dialógicas que constituem e que são tecidas entre discursos, afirmando ser a relação dialógica constitutiva da linguagem [@marcuzzo2008dialogoinconcluso; @rechdan2003dialogismo]. Segundo ele, o ser humano precisa ser visto sempre em sua relação com a alteridade, uma vez que “é impossível pensar o homem fora das relações que o ligam ao outro” [Faraco, 1996 como citado em @marcuzzo2008dialogoinconcluso, p. 4]. Desta forma, a dimensão dialógica não é apenas presente na linguagem e nos discursos, mas atravessa continuamente nossa identidade. Apesar desse entrelaçamento fundante que vincula eu e outro, a realização de relações dialógicas em que uma voz não se submete às demais não estão a priori asseguradas. Neste ponto, entra em cena a noção de polifonia, que aponta para um movimento dialógico em que “diferentes vozes sociais ... se defrontam, se entrechocam, manifestando diferentes pontos de vista sociais sobre um dado objeto ...” [@rechdan2003dialogismo, p. 46]. Esse conceito não dá nome ao projeto à toa: as atividades do Polifonias se caracterizam por mobilizar vozes sociais diversas, criando um ambiente em que discursos distintos têm a oportunidade de se atravessarem mutuamente e, de forma consciente, redesenharem-se na medida em que se dão conta de que suas identidades não são estáticas nem independentes de sua ligação com o outro.

Como visto no tópico que tratou da transdisciplinaridade, o projeto acata a noção de que a construção do conhecimento opera de forma múltipla e constante, abrangendo diferentes aspectos que se modelam, transformam-se ou têm sua validação cessada na medida em que se relacionam. Isso se coaduna com a ideia de que a realidade é complexa, ou seja, não tem apenas um nível, um lado, um conhecimento, todos alcançáveis definitivamente. Por esse ângulo, a hierarquização do conhecimento ou de certas áreas como menos ou mais importantes perde uma significação apriorística, vez que o motor e a validação do saber passam a ser entendidos como inseparáveis do fluxo de conhecimentos, experiências e consequências que estão em jogo.

O trajeto que o Polifonias vem trilhando procura, ainda, ter presente que não somente a realidade, mas também os sujeitos que a habitam e compõem são complexos. Destarte, assumindo seu compromisso de ter efeito transformador no mundo, o projeto considera os indivíduos como portadores de histórias, vivências e percepções de mundo [@lucena2016dialogica]. Em vista disso, Paulo Freire [-@freire2008medoeousadia] aparece como um referencial incontornável, porquanto entende que “... o diálogo é, em si, criativo e re-criativo” \[e que\] o diálogo sela o ato de aprender, que nunca é individual, embora tenha uma dimensão individual” (pp. 13-14). Subscrevendo Freire [-@freire2008medoeousadia], o Polifonias se esforça por convocar, através do diálogo, os indivíduos como sujeitos criadores dotados de riquezas particulares, cuja ação/inação tem impacto na realidade. Ao lançar o diálogo como parte da coluna dorsal de suas atividades, o projeto ratifica a ideia de que o conhecimento é produto da coletividade dos sujeitos que, cientes ou não, inventam e reinventam o mundo.

Isto posto, ao pensar a divulgação científica pelas lentes dialógicas, reafirma-se a necessidade discutida no tópico precedente de subverter a forma convencional como nos relacionamos com a linguagem, a fim de criar espaços diversificados em que as palavras façam sentido para todos. Essa tarefa é especialmente árdua em um país imerso em grandes índices de desigualdade social e concentração de renda, a qual precisa considerar seriamente que em palestras formais, em congressos, ou mesmo na sala de aula, a linguagem utilizada pode incluir ou afastar os sujeitos, que historicamente tiveram seus saberes negados e apagados pela imposição de uma cultura hegemônica, inclusive instrumentalizada por teorias e instituições científicas.

Chauí [-@chaui2002sereducador], nos convida a dar o passo seguinte ao recordar que “a democracia coloca na ordem do dia o problema da violência, isto é, da redução do sujeito à condição de coisa”(p. 68). Quer dizer, ao adotar o diálogo como forma de divulgação científica, o Polifonias não se ocupa simplesmente com a dimensão cosmética da linguagem, tornando-a palatável e acessível aos indivíduos situados fora do meio acadêmico, mais do que isso, os eventos do projeto miram a valorização das inúmeras maneiras dos sujeitos de produzir, significar e narrar as culturas e os saberes.

Deste modo, as ações do Polifonias se contrapõem a uma 'missão colonizadora', cujo projeto foi homogeneizar o mundo, obliterando as diferenças culturais. Pelas mãos de uma colonização profundamente antidemocrática e antidialógica, desperdiçou-se muita experiência social e reduziu-se a diversidade epistemológica, cultural e política do mundo, e aquelas que manejaram sobreviver aos avanços colonizadores foram submetidas à norma epistemológica dominante [@santos2008complexidade].

Ao estabelecer o diálogo como diretriz inescapável de suas atividades, o Polifonias reconhece a existência de uma colonialidade do conhecimento e posiciona-se contra ela. Admitir que a fala implica relações de poder é não se furtar de, recorrentemente, se perguntar: Quem fala? Para quem se fala? Sobre o que se fala? Como se fala? Que práticas discursivas estão sendo negadas e quais estão sendo legitimadas? A quem serve esse discurso?

Fazer essas questões e estar empenhado em sempre retomá-las delineia o horizonte ético do projeto, instigando seus membros a reiteradamente pensar em formas de criar espaços onde os saberes possam circular dialogicamente, onde todas as falas importem e onde a divulgação científica seja efetiva, justamente porque os muros que separam o saber científico do saber popular podem ser, coletivamente, retraçados.

## Considerações Finais

O Projeto de Extensão Polifonias, a partir de práticas transdisciplinares e dialógicas, procura divulgar o conhecimento científico para além da universidade, e assim romper com os muros e a hierarquização do saber. Suas atividades têm como pilar norteador a transdisciplinaridade, ganhando ainda mais força por meio do diálogo que auxilia na elaboração e condução dos eventos, tornando-os acessíveis ao público em geral e tornando o projeto uma construção erguida a muitas mãos. As ações do projeto focam na divulgação do conhecimento, entendendo-a como um processo coletivamente gestado a partir do encontro de diferentes sujeitos que têm oportunidade de ouvir e serem ouvidos. Nesse sentido, pode-se afirmar que a finalidade maior com a qual o Polifonias pretende colaborar é a transformação social que fortalece e incentiva a invenção de um conhecimento complexo, enraizado e pertinente aos problemas que afligem os vários atores e contextos que tecem as sociedades.

Por isso, os eventos organizados pelo projeto trazem o interesse pelo diálogo e pelo contato com o outro marcado em seu nome. “Polifonias”, “Papos de boteco” e “Clubefonia” tiram a rigidez com que as informações científicas são abordadas costumeiramente, dando origem a conversas descontraídas e potentes, exatamente porque são mais do que locais de “repasse de informações”. O público não é visto de forma passiva, pelo contrário, seus pensamentos, suas culturas e seus conhecimentos são incorporados ao diálogo para abranger o contato e entendimento da realidade. Portanto, é válido dizer que o Polifonias trabalha com a pluralidade de vozes, de ideias, de pessoas, de culturas e de saberes. Movido pela possibilidade de olhar o mundo por uma óptica transdisciplinar, o projeto procura aprender, expressar e fomentar essa visão através de suas ações.

Não obstante, há entraves e espaço de melhoria para o projeto. Entre os desafios, a equipe do Polifonias tem se dedicado a encontrar estratégias para “furar a bolha”, ou seja, conseguir mobilizar cada vez mais a participação de pessoas de fora da universidade que têm acesso ao projeto e a seus eventos. Nessa lida, o grupo tem se organizado para promover uma ação de divulgação, por meio de diferentes mídias sociais (Instagram, Whatsapp, Facebook, etc.), do projeto em si, enfatizando seu interesse por um público de variados níveis educacionais, formações e atuações sociais.

Outro obstáculo a ser enfrentado é imposto pelas limitações próprias ao ambiente virtual dos eventos. Por um lado, ele viabiliza o rompimento de barreiras físicas, ao congregar indivíduos de diferentes cidades, por outro, porém, restringe a intensidade das interações possíveis, afetando, especialmente, o diálogo com o público participante que, nesse cenário, tende a mostrar-se mais passivo.

Ciente dessas e de outras dificuldades, o Polifonias segue firme no seu intento de, através de suas ações, possibilitar uma troca de conhecimentos e reestabelecer o contato há tempos perdido entre ciência e sociedade, trazendo a comunidade para um novo lugar: o de construtora de conhecimento, contribuindo assim com a divulgação científica.
