---
author: 
  - name: Francisco Pablo Huascar Aragão Pinheiro
    url:  http://lattes.cnpq.br/8266089190930601
    orcid: 0000-0001-9289-845X
    email: pablo.pinheiro@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará    
  - name: João Paulo Pereira Barros
    url: http://lattes.cnpq.br/0351156693555523
    orcid: 0000-0001-7680-576X
    email: joaopaulobarros@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
language: 
  title-block-author-plural: "Organizadores"
filters:
  - section-bibliographies
bibliography: apresentacao.bib
reference-section-title: Referências
citeproc: false
toc: false
---

# Apresentação {.unnumbered}

Comentar sobre a construção desse livro, é discutir sobre uma produção técnica. Conforme a última classificação da CAPES [@hemerly2019producao], um produto de editoração é definido como resultante de “processos de edição e publicação de obras de ficção e não-ficção. Compreende planejar e executar, intelectual e graficamente, livros, enciclopédias, preparando textos, ilustrações, diagramação etc. com vinculação ao Programa (projetos, linhas, discentes/egressos)” (p. 41). Em linhas gerais, foi isso o que fizemos e, por esta definição, estamos bem enquadrados.

Dito isto, é preciso declarar que produzir este livro foi uma forma de nos libertarmos de algumas amarras, apesar de ainda estarmos presos a outra, não por opção, mas por uma institucionalidade que podemos qualificar, no mínimo, como questionável. Voltaremos a esta amarra institucional em especial adiante.

A primeira amarra de que nos livramos ao construir esse livro foram das editoras comerciais. Em um mundo analógico, no qual os livros precisavam ser impressos e distribuídos para que seu conteúdo fosse acessado, as editoras desempenharam um papel relevante. Manter a estrutura necessária para que um livro saísse da cabeça de alguém e chegasse até o leitor era caro e a maioria das pessoas que gostaria de publicar algo não tinha condição de despender dos recursos necessários. Se isso é verdade, por outro lado, estava concentrada nas mãos de algumas poucas empresas a decisão sobre o que público deveria ler e o que ditava essa decisão era o possível retorno comercial de uma obra. Havia, portanto, um oligopólio sobre o pensamento.

Essa mesma lógica se aplica a qualquer outra forma de expressão que dependia de meios e estruturas analógicas para ser criada e distribuída: música, filmes, notícias etc. Contudo, hoje vivemos em um mundo em que a produção e a transmissão de informações se dão digitalmente. Então, da mesma forma que não se precisa mais de uma mesa de som para gravar e de um disco de vinil para materializar um fonograma, o impresso em papel é dispensável (o que não quer dizer que não tenha valor). Também não é mais necessário um caminhão transportando toneladas de livros para lá e para cá para que as pessoas possam acessá-los.

Apesar dessa libertação, essa história, que ainda não terminou, até o momento, parece não ter um desenrolar feliz. O capitalismo é como os borgs: sempre acha um jeito de se adaptar e repete insistentemente que resistir é inútil. No novo mundo da internet, o oligopólio da produção e distribuição analógica de editoras, gravadoras, rádios e tvs foi substituído pelo das grandes empresas de tecnologia a partir das plataformas de streaming, sejam de vídeo, de áudio ou, até mesmo, de livros. Ok, podemos criar e distribuir o livro, as músicas e as notícias sem intermediários, mas, só terá chance de aparecer e destacar quem estiver vinculado às plataformas de transmissão mais conhecidas, com raras exceções.

Apesar desse revés, a premissa inicial, de que é possível criar e distribuir sem intermediários, é válida, pode ser explorada e foi o que fizemos. Nesse contexto, esse livro foi construído com o software livre e gratuito chamado Quarto, que é agnóstico, ou seja, não está preso a uma plataforma específica. No nosso caso, o R e o R Studio foram as ferramentas utilizadas para mediar nossa relação com os documentos e demais arquivos que criamos. Ademais, todo o código utilizado para a produção do livro está disponível publicamente no [GitHub](https://github.com/pablo-huascar/livro_pt_2024){.external target="_blank"}.

Nessa nova forma de organização digital, também ficamos livres da linearidade que o meio analógico impõe. Quando usávamos uma fita cassete, para chegar na música que queríamos ouvir precisávamos fazer o rolo andar até o ponto em que ela estava. Se estivéssemos assistindo um programa de tv e precisássemos ir ao banheiro por alguns instantes, perdíamos aquele momento crucial da série em que toda a trama era revelada. Hoje, podemos até mesmo pausar uma transmissão de tv ao vivo e retornar depois.

Assim, num livro, tínhamos uma série de palavras e gravuras impressas e íamos de folha em folha para onde desejávamos. Pessoas com deficiência visual precisavam que uma versão em braile fosse viabilizada para terem acesso ao material de forma autônoma. Nas versões digitais, o livro não precisa ter só palavras ou gravuras e elas não tem uma forma concreta. Nesse sentido, em relação à deficiência visual, leitores de tela são comuns e cada vez mais precisos, o que, desde que o material esteja organizado de forma adequada, permite que ele seja acessado por pessoas cegas ou com baixa visão. Até mesmo as figuras, se estiverem áudio descritas (e no nosso caso estão), podem ser “lidas”.

Nesse contexto, quaisquer dos capítulos deste livro podem ser acessados com um clique e há uma ferramenta de busca para achar termos ou conceitos que se deseje recuperar. Como não precisamos só ter palavras, podemos colocar, por exemplo, vídeos onde quer que desejemos e blocos para que as pessoas executem códigos de R. Eis alguns exemplos de como a possibilidade de reunir diversas mídias em um único espaço foi utilizada nessa produção:

-   O capítulo “Clínica, estética e política do cuidado: a experiência da educação permanente em saúde no contexto da pandemia da covid-19” aborda a experiência de um curso, voltado a profissionais de saúde de diversos municípios cearenses, cujos vídeos estão disponíveis no YouTube. Quem ler esse capítulo vai poder assistir diretamente aos vídeos do curso no próprio livro, pois eles foram entremeados com as palavras, parágrafos e tópicos do texto.

-   Em “Podcasts sobre Psicologia, Direitos Humanos e processos sociopsicológicos contemporâneos: experiências do VIESES-UFC no contexto pandêmico”, alguns dos episódios dos podcasts apresentados estão disponíveis na margem do livro.

-   As análises estatísticas do capítulo “Trabalho e saúde mental de professores do interior do Ceará durante a pandemia de COVID-19: relatório técnico conclusivo de pesquisa” foram feitas com a linguagem de programação R, mencionada anteriormente. Assim, tendo em vista a integração que o Quarto possibilita, todo o código utilizado para a análise dos dados está disponível para os leitores, o que segue uma tendência de promover ciência aberta e reprodutível.

-   Ainda sobre R, no capítulo “Relatório sobre o curso ‘Introdução ao R para análise de dados em psicologia’: proposta e construção”, é possível executar códigos em R dentro do próprio livro. Alguns exemplos de assuntos que o curso aborda são apresentados e o leitor pode tentar executar alguns exercícios sobre eles no próprio capítulo.

Estes são exemplos do que é possível fazer e, na medida em que os pesquisadores compreenderem melhor estas possibilidades de intersecção, muito mais pode ser articulado. Há um universo de criatividade a ser desbravado.

A terceira amarra não depende só de meios tecnológicos para nos livrarmos dela. Depende de uma luta política para se repensar a produção científica no Brasil e, em especial, as formas de avaliação dos programas de pós-graduação, da concessão de bolsas e de financiamentos para pesquisadores. Já ouvi, de mais de uma voz sensata, que Einstein nunca teria um projeto aprovado no Brasil. Ao longo dos anos, uma lógica gerencialista neoliberal se apossou da educação brasileira, em todos os níveis, e parece ter criado raízes nos mecanismos de avaliação.

A fórmula é muito parecida com a da financeirização que tomou conta das empresas: só importa o lucro trimestral para distribuição de dividendos e para aumentar os bônus dos gestores. A rentabilidade imediata deve vir a qualquer custo mesmo que, para isso, seja necessário fazer cortes que vão tirar as possibilidades de inovação e, no longo prazo, tornar a empresa sem capacidade de competição no mercado.

Na pós-graduação, o que se vê é: publique massivamente, mesmo que sejam produtos absolutamente irrelevantes, mas que ganhem pontos nas tabelas de avaliação miraculosamente elaboradas. Quanto mais você fizer isso, mais acesso a recursos e “prestígio no meio” você vai ter, para, quem sabe algum dia, fazer aquilo que de fato acredita que precisa ser feito.

Por óbvio, não estamos dizendo que toda a produção é irrelevante, há inúmeras inovações e descobertas que surgem em meio a essa lógica perversa, mas a caricatura serve para mostrar o caminho que esse modelo nos leva a percorrer. Feita esta ressalva, no longo prazo, é preciso denunciar que esse modelo de resultados em tabelas de pontuação aplicado à pós-graduação pode tornar a produção científica volumosa, mas sem qualquer repercussão, seja na ciência básica, em que simplesmente se quer compreender como o universo funciona, seja na tentativa de resolver os inúmeros problemas que o país enfrenta.

Esse modelo já tem subprodutos: o comércio de participação em livros coletânea, cuja propaganda afirma serem “aderentes ao Qualis CAPES”, e, talvez eticamente ainda mais questionável, a venda de coautoria em capítulos. Se o jogo é pontuar, qual o problema de vender a pontuação para quem quer ou precisa? A lógica é simples: pagou, publicou e pontuou.

E o que fazemos? Inventamos um nome bonito para não ir à raiz do problema: são editoras e periódicos “predatórios”. Vamos fazer infindáveis listinhas para colocá-los na nossa fogueira acadêmica das vaidades, bradar aos quatro ventos que essas práticas precisam ser combatidas e continuar evitando a discussão que realmente importa que é nos perguntarmos o porquê de a avaliação ter esse caráter somente quantitativo baseado em pontuações com critérios questionáveis. Há elementos ‘qualitativos’ nas fichas de avaliação, mas, ao fim e ao cabo, é o volume de produção “bem pontuada” que conta e é a concorrência entre os programas que está na base do sistema avaliativo.

Nesse sentido, não vamos criticar as pessoas que organizam e ganham dinheiro com esse comércio, mesmo que a prática seja moralmente questionável (diga-nos algo no capitalismo que não é?), nem as pessoas que dele participam, porque eles não são a causa do problema e sim a consequência mais óbvia do modelo que estamos questionando. Não vamos criticar, mas temos que nos perguntar: alguém acredita na relevância da maior parte do “conhecimento” que é gerado nessa feira da fruta acadêmica? E essa feira nasce do modelo gerencialista que precisa criar tabelas de pontuação para dizer quem é mais ou quem é menos nesse ranqueamento feito a cada quatro anos, no que diz respeito aos programas de pós-graduação.

Um pequeno adendo para mostrar como isso se espalha por toda a educação brasileira. Algo similar acontece na educação básica quando se olha para as avaliações em larga escala, uma proposta estadunidense que já se mostrou equivocada por lá, mas que ainda é tratada com deferência por aqui em função da enorme influência que fundações privadas ligadas a grandes grupos corporativos têm nas políticas educacionais. Diversas prefeituras estampam propagandas mostrando as notas que os municípios e escolas obtiveram no Índice de Desenvolvimento da Educação Básica (IDEB). Os adversários políticos vão acusar os gestores de fraude para conseguir as notas, mas, em muitos casos, não há fraude no sentido que eles estão acusando.

A fraude está em tratar a educação como treinar crianças para resolver provas de português e matemática, as únicas disciplinas avaliadas. Ocorre aí o que se chama de estreitamento curricular [@gesqui2015estreitamento; @rubio2020avaliacao] , no qual todas as outras matérias são relegadas a um segundo plano. Há casos em que professores de história, geografia e de quaisquer outras disciplinas são pressionados a ministrar os assuntos que serão cobrados nas avaliações externas e abandonarem os seus conteúdos. Se pensarmos bem, até português e matemática são escanteados, porque elas, em si, não interessam, todavia, a capacidade das crianças de resolver as provas. Senso crítico, cidadania, educação científica para quê? O que eu preciso é fazer propaganda de como a nota do município foi alta.

Transladando essa afirmação para a pós-graduação: produção científica de ponta, resolver os problemas do país, fazer descobertas sobre o universo, para quê? O que eu preciso é pontuar, pontuar e pontuar para chegar ao olimpo da nota 7. Nos dois casos, o que isso trouxe de positivo para a sociedade? Ninguém se importa, porque o que está em jogo é o resultado trimestral para distribuir dividendos para os acionistas e dar bônus para os gestores. Nessa lógica, o longo prazo é para quem gosta de filosofar e não de ganhar dinheiro ou pontuar.

Aqui, outro adendo: vamos criticar quem joga o jogo que está posto? Jamais! As pessoas estão tentando sobreviver nessa selva de competição que esse modelo avaliativo criou e são trabalhadores com condições precarizadas de trabalho, que, no meio disso tudo, tentam fazer algo de relevante pelo mundo. O que podemos fazer é convidá-las à reflexão e ao engajamento na luta por melhores condições de trabalho, o que passa por uma mudança profunda em como se avalia a produção científica no Brasil. Achou que nós próprios vamos abandonar esse jogo porque não tem jeito? Achou errado… ! A primeira coisa a que o capitalismo nos condena é ao fatalismo e não vamos nos render a ele.

Como dissemos antes, caricaturamos propositadamente o caminho de irrelevância científica ao qual esse modelo leva, mas reconhecemos a luta de professores, professoras, pesquisadoras e pesquisadores para produzir conhecimento de alto nível em um país que trata ciência e tecnologia como algo subalterno. Se aqui fazemos a denúncia, não é contra os trabalhadores, mas contra o sistema capitalista que entremeou sua lógica financeira na gestão e na avaliação da pós-graduação e conclama o fim da história, como se nada mais fosse possível além do aprofundamento desse modelo perverso.

::: callout-warning
O conteúdo dos capítulos é de inteira responsabilidade dos autores. As opiniões e os posicionamentos adotados não necessariamente refletem os pontos de vista do PPGPSI, do PPGPPPP ou dos organizadores.
:::
