---
author: 
  - name: Mariana Tavares Cavalcanti Liberato
    orcid: 0000-0002-9410-0437
    email: marianaliberato@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará    
  - name: Camila Ribeiro de Oliveira
    orcid: 0000-0003-2975-7106
    email: camisrdeo@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Marta Clarice Nascimento Oliveira
    orcid: 0000-0002-3720-1418
    email: martaclarice03@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Natália Matos de Souza
    orcid: 0000-0001-5064-5761
    email: nataliamatosdesouza@alu.ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Vinicius Nogueira Lopes
    orcid: 0009-0008-8651-7022
    email: vininogueira852@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
language: 
  title-block-author-plural: "Autoras"
filters:
  - section-bibliographies
bibliography: liberato_contagios.bib
reference-section-title: Referências
---

# Contágios possíveis: produção de espaços de uma Psicologia antimanicomial

## Do que move o pensamento a pensar

O trabalho que ora apresentamos origina-se de nosso comprometimento com a construção de uma sociedade sem manicômios. A partir da perspectiva deleuziana de que “mais importante do que o pensamento é o que ‘dá que pensar’...” [@deleuze2003proust, p. 89], fomos impulsionados, diante dessa luta, a criar dispositivos que articulassem o que era experienciado no contato com o nosso campo de intervenção, a saber, um Centro de Atenção Psicossocial (CAPS), e a produção e difusão do conhecimento, na tentativa de inventar espaços, além da atividade acadêmica, que possibilitassem a desconstrução do estigma da loucura.

A produção de conhecimento que se constrói na/pela imersão no campo se ampara na perspectiva do tensionamento que a inserção de corpos em um dado território exerce, à medida que impulsiona a construção de novos saberes, práticas e experimentações. Tendo como referência a cartografia como método de pesquisa e acesso à realidade para Barros e Kastrup [-@passos2009cartografar], o cartógrafo se abre ao movimento de um território e destrincha variáveis de um processo de produção nesse contato.

Neste sentido, a experiência de organização de um evento em alusão ao Dia Nacional da Luta Antimanicomial surge como uma produção técnica relevante, que possibilita a reflexão sobre a construção de um conhecimento implicado e encarnado, que se expande para além das salas de aula e dos muros da Academia. Articulada pelo grupo PASÁRGADA: Promoção de Arte, Saúde e Garantia de Direitos, vinculado ao Departamento de Psicologia e ao Programa de Pós-Graduação em Psicologia da Universidade Federal do Ceará (UFC), campus Fortaleza, em parceria com o serviço substitutivo, entre outros grupos e movimentos sociais, a Semana da Luta Antimanicomial, produzida no ano de 2022, se constituiu como um evento que buscou contagiar a comunidade para a defesa do cuidado em liberdade, tendo como base a necessidade de irradiação de uma nova visão social que afirme a loucura na esfera da coexistência, com livre circulação nas malhas da cidade.

Nessa aventura, partimos de um olhar que concebe a defesa dos direitos das pessoas em sofrimento psíquico como um projeto de transformação social que não se restringe somente à extinção física dos manicômios, mas de todos os mecanismos societários de exclusão e silenciamento da loucura, entendendo que “a questão manicomial ecoa muito além dos muros do hospital psiquiátrico ou do domínio estrito das práticas manicomiais, estendendo-se pelo tecido social” [@pradofilho2020breve, p. 55]. Em outras palavras, a produção desse evento advém da ideia de que não há como resistir ao sistema manicomial sem que se contamine as ruas, desafiando o pensamento daqueles que estão presos a perspectivas opressoras e excludentes sobre a loucura e a diferença.

Com Deleuze [-@deleuze2003proust], aprendemos que "sem algo que force a pensar, sem algo que violente o pensamento, este nada significa" (p. 89). Desse modo, para fazer eclodir o pensar, indo além do que é prescrito pelo senso comum, é preciso que se crie um estado de estranheza, sempre involuntário, que quebre com a mera recognição do mundo externo, o que é provocado pelos signos: “o que nos força a pensar é o signo. O signo é o objeto de um encontro; mas é precisamente a contingência do encontro que garante a necessidade daquilo que ele faz pensar” [@deleuze2003proust, p. 91].

O pensar é, portanto, uma atividade desencadeada involuntariamente sob a violência do encontro com os signos, os quais não devem ser confundidos com os significantes, pois nos signos não há um sentido dado de antemão que deve ser reconhecido. Ao contrário, “o signo implica em si a heterogeneidade como relação” [@deleuze2003proust, p. 21], de forma que todo signo implica uma abertura de mundos que nos afeta de tal modo a impulsionar nossas faculdades além dos limites habituais. Portanto, o signo é diretamente afecto, e o pensar se origina da afecção. Isso nos parece particularmente importante, pois nos dá a abertura necessária para conceber a produção do conhecimento como uma experiência intensiva e corporal, muito longe de uma atitude recognitiva.

O que estamos a defender aqui é que o pensar não parte de algo pré-estabelecido, mas de uma produção a partir das sensibilidades. Nosso desafio, portanto, foi o de possibilitar encontros intensivos, pela via dos signos, que afirmassem a produção e propagação do conhecimento como uma experiência sensível e implicada. Mais do que isso, sabemos que o signo, como afecto, se efetiva na construção de outros mundos incompatíveis com o instituído [@nascimento2012teoria], de modo que a centralidade da nossa iniciativa esteve ligada à criação de espaços de perturbação que, por força do encontro, tensionassem o lugar da loucura no corpo social e contagiassem o outro a respeito do cuidado em liberdade.

Assim, propusemos um evento que se constitui como uma produção técnica voltada para a construção de uma psicologia antimanicomial. Essa iniciativa se faz especialmente necessária em um momento de retrocessos na política nacional de saúde mental que acontecem hoje no Brasil em decorrência da aprovação de uma série de projetos políticos contrários aos ideais de uma sociedade livre de manicômios, sejam eles mentais, sejam estruturais. Diante desse cenário, defendemos que é preciso, mais do que nunca, provocar o pensamento em relação à loucura e ao cuidado em saúde mental, arando o solo para a criação de outras formas de se relacionar com a diferença.

Lembramos, ainda, que a persistência de uma lógica manicomial nos próprios serviços substitutivos é um dos grandes desafios enfrentados pela Rede de Atenção Psicossocial (RAPS), cuja origem, muitas vezes, já se encontra nos processos formativos dos profissionais da saúde, que falham em desconstruir as relações de dominação e cronificação dos usuários, típicas dos modelos manicomiais. Para resistir a isso, criamos um produto inovador, fruto de nossas intervenções e nossos estudos a respeito do cuidado em saúde mental, que coloca a afecção e o contágio da realidade como premissas para a produção e difusão do conhecimento em tempos de tensão e disputa neste âmbito. A seguir, contaremos um pouco sobre a construção desse evento que foi, antes de tudo, a experimentação de um conhecimento que se produz com o outro.

## Do afetar-se e movimentar-se: invenção de “Semana da Luta Antimanicomial”

A iniciativa da Semana da Luta Antimanicomial é resultado dos estudos sobre cuidado em saúde mental e da inserção continuada que o programa PASÁRGADA possui nesse âmbito desde 2019. Por meio da extensão universitária, o grupo desenvolve, até o momento, atividades em dois Centros de Atenção Psicossocial (CAPS) - Tipo II de Fortaleza-CE. No escopo de ações, realiza-se o acompanhamento de grupos terapêuticos, além de atividades na sala de espera dos serviços, e a construção de ações que se expandem para além dos muros desses equipamentos.

Tais intervenções amparam-se na arte como dispositivo que possibilita a fluidez da expressão em suas distintas roupagens, bem como expande a noção comunicativa ao transbordar a linguagem por sentidos que pulsam para além da fala. Deleuze e Guattari [-@deleuze2010filosofia] afirmam que “a arte quer criar um finito que restitua o infinito: traça um plano de composição que carrega por sua vez monumentos ou sensações compostas, sob a ação de figuras estéticas” (p. 253). Nesse sentido, a inventividade característica desse dispositivo possibilita o acesso a um dado conteúdo que transborda o artista, a obra e o sujeito a visualiza, dimensionando uma realidade vibrátil que propõe novos modos de acesso à vida de uma maneira estético-sensível.

É com esse olhar que entendemos que a arte não se limita a uma ferramenta humanizadora do cuidado, pois ela é, também, um recurso que oferece, através da experimentação, novas ancoragens subjetivas para as pessoas em sofrimento psíquico, dando a possibilidade de reinventar a si e ao mundo. Como apontam Costa, Zanella e Fonseca [-@costa2016psicologia], a arte influi justamente na composição de transbordamentos dos limites instituídos que se colocam para a pesquisa, a intervenção e a existência. Assim, ela surge para nós como uma forma de resistência aos modos hegemônicos de viver impostos à loucura, afirmando um processo de ampliação dos campos que ela pode habitar, sejam eles concretos – no caso, sociais –, sejam subjetivos. Portanto, a nossa aliança com a arte é feita, também, dentro de uma perspectiva de luta ética e política, ligada à superação das instituições psiquiátricas e manicomiais, as quais têm ganhado força nos últimos anos.

Em decorrência da situação de isolamento social desencadeada pela pandemia da COVID-19 em 2020, o cuidado produzido nos CAPS se colocou majoritariamente na prestação de atendimento psiquiátrico e psicológico e na distribuição de medicamentos, diante da impossibilidade da realização de atividades coletivas, como grupos terapêuticos e operativos de maneira presencial. Como consequência disto, criou-se um cenário propício para o avanço da lógica de cuidado ambulatorial e medicalizante que vem sendo cultivada na rede de atenção psicossocial de Fortaleza antes mesmo da crise sanitária pandêmica [@guimaraes2016inovacao], mas que se agrava severamente durante o contexto em questão, implicando num expressivo retrocesso da reforma psiquiátrica e do projeto antimanicomial, já bastante fragilizados com o avanço do neoliberalismo e do conservadorismo no país.

O vislumbre da construção do evento da Semana da Luta Antimanicomial se deu a partir do cenário de afrouxamento das medidas sanitárias e da volta de atividades presenciais, no início do ano de 2022. Emerge, ainda, da fruição da memória que constitui o PASÁRGADA, que, em seus anos de existência, realizou diversas ações costurando serviços de saúde, universidade, movimentos sociais e sociedade. Atravessados pelo que afirma Deleuze [-@deleuze1992conversas] quando diz “um pouco de possível, senão eu sufoco...” (p. 131), somos convocados a reencantar o dia 18 de maio em um contexto de fragilização psíquica, social e política, bem como de retrocessos da reforma psiquiátrica e de incerteza diante da realidade que outrora conhecemos e somos convocados a habitar novamente após a calamidade da COVID-19.

Vale ressaltar que o Dia Nacional da Luta Antimanicomial é reflexo de uma série de disputas, bem como da participação ativa da comunidade, dos trabalhadores, dos familiares e das pessoas em sofrimento psíquico. Espírito Santo, Araújo e Amarante (2016) colocam que, a partir do surgimento do Movimento dos Trabalhadores em Saúde Mental (MTSM), em 1970, repercutem denúncias contra o modelo de tratamento até então usado como referência no campo da saúde mental. O olhar estritamente biomédico em conjunto com as denúncias de violência contra os corpos que habitavam os espaços ditos de cuidado descrevem uma situação insustentável, que resulta na ocorrência da 8ª Conferência Nacional de Saúde e, um ano depois, na Primeira Conferência Nacional de Saúde Mental. O cenário de emergência e de mudança produz no segundo congresso do MTSM, ocorrido em 1987, o estabelecimento da data de 18 de maio como marco simbólico para a permanência e implicação de uma luta por direitos, por um cuidado em liberdade e por desmanicomialização da vida.

Amarante e Nunes [-@amarante2018reforma] ressaltam que, na ocasião, foi criado o lema “Por uma sociedade sem manicômios”, e o movimento social se complexificou, ganhando a participação de novos atores sociais (usuários, familiares e outros militantes dos direitos humanos). Ademais, há a construção de um novo horizonte de reivindicação, pautado pela busca da desconstrução da própria lógica manicomial e do seu aparato institucional, constituindo-se, a partir de então, como “Movimento da Luta Antimanicomial (MLA)”. Ainda de acordo com com os autores:

> Elemento decisivo para esta ampliação \[do MLA\] foi a criação, já em Bauru, do Dia Nacional da Luta Antimanicomial. O dia 18 de Maio serviria para despertar o pensamento crítico na sociedade sobre a violência institucional da psiquiatria e a exclusão das pessoas em sofrimento psíquico. Pode-se considerar que o objetivo teve êxito na medida em que, desde então, são realizadas atividades políticas, científicas, culturais e sociais não apenas no dia em questão, mas por todo o mês de maio, que passou a ser considerado o Mês da Luta Antimanicomial. Dada a grande repercussão dos eventos organizados pelo MLA e pela sua também expressiva participação nos fatos mais gerais da saúde, a denominação de mentaleiros (em alusão ao heavy metal) passou a ser amplamente utilizada para caracterizar o “barulho” causado por este ator social [@amarante2018reforma, p. 2070].

Assim, diante da importância dessa data, orientados pela construção de um cuidado integral, em liberdade e em internação (em rede), questionamo-nos sobre como criar atravessamentos que possibilitem cindir o que se encontra enrijecido na atenção psicossocial e dar continuidade à proposta de um cuidado que ultrapassa a estrutura do serviço. Os desafios surgem a partir da interseção de um momento de luto coletivo, de reinserção física nos espaços antes inabitados e de uma sensibilização expressiva acerca das questões referentes à saúde mental e aos laços sociais. Diante disso, somos convocados a tensionar o instituído e apostar na inventividade e na afecção como via de mobilização, criando o evento da Semana da Luta Antimanicomial 2022.

Esta contou com uma programação de atividades diversas distribuídas ao longo de cinco dias de programação, a saber:

1.  Segunda-feira, realização de um cortejo pelo Benfica e de uma roda de conversa na universidade.
2.  Terça-feira, construção de uma ação em sala de espera no CAPS II - CORES IV e de uma mesa redonda na universidade;
3.  Quarta-feira, participação no ato público, promovido pelo Fórum Cearense da Luta Antimanicomial (FCLA), no Centro da cidade;
4.  Quinta-feira, organização da exposição; e
5.  Sexta-feira, mostra presencial da exposição “Desambula: para que o desejo possa fluir”, no Teatro São José.

A construção e efetivação dessa empreitada somente foi possível graças às alianças construídas com instituições e profissionais parceiros, usuários, movimentos sociais, setores da universidade, bem como a uma gama de agenciamentos que, segundo Deleuze e Guattari [-@deleuze2003kafka], “... se estende ou penetra num campo de imanência ilimitado que faz fundir os segmentos, que liberta o desejo de todas as suas concreções e abstrações, ou, pelo menos, luta activamente (sic) contra elas para as dissolver” (p.145). Assim, buscamos criar atravessamentos que trouxessem movimento às práticas cristalizadas no campo da saúde mental.

O evento teve início no dia 16 de maio, segunda-feira, com um cortejo pelas ruas do Benfica, um bairro onde há uma grande movimentação de pessoas e onde se localiza o Departamento de Psicologia da UFC. O ato foi realizado junto ao bloco carnavalesco “Doido é Tu!”. Esse momento apostou na composição de uma luta que se faz a partir das alianças e através do extravasamento de fronteiras, à medida que propõe um contágio com a cidade, com a universidade, com a arte e a cultura, tecendo a luta por um cuidado ético-político. Como aponta Martins [-@martins2009ode], “nas práticas antimanicomiais, a cidade, a loucura e a arte se reencontram e compõem juntas um apelo pela vida. Exigem menos a vida para ser vivida e mais uma vida pulsante....” (p. 86).

O cortejo fez emitir notas que fizeram vibrar a cidade, que convocaram os carros que passavam na avenida a buzinar e as pessoas que passavam na rua a gritar conosco, através de uma porosidade que permeabiliza fronteiras. Levantamos voo, cantamos, andamos, dançamos, gritamos e pousamos. O ato se encerrou no Bosque Moreira Campos, localizado no Centro de Humanidades I da UFC, onde nos reunimos e nos acomodamos para uma roda de conversa intitulada “Lutas Antimanicomiais: Ainda!”. Esse local foi propositadamente escolhido, pois ali há um grande fluxo de pessoas que se locomovem diariamente, podendo, portanto, entrar em contato com a discussão proposta.

Apostamos em adentrar na universidade estilhaçando as cristalizações a despeito da loucura e procurando ampliar esse debate não só dentro de um curso que se diz focado na saúde mental, como o da Psicologia, mas para a sociedade como um todo. Sob essa égide, em concordância com perspectiva basagliana, propusemos pôr em discussão a possibilidade de invenção de novas estratégias de reestruturação da organização cultural com relação à presença do sujeito em sofrimento e do distúrbio que ele determina, produzindo outros modos de expressividade dessa experiência de sofrimento [@basaglia2010escritos].

Instalar-se visivelmente aos transeuntes, cantar, dançar, dialogar e inquirir: pode a loucura ocupar a universidade? Nessa composição entre os fluxos de passagem, a grande roda contou com a participação de usuários e profissionais dos serviços, professores e alunos de variados cursos da universidade. Efetivou-se pelo espaço coletivo de partilha e discussão acerca da história da Luta Antimanicomial e da Reforma Psiquiátrica Brasileira, dos seus processos e retrocessos, bem como da necessidade de manutenção desta na atualidade.

Tensionou-se neste momento esta luta como pluralizada, visto que se trata também de uma luta antirracista, antiLGBTQUIAP+fóbica e antifascista, se configurando como uma reinvidicação por um cuidado que promova qualidade de vida para os corpos que ocupam esse espaço. Basaglia [-@basaglia1985instituição], ao analisar a condição de institucionalizado, coloca o sujeito em sofrimento psíquico como um sujeito sem direitos, submetido aos poderes institucionais, excluído socialmente devido, antes mesmo da doença em si, a sua condição social e econômica. Stela do Patrocínio [-@patrocínio2009reino], poetiza negra internada durante quase 30 anos, traz-nos que “estar internada é ficar o dia todo presa” (p. 47), sendo o manicômio, portanto, uma estratégia de controle e aprisionamento dos corpos, majoritariamente negros e pobres. Posto isto, é de suma importância pensar uma atenção à saúde mental que se faça em liberdade e que seja interseccionalizada, reconhecendo os marcadores identitários que são colocados no campo da subalternização e acabam por produzir adoecimentos e novas roupagens do manicômio.

No segundo dia de evento, organizamos pela manhã uma ação na sala de espera no CAPS II - CORES IV. A proposição desta atividade é de praxe do Pasárgada desde sua inserção nos equipamentos de saúde, em momentos de espera de atendimento ou de requerimento de medicamento, por exemplo. Aposta-se em atividades interativas, instalações provocativas, bem como intervenções que mexem com os corpos presentes, objetivando subverter a lógica ambulatorial que marca essa temporalidade do aguardo. Ademais, corroborando a aproximação que Deleuze [-@deleuze1999ato] destaca entre obra de arte e resistência, almejamos construir outras possibilidades de produção de vida por meio do contato entre o dispositivo e a saúde mental.

Entendendo a possibilidade de construir caminhos possíveis de vida, de outras criações para a existência, a atividade tinha como pergunta-chave “O que fazemos para sermos livres?”, sendo deixadas canetinhas, lápis de cor, lápis, cola, cola colorida e imagens, bem como um cartaz disposto em um cavalete, para produção de uma obra coletiva a partir desse disparador. O objetivo era pensar o que era a liberdade para cada pessoa, o que as afetava nesse sentido e como ela pode partir de uma noção expansiva e coletiva, entendendo os processos de subjetivação e os modos que a existência vai tecendo para além do ideal neoliberal e individualista. A ação foi planejada no sentido de um cuidado implicado com a não individualização dos usuários, propondo, outrossim, um processo de construção de resistências coletivas, frente às opressões sistemáticas que tentam sufocar a diferença, a partir da formação de alianças como aposta possível no processo de experimentação do cuidado em liberdade.

Ainda, à tarde, houve uma mesa redonda no Centro de Humanidades II da UFC, proposta pelo VIESES (Grupo de Pesquisa e Intervenções sobre Violência, Exclusão Social e Subjetivação), em parceria com o FCLA, contando com o apoio do PASÁRGADA, intitulada “Assistência à saúde mental no Ceará: inquietações e proposições”. A mesa tinha como eixo de debate a saúde mental infantojuvenil e os seus desafios atuais; a necropolítica e as incidências na saúde mental; e os embates políticos em torno da assistência a usuários de álcool e outras drogas. Entendemos esse espaço como oportuno para a provocação de um pensamento acadêmico crítico sobre a realidade da saúde mental cearense na atualidade, que pudesse articular diferentes atores sociais de contextos diversos.

Os retrocessos nas políticas de saúde mental que Passarinho [-@passarinho2022retrocessos] demarca ao falar do financiamento governamental de comunidades terapêuticas e hospitais psiquiátricos na Rede de Atenção Psicossocial (RAPS) surgem nesse momento na fala de trabalhadores e usuários. Além disso, denuncia-se, ainda, a má gestão com relação ao cuidado com os trabalhadores, em conjunto com a escassez de promoção de concursos públicos nessa área – estratégias de fortalecimento de vínculo entre profissionais e usuários a partir da permanência no serviço que o processo implica –, surgindo como ferramenta central em uma proposição de cuidado que se faz ética.

O descaso com a saúde mental infanto-juvenil pela falta de incentivo, bem como pela política de mortificação da juventude atravessada por marcadores de raça, gênero e condição socioeconômica é outro tópico sublinhado. A lógica de fazer morrer que promove vida apenas para corpos ditos na esfera da normalidade, é evidenciada nesse momento, a partir dos relatos trazidos pelos inseridos nessa rede, corroborando a noção que Mbembe [-@mbembe2018necropolitica] traz de que, “na economia do biopoder, a função do racismo é regular a distribuição da morte e tornar possíveis as funções assassinas do Estado” (p. 18).

Fora isso, foi colocado que a falta de incentivo à política de redução de danos em favor das lógicas proibicionistas que perpetuam a dinâmica no campo de assistência a usuários de álcool e outras drogas cronifica o problema e reproduz práticas de manicomialização e violência. A redução de danos promove uma construção conjunta para as experiências com substâncias psicoativas que implica uma participação na gestão de políticas da área e ainda a diminuição e até o cessamento do uso de drogas [@passos2011redução]. A mesa com falas sobre esses três eixos deixou muitas inquietações e também trouxe proposições em torno do que foi debatido, tendo como fim levar à frente os pontos destacados para discussão no espaço de conferências e fóruns, de modo a contribuir com o planejamento das políticas públicas.

No terceiro dia de promoção de ações, 18 de maio de 2022, firmamos o compromisso ético-político de estar na rua, participando do ato organizado e conduzido pelo FCLA e mobilizando a comunidade acadêmica para compor tal atividade. A concentração para a manifestação política em prol do cuidado em liberdade se deu na Praça do Ferreira, no centro da cidade, a fim de criar novas zonas de visibilidade para a loucura, isto pois, como aponta Silva [-@silva2006espacos], o local é historicamente marcado pelo

> ...significativo conteúdo social constituindo-se, ao longo dos anos, como um “ícone” para Fortaleza. Tradicional local do encontro e da sociabilidade foi um espaço de lazer por excelência, sendo ainda hoje a praça de maior representação no centro. Torna-se perceptível a grande vitalidade que ali se efetiva, através dos eventos culturais, manifestações sociais e a permanência de alguns usos que vêm resistindo em meio às transformações ocorridas naquele espaço público. (p. 106)

Segundo Amarante [-@amarante2007saude], há uma dimensão sociocultural no processo de reforma psiquiátrica brasileira que é estratégica, no sentido de tentar provocar o imaginário social através de questionamentos sobre a loucura, sobre a doença mental e o hospital psiquiátrico, a partir da produção cultural e artística dos atores sociais que compõem esse movimento. Nesse sentido, historicamente, como citado alhures, o dia 18 de maio, assim como os dias seguintes a ele, marcam movimentos sociais, culturais e políticos nos quais há participação de usuários, profissionais e familiares para reivindicar e garantir direitos, políticas de cuidado, bem como ocupar a cidade em prol da luta antimanicomial.

Desse modo, estar na rua, ocupar a cidade com a arte, a música, a dança e as palavras de ordem, faz-se necessário. Habitar essa territorialidade como ponto de encontro, com corpos para os quais o espaço público é negado, é um processo de afirmação da diferença. Estarmos ali profissionais, usuários, familiares, estudantes, políticos e militantes é uma aposta em desestabilizar o que está posto na macropolítica e na estrutura manicomial, anunciando nossa presença como reivindicação à ocupação do direito à cidade. Além disso, persistir como grupo que se reúne nesta data, diante de um cenário político desafiador – sobretudo no que tange à saúde pública –, constitui-se uma construção coletiva de cuidado, bem como de compromisso ético-político com a pauta antimanicomial, que deve ser fortalecida. Ressaltamos, também, que a participação neste ato aponta para a perspectiva de um conhecimento que se faz não apenas entre os muros da Universidade, de modo teórico, mas que também se constrói a partir da experimentação junto aos atores sociais envolvidos e seus contextos de vida.

Novamente, o bloco carnavalesco “Doido é tu!” esteve presente, potencializando esse momento, com músicas e danças. Produzimos cartazes, levantamos bandeiras e seguimos caminhando em coletivo até a sede da Secretaria Municipal de Saúde de Fortaleza, onde foi entregue uma carta escrita pelo FCLA, listando e reivindicando pautas para efetivação de cuidados na rede de atenção psicossocial de Fortaleza.

No dia 19 de maio, destinamo-nos à organização e montagem de nossa última ação de encerramento daquela Semana, que se caracterizou pela mostra presencial do projeto “Desambural: para que o desejo possa fluir”. Assim, no dia 20 de maio, tivemos tal exposição, agora em formato presencial, em parceria com o CAPS II - CORES IV de Fortaleza. A ideia de tal ação surgiu do desejo de reverberar esta apresentação de obras artísticas que, em seu primeiro momento, aconteceu de forma virtual, com início da produção ainda em 2021, quando houve a proposta, junto à artista do CAPS, para que um dos grupos de arteterapia criasse e organizasse trabalhos para uma mostra, com finalização em 2022. O objetivo foi pensar e fazer, junto à artista e aos usuários do grupo, uma exposição coletiva, construída conjuntamente, desde as atividades propostas no grupo, que resultaram nas artes, à criação objetiva do tema da exposição, do site e do próprio processo de curadoria.

A despeito das dificuldades de se construir um processo de cuidado, através do contato híbrido, em meio a uma pandemia, a exposição virtual foi aberta no dia 16 de fevereiro de 2022, com a divulgação do site criado junto aos artistas, em uma roda de conversa através do Google Meet, e teve seu fechamento no dia 16 de março de 2022. Assim, tentando, sobretudo, propor uma relação que se dá a partir da transformação relacional da sociedade ocidental com a loucura (Amarante, 1994), trouxemos a exposição para o formato presencial no Teatro São José, em Fortaleza, concluindo a Semana da Luta Antimanicomial.

O Teatro São José, lugar escolhido para a exposição, foi criado em 1914 e é um equipamento histórico da cidade de Fortaleza, localizado no centro da cidade, que figura como um grande polo cultural. Tendo sido reformado recentemente, depois de alguns anos fechado, conta, agora, com uma programação cultural importante para a cidade. Assim, a escolha do teatro partiu da nossa vontade, já afirmada, de ocupar o espaço urbano, em lugares de grande movimentação.

As obras que compunham a exposição de forma presencial eram as mesmas da exposição virtual, porém com uma configuração diferente, pois tinham molduras interativas que podiam ser tocadas, produzidas pelos artistas-usuários, feitas com materiais como tampinhas de garrafa, lantejoulas, linhas, glitter e até mesmo sementes. Além disso, todas as obras estavam suspensas com barbantes coloridos, propondo o movimento com corpos para além do tato manual com as materialidades. A sala estava disposta de maneira que as pessoas pudessem fazer um caminho que se iniciava com recepção e informações acerca da construção da exposição e se encaminhava para uma instalação com dois projetores: um transmitindo obras audiovisuais e outro expondo obras estritamente visuais, todas produzidas no espaço do grupo.

Havia, ainda, algumas instalações artísticas que propunham reflexões acerca de temáticas que atravessam o campo da saúde mental. Foi instalado um espelho com a famosa frase “de perto ninguém é normal”, da música “Vaca Profana”, de Caetano Veloso, a partir do qual as pessoas eram chamadas a interagir e fotografar-se. Havia também uma instalação intitulada “Como tornar-se descomprimido? II”, de Caio Prado, no canto da parede, que convocava as pessoas a interagirem descartando cartelas de remédios vazias, com o intuito de trazer reflexões sobre a medicalização da vida. Por fim, organizamos um espaço de criação coletiva onde os visitantes puderam transbordar os afetos deste encontro, colocamos cartolinas em um cavalete antes da saída da sala, dispomos tinta, canetas coloridas, linhas e cola para composição de uma materialidade composta por escritos, desenhos e intervenções dos transeuntes após a visita.

Ao longo do dia, mais de 100 pessoas visitaram a mostra, sendo elas os próprios artistas e seus familiares, usuários de outros CAPS de Fortaleza, como os do CAPS AD da Regional IV, profissionais de saúde, alunos de universidades públicas, faculdades privadas, instituições de ensino médio, cursos técnicos, além de outras tantas pessoas curiosas com a exposição. O propósito era dar visibilidade aos artistas e às obras, já que existia, no grupo, a vontade de expor e que muitos nunca haviam tido a oportunidade, além de pensar como a arte tem um lugar de possibilidade importante quando se trata de cuidado em saúde e de desestigmatização dessas pessoas, colocando a cidade como ponto de implicação.

As cidades, para além de prédios, casas e ruas que se entrelaçam, produzindo uma materialidade, também são palco de afetos e relações sociais (Mansano, 2016). Ao entendermos a cidade como esse lugar de entrelaçamento, compreendemos, também, que é nela que se produzem a vida, os encontros e, também, as discussões. A loucura, que por muito tempo foi aprisionada – a partir do século XVII, como cita Foucault [-@foucault1975doença], ao dizer que a loucura entra nesse mundo da exclusão por um ideal de incapacidade e reconstrução do espaço social da época –, precisa estar também entrelaçada nessa cidade. A saída para o mundo implica, portanto, uma forma de resistência a essas políticas históricas de exclusão, violência e estigmatização desses corpos.

## Considerações finais

Passos et al. [-@passos2021remanicomialização] apontam que o país avança, hoje, para um processo de (re)manicomialização movido pelo interesse de atores que representam um projeto político conservador e neoliberal, centrado na manutenção de privilégios e voltado para as privatizações e o resgate de práticas de controle social. Logo, observamos a importância de eventos como o proposto, seja para produção de uma materialidade vista, tocada, sentida, seja para a produção de uma sensibilização, reflexão, de debates acerca da pauta antimanicomial, atuando na desestigmatização da loucura e na proposição de um cuidado produzido em liberdade.

Uma Psicologia que se pretende Antimanicomial deve buscar, dentro da Universidade, produzir conhecimentos articulados à proposição de novos horizontes éticos e políticos, buscando combater esse cenário de opressão e estigma. Deve, portanto, apostar no compromisso de fomentar saídas para além dos muros da Academia, possibilitando trocas com sujeitos e grupos que, muitas vezes, se encontram à margem dessas discussões, mas que são atravessados pelos efeitos dela e que criam, também, resistências no seu cotidiano.

Nesse sentido, ressaltamos que promover um evento como este, que visou criar deslocamentos, também, na própria forma de produzir o saber e o fazer acadêmicos, somente foi possível a partir de uma perspectiva de trabalho coletivo e com os diferentes atores sociais que formam esse contexto. Contágio mútuo de experiências, pensamentos, criações. Uma produção técnica, mas que, também, é viva e nos lança a novos problemas e inquietações para nossos estudos, nossas pesquisas e práticas. Na interface entre Universidade e sociedade, firmamos um engajamento afetivo centrado na quebra de modelos enrijecidos de produção de conhecimento, formando-nos, também, como corpos-pesquisadores-experimentadores de uma saúde mental antimanicomial e de novos modos de aprender, cuidar e viver.
