---
author: 
  - name: Carolina Silveira Leitão Melo
    orcid: 0000-0002-9397-5098
    email: leitaoscarolina@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará    
  - name: Viktoria Braga Leite
    orcid: 0000-0003-4139-9161
    email: viktorialeite1010@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Julia Mesquita Lopes
    orcid: 0009-0006-0616-1798
    email: juliamesquita_lopes@hotmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Maria Lídia de Farias Araújo
    orcid: 0000-0002-5911-9327
    email: lidiadoisdo4@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Dária Maria Barbosa Dedê
    orcid: 0009-0005-6962-1694
    email: dariadede2110@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Ana Laís Carvalho de Sousa
    orcid: 0000-0002-7300-0402
    email: analaisc1@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Renata Guimarães de Carvalho
    orcid: 0000-0002-3592-7709
    email: renatagui.carvalho@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
language: 
  title-block-author-plural: "Autoras"
filters:
  - section-bibliographies
bibliography: melo_assessoria.bib
reference-section-title: Referências
---

# Grupo reflexão sobre saúde mental no trabalho: um relato de experiência em uma organização na área de serviços públicos

## Introdução

O contexto da pandemia da Covid-19 trouxe inúmeros desafios e incertezas que afetaram a saúde física e mental da população em geral. Os ambientes de trabalho foram impactados e trabalhadores passaram por processos de adaptação de suas funções – tanto no modo remoto quanto no presencial –, vivenciando uma nova rotina que envolvia o isolamento ou a exposição a situações de risco de contaminação [@antunes_fischer_2020; @helioterio2020].

Guilland et al. [-@guilland2022] afirmam, a partir de um estudo realizado em 2021, que os grupos que apresentaram maior risco de desenvolver sintomas de ansiedade e depressão foram os trabalhadores da linha de frente, as mulheres, os indivíduos que, mesmo não estando na linha de frente, mantiveram contato com pessoas diagnosticadas ou com suspeitas de ter contraído Covid-19 e os trabalhadores que não estavam em isolamento total. Nesse último caso, os níveis de sofrimento psicológico foram acentuados pelo medo de contaminação pessoal e familiar, principalmente em se tratando de profissionais que necessitavam continuar com o desempenho de suas atividades presencialmente.

Diante disso, aplica-se a esse contexto o campo de estudos e intervenções em Saúde Mental Relacionada ao Trabalho (SMRT), o qual pressupõe que o processo saúde-doença é impactado por determinantes sociais e que as dimensões físicas e mentais do sujeito são indissociáveis. Nesse sentido, os estudos sobre saúde e desgaste mental devem articular aspectos macrossociais, como processos de transformação laboral, organizacional, produtiva e tecnológica, e microssociais, como especificidades da situação de trabalho e trajetória de vida do trabalhador, para compreender a contribuição laboral tanto para o fortalecimento da saúde, quanto para a intensificação do sofrimento e a determinação de quadros de transtornos mentais [@seligmann2011trabalho]. Os transtornos mentais e comportamentais relacionados ao trabalho expressam processos de adoecimento “determinados pelos lugares, tempo e ações do trabalho” [@jardim2010diagnostico, p. 50], não emergindo de fatores isolados, mas de contextos laborais patogênicos capazes de gerar ou contribuir para o surgimento de sintomas psicopatológicos.

Nesse sentido, o Laboratório de Estudos sobre Subjetividade e Saúde no Trabalho (LESSAT) da Universidade Federal do Ceará/Campus Sobral propôs-se a efetivar ações com foco na promoção da saúde mental entre trabalhadores, no contexto da pandemia, como modo de prevenir adoecimentos. Assim, no final de 2021, recebeu e acolheu a demanda de realização de um grupo sobre saúde mental e trabalho com funcionários que atuavam em uma organização concessionária de serviços públicos na cidade de Sobral (CE). A organização demandante era privada e operava como uma central de serviços ao cidadão, com atendimento ao público e elevado fluxo de pessoas em suas instalações. Devido ao caráter essencial de prestação de serviços da instituição, os trabalhadores do atendimento não ficaram em isolamento social durante a segunda onda da Covid-19, no início de 2021.

No final de 2021, após um ano do retorno presencial de suas atividades, os gestores da empresa procuraram o LESSAT trazendo relatos de absenteísmo de funcionários, demandas relacionadas aos indicadores organizacionais e necessidade de criação de um grupo de apoio psicológico presencial que abordasse temas em saúde mental. Foi relatada, ainda, a existência de casos de contaminação e de perda de parentes próximos em decorrência do novo coronavírus, indicando que esses funcionários faziam parte do grupo de trabalhadores mais afetados em relação à saúde mental na pandemia. 

O laboratório, diante disso, por meio das informações coletadas, elaborou a proposta de realização de um “Grupo-reflexão sobre saúde mental e trabalho” [@silva_bernardo_2018] com o intuito de desenvolver um espaço de reflexão, acolhimento e diálogo sobre estratégias de cuidado e autocuidado em saúde mental, de caráter não psicoterapêutico, no qual as experiências dos trabalhadores pudessem ser compartilhadas. Essa proposta foi aceita pelos gestores da organização em reunião realizada no início do ano de 2022, definindo-se o cronograma preliminar para o início das ações do projeto no mês de março do mesmo ano.

Dessa forma, este capítulo consiste no relato de experiência referente a esta ação de intervenção psicossocial, caracterizada como uma assessoria enquanto produto técnico em psicologia, e tem, como objetivo, descrever e refletir sobre a construção e efetivação de um grupo em saúde mental no trabalho no âmbito de uma organização na área de serviços públicos.

## Caminho metodológico

No caminho metodológico de construção desta ação de assessoria, buscou-se compreender a intervenção psicossocial como um processo que tem início na análise de demanda, na definição de objetivos e no planejamento de atividades; que passa, depois, à execução propriamente dita; e que, ao final, avalia os resultados obtidos e sugere encaminhamentos para as próximas ações. Esse ciclo é flexível, dialógico e passível de mudanças diante das necessidades do público em foco [@neiva2010intervencao].

O LESSAT, tendo como um dos seus objetivos principais o estudo e a intervenção em saúde e subjetividade em contextos de trabalho, partilha da visão de que os trabalhadores são protagonistas de sua prática cotidiana. Portanto, a escolha da ferramenta de intervenção, o grupo-reflexão, vem alinhada a esse entendimento uma vez que o grupo pode proporcionar vivências que facilitem a atitude de cooperação e a adoção de postura ativa diante da situação laboral vivida, bem como apontar para a construção de estratégias individuais e coletivas no sentido de melhorar a qualidade de vida desses indivíduos [@silva_bernardo_2018].

Seguindo essas premissas e entendendo que os trabalhadores são protagonistas de sua atividade laboral [@oddone2020ambiente], a construção do grupo aconteceu de forma compartilhada entre integrantes do laboratório e participantes. Inicialmente, foram alinhados seis encontros com a gestão, de março a agosto de 2022, mas, por solicitação dos participantes, o projeto se estendeu por mais um mês, totalizando sete encontros (a conclusão ocorreu somente em setembro do mesmo ano). Eles aconteceram em salas adequadas, localizadas na própria empresa, e tiveram uma periodicidade mensal, com duração de duas horas em média (embora, em algumas situações, este tempo tenha sido ultrapassado).

Como estratégias metodológicas, foram utilizadas rodas de conversa, dinâmicas, materialidades mediadoras, vídeos, notícias e práticas de Atenção Plena (Mindfulness). Os encontros aconteciam sempre com três integrantes do laboratório, dentre os quais uma facilitadora principal, que esteve presente ao longo de todo o funcionamento do grupo, e duas facilitadoras auxiliares, que variavam a cada encontro. Um novo planejamento acontecia, de forma gradual, após cada uma das reuniões, respeitando o movimento e as necessidades apontadas pelos participantes.

Como forma de registro das ações, foram utilizados diários de campo e fotografias (com a devida autorização dos integrantes). Após cada encontro, as experiências e percepções eram registradas a fim de se ter um posterior objeto a analisar, tendo em vista as informações e as impressões pessoais dos facilitadores, bem como as relações estabelecidas em campo, entre outros aspectos que poderiam enriquecer o processo de construção do grupo [@silva_bernardo_2018].

Além disso, nas reuniões semanais do LESSAT, que aconteciam após cada encontro, também foram realizadas discussões que contribuíram para o planejamento, a continuidade e o registro das atividades.

## Resultados

Após as reuniões com os gestores para prospecção da demanda, foi realizada a visita de um integrante do LESSAT à empresa para fazer o primeiro contato com os trabalhadores, apresentar o laboratório, os objetivos e a proposta do grupo reflexão. Esse momento aconteceu na reunião de alinhamento da equipe, que ocorria diariamente ao final do expediente.

Após essa visita, encaminhou-se à gestão da empresa um formulário virtual de interesse contendo campos a serem preenchidos com informações gerais (nome, idade, e-mail, estado civil, escolaridade, cargo e tempo de trabalho), bem como orientações sobre a metodologia do grupo (esclarecendo não se tratar de um grupo psicoterapêutico), além de perguntas que contribuíram com o formato e as temáticas a serem abordadas, como: “por que o interesse em participar do grupo?”; “quais as expectativas?”; “que temas gostaria que fossem abordados?”; “quais tipos de cuidados em saúde mental busca ou já buscou?”.

Este instrumento confirmou a percepção da empresa em relação aos desdobramentos da pandemia quanto à saúde mental, sendo este assunto apontado pelos trabalhadores como um dos principais temas de interesse, juntamente com a sensação de esgotamento. Fatores como estresse, equilíbrio mental, estereótipos, ansiedade e depressão foram trazidos por eles, assim como a expectativa de dispor de um espaço para expressar suas emoções e percepções de maneira mais aberta e coletiva. A necessidade de partilha esteve presente em todos os encontros, portanto buscou-se possibilitar o contato com os temas de forma mais fluida, respeitando os interesses do grupo.

A princípio, o grupo foi constituído por 15 participantes, considerando o funcionamento no horário de expediente, a necessidade de os participantes deixarem o posto de trabalho e a impossibilidade de setores fecharem por completo. O critério de escolha dos participantes foi decidido pela empresa, que ficou responsável por mapear os interessados conforme o seu setor, sendo selecionados neste processo atendentes, parceiros de empresas que atuavam no consórcio e integrantes da equipe de bem-estar.

Inicialmente, as 15 vagas foram preenchidas, porém, no decorrer do processo, alguns integrantes deixaram a instituição, e o grupo finalizou com 11 integrantes – um do sexo masculino e 10 do sexo feminino. Delimitou-se um formato de grupo fechado, sem possibilidade de entrada de novos membros devido ao caráter de continuidade das ações. Em vista disso, frequências de presença foram colhidas pelo setor de gestão de pessoas durante todos os encontros.

No primeiro encontro, os participantes foram recepcionados através de uma prática de atenção plena com estimulação dos cinco sentidos. O objetivo era realizar um movimento de atenção para o momento presente, proporcionando ao indivíduo desconexão do ambiente de trabalho, que é bastante agitado, e maior participação nas atividades que seriam propostas. A sala utilizada tinha um caráter multifuncional, permitindo à equipe realizar diariamente diferentes atividades. A prática de mindfulness, cujo significado literal é atenção plena, foi uma forma de fazer com que esse espaço adquirisse uma conexão com as atividades que estavam sendo iniciadas, tirando a equipe de um “modo automático” de comportamento.

As facilitadoras foram apresentadas, e foi feita a exposição dos objetivos do grupo, do período de realização, das datas e dos horários. Posteriormente, foi realizada uma dinâmica na qual foram divididas cinco equipes que deveriam se apresentar e encontrar algo em comum de que gostassem no ambiente de trabalho, com o intuito de estimular a partilha e a fala no ambiente grupal e de abrir espaço para as expectativas dos participantes em relação aos encontros. Foi apresentada a temática da saúde mental no trabalho, utilizando-se para isso dados e estudos sobre o tema para sensibilizá-los sobre a sua importância em futuras reflexões. Como apresentado por eles no formulário inicial, a necessidade de falar se apresentou como uma demanda importante, de modo que algumas das ações planejadas não se concretizaram, pois a equipe do laboratório priorizou esse direcionamento.

No segundo encontro, os participantes foram novamente recepcionados por meio de atividades de atenção plena. A sala estava parcialmente iluminada, com fundo musical sereno, e as cadeiras foram dispostas em círculo com pedaços de plástico bolha em cima. No centro dela, foi preparado um “tapete” com esse mesmo material, e os participantes eram convidados a retirar os sapatos e passar sobre ele. Esse momento foi pensado para auxiliá-los a desacelerar a partir de um ambiente relaxante e acolhedor.

Observou-se que eles já estavam mais atentos aos estímulos da sala (cheiro, sons, imagens), visto que, no primeiro encontro, se perceberam agindo no modo automático e tiveram dificuldade de observar de forma mais sensível os detalhes de seu entorno. Alguns demonstraram insegurança em tirar os sapatos e aproveitar a experiência, precisando ser estimulados em algumas situações – apesar de haver uma placa fazendo esse convite. Esses comportamentos foram posteriormente discutidos no coletivo.

A temática principal do encontro foi o burnout e o esgotamento no ambiente de trabalho, visto que esses elementos tiveram grande prevalência no formulário e na partilha do primeiro encontro. Para tanto, organizou-se uma roda de conversa, e, no centro da sala, foram dispostas reportagens atuais sobre esse assunto. A partir disso, diversas situações pessoais foram relatadas, sendo possível notar uma emergente demanda de fala (fator que influenciou na gestão do tempo para a realização do que tinha sido planejado).

Ao final do encontro, foi proposta a construção do contrato de convivência (pendente do encontro anterior), a partir de princípios que os participantes consideraram necessários para o bom funcionamento do grupo, além do estabelecimento de regras que guiariam o grupo durante todo o período de realização das atividades. Por fim, concluiu-se o encontro escutando a percepção deles sobre a temática abordada, definindo-se a próxima data e o tema do mês seguinte.

Após os dois primeiros encontros, ficou alinhada nas reuniões de planejamento das ações da equipe do LESSAT a necessidade de se oferecer menos atividades e dar mais abertura para a partilha, além de permitir aos participantes sugerirem a temática a partir de seus interesses e suas reflexões nos encontros. Em cada um deles, era disponibilizado um lanche, que ficava exposto e poderia ser acessado segundo a necessidade de cada trabalhador. Entretanto, percebeu-se que eles preferiam que esse momento acontecesse de forma coletiva, então, o lanche também passou a fazer parte do planejamento. Apesar de trabalharem diariamente juntos, eles afirmaram ter poucos momentos de interação, portanto a prática foi incluída considerando esse movimento.

O terceiro encontro teve como temática “colorir a vida” e envolveu uma atividade de recepção na qual os participantes eram convidados a pintar algo sobre a sua rotina. Para isso, a sala foi preparada com almofadas e colchonetes no chão em formato de círculo, e no centro dele estavam dispostas cartolinas, tintas coloridas, pincéis e um convite para pintar. No telão passavam músicas calmas com explosões de cores, sendo apresentado o vídeo "Escolhas" – que propunha uma reflexão sobre a rotina diária de trabalho e o autocuidado através da metáfora de colorir o dia com ações simples.

Posteriormente, os participantes foram convidados, via perguntas geradoras, a refletir e listar ações de autocuidado individuais, que envolvessem desde atividades que eles já praticavam, até ações que gostariam de fazer, mas não o faziam, para que discriminassem os obstáculos que os estavam impedindo. Ao finalizar a lista, quem se sentisse à vontade poderia partilhar as impressões da atividade individual com o grupo, fomentando a reflexão coletiva, e relacioná-las com os conceitos de autocuidado previamente apresentados.

Por fim, foi pedido que cada participante escolhesse uma atividade de autocuidado que deveria ser executada até o próximo encontro, com o objetivo de incentivar a utilização dos conceitos fora do grupo, criar um elo entre os encontros e, potencialmente, desenvolver atividades geradoras de sentido para cada sujeito. Esse encontro teve uma característica mais introspectiva tanto pela atividade como pelo próprio coletivo (que apresentou uma maior necessidade de silêncio).

O quarto encontro se diferenciou por ocorrer em outro espaço dentro da empresa: a sala de descanso – diariamente utilizada pelos participantes no intervalo entre os turnos de trabalho. Os trabalhadores foram recebidos com chocolates e frases sobre autocuidado, no centro da sala havia colheres com brigadeiro caseiro para que eles pudessem degustar.

Realizou-se uma prática de atenção plena com o alimento, refletindo-se sobre a necessidade de estar presente nas atividades simples do dia a dia e sobre a relação entre a presença e o autocuidado. Muitos compartilharam que já não sentiam o sabor do alimento quando comiam e que, mesmo quando não estavam no trabalho, se alimentavam de forma rápida, como se tivessem pouco tempo para aproveitar. Assim, parar para saborear o alimento trouxe essa percepção de desconexão de atividades do cotidiano.

Como o lanche foi incluído na programação, esse momento foi usado para que eles compartilhassem sobre as atividades de autocuidado que cada um havia escolhido para pôr em prática durante o intervalo dos encontros. Alguns partilharam ter conseguido e outros não, apresentando de forma resumida o processo e sendo acolhidos pelos demais integrantes em ambas as situações.

Como no terceiro encontro se percebeu uma maior introspecção do grupo, propôs-se uma dinâmica mais movimentada. Por acontecer no mês de junho, utilizou-se a dinâmica da batata quente, que faz alusão às festas que ocorrem no Nordeste nesse período. Ao som de músicas de quadrilha, uma caixa era passada na roda, e, ao parar, aquele que estava com ela na mão deveria abrir e ler a pergunta. Dentro da caixa estavam perguntas sobre autocuidado, visando aprofundar as discussões que vinham sendo feitas nos últimos encontros, além de apresentar conceitos contidos em uma cartilha elaborada pelo LESSAT.

O quinto encontro também aconteceu na sala de descanso por solicitação dos próprios trabalhadores, e a dinâmica inicial consistiu em oferecer um momento relaxante e introspectivo. Foram colocados na sala recipientes com água morna e um escalda pés, os participantes eram convidados a tirar os calçados e descansar os pés na água. A partir disso, foi realizada uma reflexão sobre as próprias formas de autocuidado dos participantes, que nem sempre exigem um valor elevado de investimento financeiro (uma vez que isso foi um fator apresentado como obstáculo para alguns nas atividades escolhidas no encontro passado).

O tema do encontro foi autocompaixão, a necessidade de acolher a si e de respeitar os próprios limites. Para iniciar essa reflexão, foi facilitada uma prática de mindfulness [@neff2017autocompaixao] chamada toque calmante, na qual o acolhimento é realizado através do próprio toque. Houve a partilha do modo como cada um se sentiu durante a prática, as facilidades e limitações relacionadas ao toque de forma respeitosa e ao acolhimento da própria agitação. Cada participante foi relacionando situações da sua vida com o respeito percebido no próprio grupo com relação ao acolhimento e à segurança que sentiam ao trazer reflexões sobre o cuidar-se. Ao final, foi proposta uma atividade que consistia na escrita de uma carta para si, que deveria ser feita naquela semana e relida na véspera do próximo encontro.

Entre o quinto e sexto encontro, houve um período maior de intervalo. Conforme a proposta, o sexto encontro deveria ser o último, mas, como afirmado anteriormente, a proposta foi estendida. A sala foi preparada de modo intimista com velas e luz baixa, e foi projetada na parede a pergunta “já olhou para você hoje?”, enquanto era reproduzida a música “Paciência”, do cantor e compositor Lenine.

O objetivo da prática foi buscar um olhar mais profundo de si, do outro, das limitações e dos detalhes de ser na sociedade atual. A dinâmica de observação do olhar do outro e das sensações que podem decorrer dessa experiência possibilitou essa reconexão enquanto grupo devido a esse período maior sem reuniões. Foi partilhado um pouco do desconforto de observar e ser observado e de sustentar um olhar mesmo com alguém que se encontrava diariamente (trazendo essa percepção de afastamento, mesmo estando fisicamente muito próximos).

A temática principal foi a necessidade do descanso, do ócio, das pausas e do lazer. Para tanto, foi realizada uma roda de conversa a partir da exibição do episódio de uma série que abordava o cansaço crônico na sociedade contemporânea. A roda foi guiada por questões geradoras que estavam expostas no centro da sala: “o tempo livre precisa render?”; “vida ativa ou ser multitarefa”; “necessidade constante de otimização do tempo”; “o meu lazer é diversão ou obrigação?”; “sinto-me culpado pelo ócio?” “sensação recorrente de ‘não vai dar tempo’”; “o celular é descanso ou prisão?”; “metas de produtividade”; “sucesso ou autoexploração?”.

O sétimo e último encontro aconteceu na sala de descanso e teve como temática o encerramento e a avaliação das ações durante o projeto. Os participantes foram recebidos à meia luz e com som ambiente, com o lanche já servido e com fotos impressas de registros de todos os encontros expostas nas poltronas (escolhidas conforme a preferência de cada um), as quais que trouxeram a lembrança dos acontecimentos vividos, daqueles que não continuaram no grupo e das reflexões construídas. Enquanto o lanche acontecia, cada um compartilhava o porquê de ter escolhido aquela foto com o grupo e a sua principal lembrança das atividades.

Nesse contexto, a atividade final realizada foi denominada “guardar num potinho”. Nela, foram disponibilizados potes com tarjetas que estavam disponíveis na sala, papéis coloridos e canetas, nos quais cada um deveria escrever o que levaria daquela experiência, ou seja, o que guardaria num potinho para resgatar em um momento posterior. Eles deveriam dar um nome para o seu potinho, escrever seus aprendizados e compartilhá-los com o grupo. Muitos trouxeram o autocuidado, o respeito consigo, a necessidade de estar presente nas atividades e de sair de um padrão automático de comportamentos. Afirmaram o quanto os encontros foram evoluindo no decorrer do tempo e o modo como se sentiram acolhidos e seguros para partilhar sobre si.

## Discussão

A partir do percurso histórico da humanidade, pode-se considerar que o trabalho tem sido um dos principais responsáveis pelos modos de produção da existência social, uma vez que possibilita ao sujeito constituir identidade, vínculos e suporte; ter um propósito; obter status e prestígio, além de ser fonte de renda e subsistência. Dessa forma, evidencia-se a importância e a centralidade do trabalho, bem como seu potencial para repercutir diretamente sobre a condição de saúde dos trabalhadores – positiva ou negativamente [@alencar_merlo_2018; @seligmann2011trabalho].

Alguns aspectos relevantes percebidos nos encontros do grupo-reflexão demonstraram que havia mobilização dos participantes em relação aos temas de saúde mental e aplicação de ações cotidianas de autocuidado. Entretanto, a falta de tempo e de recursos eram apontados como impeditivos para a obtenção de uma melhor qualidade de vida. A respeito disso, Dejours e Abdoucheli (1994) evidenciam que trabalhadores podem não só reconstruir a lógica das pressões que os fazem sofrer, como também podem desenvolver estratégias defensivas para lidar com efeitos desestabilizadores e patogênicos relacionados ao trabalho, contribuindo para a manutenção da situação atual vivida. Apesar de ainda hoje ser discutida a dificuldade de estabelecimento do nexo causal entre trabalho e saúde mental, Souza e Bernardo [-@souza_bernardo_2019] apontam que existem muitas evidências da relação entre as expressões do sofrimento e a organização do trabalho enquanto fatores que podem afetar significativamente a saúde dos trabalhadores.

Cabe ressaltar que houve, por vezes, interrupções durante os encontros por conta de demandas de trabalho (como quando algum participante era solicitado a se retirar por instantes), trazendo prejuízos como a quebra de raciocínio durante a reflexão das temáticas abordadas. Houve também desistência de alguns trabalhadores, pois recebiam demandas durante os encontros, mesmo tendo sido acordado com a empresa que eles deveriam participar plenamente do grupo, sem interrupção. Esses eventos relacionam-se a um modelo atual de trabalho cada vez mais direcionado à produtividade e à manutenção de patamares elevados de desempenho, o que pode gerar intensificação laboral e sensação de esgotamento [@antunes_praun_2015].

Nesse sentido, embora o contexto pandêmico tenha sido o propulsor para que a organização buscasse meios de contemplar as demandas relacionadas à saúde mental de seus funcionários, os participantes não deram uma ênfase especial à temática da pandemia no decorrer dos encontros. Compreende-se, portanto, que a pandemia agravou uma série de questões sociais, sanitárias e econômicas, bem como trouxe visibilidade a necessidades até então negligenciadas socialmente (como a saúde mental) que remontam a um período anterior [@schmidt_crepaldi2020; @souza_bernardo_2019]. Isso porque dados anteriores ao período da pandemia indicavam ser cada vez mais comum casos de depressão, tentativas de suicídio, manifestações de ansiedade, uso abusivo de drogas lícitas e ilícitas, estresse, esgotamento emocional, entre outras manifestações de sofrimento, figurando como uma das maiores causas de afastamentos do trabalho no país [@souza_bernardo_2019].

Um contraponto à lógica laboral hegemônica, que exalta a competitividade e a produtividade, é o fortalecimento de vínculo entre os trabalhadores e a intermediação de apoio social, constituindo-se positivamente como um fator protetivo da saúde associado ao bem-estar [@paschoal_torres_porto_2010]. O apoio dos colegas ou a percepção de um possível suporte podem contribuir para redução do absenteísmo, melhor desempenho, maior satisfação com o trabalho, maior criatividade e inovação, menor intenção de sair do emprego, entre outros [@oliveira_gomide2018].  Assim, o estabelecimento de um espaço e de um tempo em que os trabalhadores tiveram a possibilidade de interagir de um modo mais pessoal e construir laços – como na experiência do lanche coletivo, caracterizou-se como um momento importante de conexão e percepção de suporte social no grupo.

A experiência gerou também vínculo entre participantes e facilitadoras, estabelecido a partir das informações compartilhadas (muitas delas para além do contexto de trabalho). A efetivação de uma estratégia metodológica que privilegiou o compartilhamento de afetos e a interação coletiva foi fundamental para a obtenção desse resultado. O uso de recursos expressivos variados, o resgate de temas levantados no encontro anterior a fim de estabelecer uma relação de continuidade e fluidez do processo do grupo, e o feedback por parte dos trabalhadores a respeito de como se sentiram e o que pensaram durante o período que antecedeu o encontro, todos esses elementos foram modos de permitir ao participante um contato mais amplo consigo e com os outros, estabelecendo novas possibilidades de relações no ambiente laboral.

Destaca-se, ainda, como fato positivo, o intuito dos gestores da organização em dar continuidade ao projeto com a formação de novos grupos de participantes, indicando o reconhecimento da relevância da efetivação de ações que favoreçam o bem-estar e a saúde mental dos trabalhadores e o propósito de ofertar essas ações no próprio ambiente e no horário de trabalho.

Diante da realização do grupo, foi possível perceber a importância da promoção de espaços e de discussões que fomentem a reflexão acerca dos temas que foram abordados e que compõem o campo de interação entre saúde mental e trabalho. Ressalta-se o fortalecimento dos vínculos, a tomada de consciência sobre padrões de comportamentos nocivos, a importância do autocuidado e da autocompaixão como estratégias válidas para lidar com as pressões fomentadas pelas condições e organização do trabalho. Como limitação dessa intervenção, destaca-se a dificuldade de refletir a relação entre saúde mental e trabalho para além do grupo, o que poderia redundar em um processo de transformação e cuidado mais amplo, envolvendo condições de trabalho que contribuem para o sofrimento e adoecimento de trabalhadores.
