---
author: 
  - name: Juliana Vieira Sampaio
    orcid: 0000-0001-5770-244X
    email: julianasampaio@sobral.ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará    
  - name: Ariadsa Mesquita Aragão
    orcid: 0009-0001-8800-7826
    email: ariadsamesquita@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Luiza Barbara Cunha Freire
    orcid: 0009-0009-5242-1361
    email: luizabcfreire@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Adrielle Jennifer Candido Coelho
    orcid: 0009-0008-7512-2148
    email: adriellecoelho88@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Brígida Sousa de Oliveira
    orcid: 0009-0001-8960-3945
    email: brigidasousa@alu.ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
  - name: Carla Cecilia Mendes Oliveira
    orcid: 0009-0001-4055-4767
    email: carlacecilia542@gmail.com
    affiliations: 
      - name: Universidade Federal do Ceará
language: 
  title-block-author-plural: "Autoras"
filters:
  - section-bibliographies
bibliography: sampaio_assessoria.bib
reference-section-title: Referências
---

# Assessoria sobre direito e saúde sexual e reprodutiva com mulheres em dispositivos da assistência social

## Introdução

O Núcleo de Estudos e Extensão sobre Subjetivação e Sexualidade (SuSex) está vinculado ao curso de Psicologia da Universidade Federal do Ceará, campus Sobral. O SuSex tem como objetivo geral promover a equidade de gênero e o respeito à diversidade sexual. Buscamos, por meio das nossas ações, produzir resistência contra os processos de homogeneização e padronização dos modos de viver. Nesse sentido, este estudo apresenta o relato da experiência de produção e desenvolvimento de um serviço técnico de assessoria sobre direito e saúde sexual e reprodutiva em equipamentos públicos da rede de assistência social.

O serviço técnico envolve a realização de ações junto à sociedade e às instituições, particularmente a assessoria é o ato de “assessorar, ou seja, é o ato de ajudar, assistir, auxiliar, coadjuvar ou colaborar com determinado processo. Na assessoria os problemas são identificados e as soluções implantadas com a participação direta do assessor interferindo nos processos” [@bastos2016consideracoes, seção EIXO 3].

A assessoria envolveu a produção de quatro oficinas voltadas para a promoção do direito à saúde sexual e reprodutiva, especificamente com mulheres cis[^sampaio_assessoria-1], em equipamentos da assistência social, sendo duas no Centro de Referência de Assistência Social (CRAS) e duas no Centro de Referência Especializado de Assistência Social (CREAS), durante o ano de 2022. A história dos direitos reprodutivos é recente, e a dos direitos sexuais mais ainda, estes tiveram o movimento feminista e LGBTQI, respectivamente, como atores fundamentais na sua configuração e produção. Assim, a partir dos direitos sexuais e reprodutivos, uma postura política e ética foi inserida no debate sobre a reprodução e a sexualidade [@Rohden2011]. Esses dois movimentos sociais têm em comum o questionamento das categorias universais, das verdades científicas, da naturalização do sexo e da normatização da sexualidade, fazendo, assim, um contraponto com a perspectiva biologizante e farmacológica do saber biomédico.

[^sampaio_assessoria-1]: Utilizamos os termos mulher ou mulheres, de modo geral, ao longo do texto para fazer referência a mulheres cisgêneras, isto é, mulheres cuja identidade de gênero corresponde ao sexo nomeado no nascimento.

Foi a partir da desconstrução da maternidade como obrigação, da luta pelo direito ao uso de métodos contraceptivos e ao aborto que feministas de várias partes do mundo começaram a construir suas pautas sobre os direitos reprodutivos. Esses buscam articular as necessidades reprodutivas não só à saúde, mas também aos direitos humanos [@Brasil2013]. A reprodução deixa de ser discutida apenas em seu aspecto demográfico, cuja exclusividade recai sobre a mulher e o seu corpo, e passa a albergar questões éticas, sociais e culturais, que são colocadas em pauta [@Correa1996]. A saúde reprodutiva faz parte dos direitos reprodutivos e defende a autonomia e o direito de escolha sobre: se, quando e quantas vezes se pretende reproduzir.

Enquanto isso, os direitos sexuais implicam o respeito aos diferentes tipos de expressão sexual, a autonomia no uso do próprio corpo e a igualdade sexual. A noção de saúde sexual coloca em pauta outros elementos que não dizem respeito à saúde reprodutiva, como a expressão da sexualidade sem coerção, violência, discriminação e risco de contrair infecções sexualmente transmissíveis (IST), assim como respeito mútuo, prazer, segurança, autoestima e liberdade de expressão da sexualidade [@Brasil2013].

Em 2005, foi lançada, no Brasil, a Política Nacional de Direitos Sexuais e de Direitos Reprodutivos, resultado da articulação entre os Ministérios da Saúde, Educação, Justiça e Desenvolvimento Social e Combate à Fome; e as Secretarias de Políticas para as Mulheres, de Políticas de Promoção da Igualdade Racial e de Direitos Humanos. Essa e outras estratégias defendem o respeito à autonomia, a maximização dos benefícios e minimização dos prejuízos, a equidade e o respeito à diversidade cultural, étnica, sexual, religiosa, etc. Perspectivas conservadoras e moralizantes da sexualidade têm se oposto às mudanças impulsionadas pelos movimentos sociais, dessa maneira muitos debates que têm ocorrido na esfera da política e nas lutas pelos direitos sexuais e reprodutivos parecem não chegar ou são barrados [@Rohden2014].

Enquanto os saberes biomédico e farmacológico preconizam o discurso médico como o único verdadeiro e o tratamento medicamentoso como o mais eficiente, o campo do direito sexual e reprodutivo defende que cada um deve decidir sobre os usos, sexual, reprodutivo ou de outro tipo, que dá a seus corpos. Assim, vamos descrever e analisar o processo de criação de práticas de cuidado alinhadas aos direitos sexuais e reprodutivos na assistência social, guiados por quatro princípios éticos: integridade da pessoa, individualidade, igualdade e respeito pela diversidade [@Rohden2014].

## Como fazemos

A ação de assessoria foi desenvolvida em parceria com a Secretaria de Direitos Humanos e Assistência Social da cidade de Sobral, Ceará, nos meses de outubro e novembro de 2022. Foram realizadas 4 oficinas, sendo duas no Centro de Referência de Assistência Social (CRAS) e as outras duas no Centro de Referência Especializado de Assistência Social (CREAS). O público alvo das oficinas no CRAS foram mulheres atendidas no Serviço de Proteção e Atendimento Integral à Família (PAIF) e no CREAS, mães de jovens que estavam cumprindo medida socioeducativa em meio aberto. No total participaram cerca de 30 mulheres cis, todas em situação de pobreza, a maioria delas pretas e pardas.

Foram realizadas, nos equipamentos da assistência social da cidade, oficinas sobre saúde sexual e reprodutiva com caráter educativo, buscando a construção de novos modos de viver mais saudáveis pautados no cuidado coletivo a partir da circulação dialogada do conhecimento científico. As oficinas utilizaram como material: preservativo interno e externo (obtidos a partir da parceria com o Centro de Referência em Infectologia de Sobral – CRIS), folha de papel e lápis de cor. As atividades foram estruturadas a partir da seguinte organização:

As mulheres eram divididas em 2 grupos, cada um destes contava com pelo menos duas extensionistas, uma responsável por facilitar e mediar a oficina, e outra por observar e registrar no diário de campo a atividade. A atividade era iniciada com uma dinâmica de apresentação em que as mulheres desenhavam ou escreviam o que mais gostavam de fazer quando eram adolescentes e/ou antes de serem mães, enquanto isso eram reproduzidas músicas que elas informaram que gostavam de ouvir. Depois, elas compartilhavam seus desenhos, falando o seu nome e explicando o que desenharam e escreveram.

Na sequência, eram apresentados cartões com os seguintes temas, que seriam abordados na oficina:

a)  Infecção Sexualmente Transmissível (IST),
b)  contracepção,
c)  maternidade,
d)  Outubro Rosa,
e)  atividade prática representada pela imagem de um “foguinho”.

Em seguida, elas sorteavam cada um dos temas, revelando as cartas para realizar a atividade. Descrevemos abaixo as diferentes dinâmicas utilizadas a partir de cada tema citado:

a)  IST – dinâmica do “pega ou não pega” em que se retiram de um envelope algumas possíveis situações de infecção por IST, e as participantes respondem “se pega ou não pega” IST nos casos descritos. Os casos eram:

    -   Não se pega pela água da piscina; pelo suor; pelo assento do banheiro; pela toalha; pelo sabonete; pelos talheres, pelos copos, pelos pratos e pelas xícaras reutilizadas e pela picada de mosquito;
    -   Pega pelo sexo oral; pela agulha ou seringa já utilizada na hora de aplicar droga; pela agulha reutilizada para fazer tatuagem e piercing; pelos instrumentos reutilizados de dentistas; também foi elencada a possibilidade de contágio em momentos como durante a gravidez; hora do parto; na amamentação.

b)  Contracepção – para trabalhar o tema, foi lido um caso fictício sobre uma relação sexual em que o preservativo estourou. Dessa forma, é possível que se aborde a prevenção de emergência e se informe como acessar aos contraceptivos disponíveis no Sistema Único de Saúde (SUS), bem como a maneira de agir em casos como esse.

c)  Maternidade – o tema foi abordado a partir de perguntas disparadoras, como:

    -   “Quando uma mulher se torna mãe, o que a sociedade espera dela?”;

    -   “As expectativas sobre como as mães devem ser hoje em dia são iguais ou diferentes das do passado?”;

    -   “As expectativas sobre o que é ser mãe são diferentes do que se espera sobre o que é ser pai? Como?”.

d)  Outubro Rosa – Tendo como demanda do CRAS e CREAS, devido à ação programada para o mês de outubro, acrescentamos o tema “Outubro Rosa”, para discutir a prevenção do câncer de mama. Com essa finalidade, realizamos perguntas para fomentar a discussão sobre cuidado em saúde, por exemplo: 

    -   “Qual a melhor forma de identificar o câncer de mama?”; 

    -   “A partir de que idade é mais comum ter câncer de mama?”; 

    -   “Qual a melhor forma de prevenir o câncer de mama?”.

e)  Foguinho – A atividade prática ilustrada pela carta do Foguinho é utilizada para abordar o uso de preservativo. Se pergunta inicialmente às participantes se estas sabem utilizar o preservativo interno e externo. Em caso negativo, elas são convidadas, caso se sintam à vontade, a mostrar como usar o preservativo, e as extensionistas ajudam a demonstrar o uso correto.

Após todas as cartas serem retiradas, e os temas contemplados e debatidos, o encontro é finalizado com a distribuição de preservativos internos e externos, além de folhetos explicativos sobre cuidados em saúde.

Toda a experiência de assessoria foi registrada por meio de diários de campo produzidos pelas extensionistas. Essa estratégia de registro é pensada a partir do debate sobre observação “no” cotidiano proposto por Spink [-@Spink2007], em que se compreende que somos parte dessa "comunidade e compartilhamos de normas e expectativas que nos permitem pressupor uma compreensão compartilhada dessas interações” (p. 07).

A atividade da oficina busca romper com modelos de intervenção verticalizados, em que as participações se limitam a responder instrumentos. Nessa perspectiva, é colocado no mesmo campo e processo conhecer e fazer [@Passos2009]. Adotamos como base epistemológica para o nosso fazer a perspectiva queer [@Butler2010], o feminismo pós-estrutural [@Haraway2009], com atenção aos aspectos relacionados à interseccionalidade [@Piscitelli2008] e à pós-colonialidade [@castrogomez2005cienciassociais]. Buscamos a produção de conhecimentos e práticas socialmente situados, alinhados com o compromisso social e a justiça ético-político-científica. Nesse sentido, colocamos em questionamento as desigualdades e hierarquias produzidas socialmente a partir dos marcadores sociais da diferença.

## Contracepção: discursos e práticas

Nem sempre as mulheres foram as únicas responsáveis pelo processo reprodutivo ou pela interrupção deste. Em diferentes culturas e tempos históricos, pesquisadores mostram que o aborto e infanticídio eram admitidos e tinham amparo coletivo, não sendo crimes passíveis de punição. Tais práticas, em algumas culturas, eram associadas à coragem materna, que impediam que os seres indesejados fossem condenados à vida [@matos2003delineando]. O aborto, o infanticídio e o abandono de crianças foram práticas comuns durante a Antiguidade e a Idade Média. Enquanto na Antiguidade era o pai quem decidia se aceitaria ou não a criança, na Idade Média tal função passou para a mãe, e, com isto, ela poderia ser inquirida e condenada pela Igreja como pecadora [@vieira1999medicalizacao].

Na modernidade, há uma mudança no modo de perceber o aborto, infanticídio e abandono de crianças, pois passaram a ser associados às mulheres empobrecidas, e não mais aos homem ou mesmo ao casal. As mulheres tornaram-se as principais responsáveis pelo planejamento reprodutivo e, com isto, pela disseminação do uso de métodos contraceptivos como “o coito interrompido, as duchas de água, as esponjas umedecidas com desinfetantes colocadas no fundo da vagina, camisinhas de tripa e de borracha e tabelas de controle” [@matos2003delineando, p. 113]. Desde a antiguidade, diferentes métodos contraceptivos são conhecidos pela humanidade, porém, só a partir do século XX, as técnicas de contracepção passaram a se concentrar no corpo das mulheres [@pedro2003representacoes]. Percebemos que, mesmo antes das pílulas anticoncepcionais e da laqueadura, as mulheres tornaram-se as principais responsáveis pelo controle da natalidade.

No Brasil, o Ministério da Saúde só começou a distribuir métodos contraceptivos na década de 1980, com a implementação do Programa de Assistência Integral à Saúde das Mulheres (PAISM). Antes disso, inicialmente, os materiais distribuídos provinham de doações de outras organizações, inclusive internacionais, como Banco Mundial. Apenas em 2007, o Brasil publicou a Política Nacional de Planejamento Familiar, que prevê distribuição de preservativos e anticoncepcionais, educação sexual e ações na área da saúde reprodutiva.

Durante as oficinas realizadas no CRAS e CREAS, percebemos que os temas que mais mobilizavam as falas das mulheres eram maternidade, contracepção, uso da camisinha interna e externa, e, por isso, vamos focar neste texto na descrição e análise das dinâmicas que envolviam os dois últimos temas, quais sejam, caso fictício e foguinho. Muitas mulheres que participaram das oficinas não sabiam o que significava contracepção e, após a explicação das extensionistas, chegavam à conclusão de que seria sinônimo de não “pegar bucho (barriga)”, termo usado popularmente no Nordeste, em referência à mulher grávida, que é chamada de “buchuda”.

A discussão sobre métodos contraceptivos utilizou, como mediadora, a leitura de um caso fictício de uma jovem que teve uma relação sexual na qual o preservativo estourou. Após a leitura do caso fictício, percebemos que as mulheres demonstravam conhecer diferentes formas de evitar a gravidez, inclusive o “chip” hormonal, mas que poucas conheciam a pílula do dia seguinte. A lógica presente no discurso da maioria das mulheres era a de que a personagem do caso deveria esperar e ver o que aconteceria, se engravidasse, ela deveria prosseguir com a gravidez, pois isso “não era o fim do mundo”.

Percebemos, atualmente, que, para a população mais favorecida economicamente, ter filhos é associado à ideia de gratificação, por isto, os futuros pais e mães devem esperar o momento adequado para procriar, isto é, quando a criança não for mais obstáculo para as realizações pessoais e profissionais, além do imperativo de só ter filhos se puder lhes oferecer as melhores condições possíveis de vida [@altmann2007sexualidade]. Enquanto isso, entre a população empobrecida, ter filhos está geralmente associado à ascensão à vida adulta, que é valorizada, pois ser adulto está relacionado com o mundo do trabalho e a obtenção de renda e independência social e financeira [@altmann2007sexualidade]. Perceber tais aspectos interseccionais é fundamental para desenvolver estratégias eficazes de promoção dos direitos e da saúde sexual e reprodutiva, tendo como referência a realidade concreta de cada grupo de mulheres.

Uma participante mais jovem disse conhecer a pílula do dia seguinte e relatou que sua irmã de 15 anos engravidara na primeira relação sexual devido à falta de comunicação com as outras irmãs, pois estas teriam sugerido o uso desse método após o sexo sem proteção. Outra participante relatou que sua filha era “filha da pílula do dia seguinte”, pois utilizara o método, porém de forma errada, ingerindo dois comprimidos de uma vez, sem esperar o tempo necessário entre as doses. Explicamos na oficina sobre a forma adequada de utilizar a pílula do dia seguinte e sobre a eficiência do método, que, se utilizado de forma correta, evitava a fecundação do óvulo.

O uso e a popularização de informações sobre o uso de métodos contraceptivos seria justamente uma das estratégias para evitar a gravidez não planejada e/ou não desejada, sendo um marco importante para a vida das mulheres em geral, bem como para o movimento feminista, na medida em que as mulheres passariam a escolher se e quando engravidar. Entretanto, a desigualdade de gênero, raça e classe ainda permeia o processo reprodutivo, e, apesar da distribuição de métodos contraceptivos de forma gratuita pelas políticas públicas, isto, de forma isolada, não é capaz de proporcionar a liberdade sexual, os direitos reprodutivos e a autonomia das mulheres. Nesse sentido, é necessário não só garantir o direito sexual e reprodutivo das mulheres, defendido pela Conferência do Cairo (1994), mas também garantir os direitos humanos e a justiça social para as mulheres de minorias étnicas e empobrecidas [@un1995programme].

O discurso sobre ser exclusivamente responsabilidade da mulher a prevenção da gravidez indesejada foi marcante nas oficinas, sendo trazido a partir de falas como “a culpa é tua”, depois de um relato sobre gravidez na adolescência de uma participante, “a mulher só engravida se ela quiser”, “não se preveniu”, “não se cuidou”, “agora tem que arcar com as consequências”, “hoje a mulher só engravida se ela quiser, tem vários métodos de graça”. A gravidez aparece nessas falas como uma espécie de punição às mulheres que possuem uma vida sexual ativa, além de ser uma responsabilidade exclusiva destas. Mesmo usando métodos contraceptivos, caso ocorra a gravidez, ainda é culpa da mulher não ter “se cuidado direito”. Essas falas se juntam com a ideia de que é importante evitar a gravidez, mas que, caso não seja possível, “filho é uma benção de Deus”.

Observamos que a popularização e o aumento da disponibilidade de métodos contraceptivos, para algumas mulheres economicamente favorecidas com maior acesso à informação e aos serviços de saúde, tornaram possível a emergência de novos arranjos familiares e conjugais. Essas mulheres passaram a ter maior liberdade para exercer sua sexualidade de forma mais livre e desassociada do processo reprodutivo, porém, se algo der errado, isto é, se a mulher engravidar, ela será a única culpada, independentemente da sua classe ou raça [@pedro2003representacoes]. Os métodos contraceptivos, ao mesmo tempo que possibilitam à mulher controlar sua reprodução e seu “futuro”, também podem se tornar um instrumento de controle dos corpos destas, com a finalidade de regular as taxas de natalidade e de responsabilizá-las pela reprodução.

Várias mulheres relataram que tiveram a primeira gravidez quando ainda eram menores de idade. Sobre isso, uma delas comenta que, quando perdeu a virgindade, com o pai da sua filha, ela o fez usar dois preservativos por medo de engravidar. Ela continua relatando que, nessa época, pensar e falar sobre sexo sempre remetia ao sentimento de vergonha e que não queria falar com os seus pais sobre esse assunto. As extensionistas advertiram que a utilização de dois preservativos é mais insegura, pois facilita o rompimento destes, ao que a mulher responde que eles fizeram isto por falta de informação, acreditando que os ajudaria a ter um sexo seguro.

É importante destacar a ausência de equidade entre mulheres de diferentes classes e raça. Segundo Perpétuo [@perpetuo2000raca], as mulheres negras iniciam a sua vida sexual e engravidam mais cedo que as mulheres brancas, tendo também mais filhos que estas. As mulheres negras têm acesso precário a métodos contraceptivos, muitas vezes não utilizando nenhum método para prevenir a gravidez e as Infecções Sexualmente Transmissíveis (IST). Essas mulheres também apresentam pouco conhecimento sobre a fisiologia reprodutiva, refletindo em um grande índice de falha quando utilizam contraceptivos.

Tomando como referência as questões que articulam gênero, classe e raça, podemos questionar o modelo instituído, na nossa sociedade, que demarca quem são os sujeitos aptos para serem mães, que idade eles têm e qual a condição econômica e social deles. As convenções sociais instituem que a gravidez só é legítima se for resultado do casamento. Apesar de a função das mulheres na sociedade ainda ser associada à sua atividade reprodutiva, podemos perceber que tal processo foi investido de padrões normativos que orientam quando e quantas vezes as mulheres devem ser mães. Tais regras estão associadas, principalmente, à raça, à renda, ao estado civil das mulheres, e, nas últimas décadas, a idade também tem sido um dos fatores marcantes dessa regulação. Nesse sentido, os direitos sexuais e reprodutivos se articulam com a desigualdade econômica, os interesses políticos, as práticas eugênicas, a geopolítica, as questões territoriais e a desigualdade de gênero [@preciado2008testo].

Podemos perceber nesses relatos que, apesar de a maternidade ter deixado de ser um destino inquestionável para muitas mulheres, especialmente as brancas e economicamente favorecidas, devido à propagação de métodos contraceptivos, este cenário não é realidade para grande parte das mulheres brasileiras, especialmente para as negras e pobres. O aumento do acesso a métodos contraceptivos não se deu de maneira homogênea entre as mulheres, segundo o Ministério da Saúde

> “um dos dados relevantes sobre a questão relacionada à saúde da mulher negra é que esta tem menor acesso aos serviços de saúde de boa qualidade, atenção ginecológica e à assistência obstétrica, seja no pré-natal, seja no parto, seja no puerpério” [@Brasil2013, p.73].

Desse modo, o corpo feminino continua sendo alvo de preocupação e controle das próprias mulheres, seus parceiros, médicos/as e governantes, devido à capacidade reprodutiva. Tal preocupação muitas vezes só se encerra com o uso de técnicas definitivas, como a laqueadura e histerectomia. O processo da laqueadura também afeta de formas diferentes os corpos das mulheres de acordo com a idade, raça e classe social. Em 1986, foi elaborado o suplemento especial da Pesquisa Nacional por Amostra de Domicílios (PNAD), que indicava que os maiores índices de mulheres esterilizadas no Brasil, com idade entre 15 e 54 anos, encontravam-se nos estados do Maranhão (75,4%), de Góias (71,3%) e de Pernambuco (61,4%), indicando a prevalência da esterilização cirúrgica na região Nordeste, onde a população negra é majoritária [@roland1991saude].

A vasectomia poderia ser uma outra opção definitiva para o controle da natalidade, mas, apesar de ser um método de esterilização mais simples, se comparado com a laqueadura, é menos frequente [@Brasil2013]. Uma das mulheres, durante a oficina, relata que tem 4 filhos e não deseja ter outros, porém, após o seu companheiro sugerir a realização da vasectomia, ela não concordou, pois, mesmo sabendo que seria mais simples, o marido poderia querer ter mais filhos, caso eles se separassem.

Outra mulher relatou que seu irmão tem três filhos, cada um com uma mãe diferente, e que, embora passe por problemas com os três por questões jurídicas, ele se recusou a fazer vasectomia quando ela o sugeriu. Segundo ela, o irmão relatava ter medo de “deixar de ser homem” (perder a capacidade de ter ereções). As mulheres afirmaram saber que não há relação entre vasectomia e desempenho sexual, mas relatam ser comum os homens repetirem tal discurso.

A menor incidência de vasectomia está articulada com os padrões de masculinidade, que afastam os homens do planejamento familiar, do processo reprodutivo e dos cuidados em saúde de modo geral, além disso muitos homens acreditam que, após o procedimento perderão, a ereção e o prazer no ato sexual [@Casarin2014]. Dessa forma, apesar do risco cirúrgico, as mulheres continuam se submetendo à laqueadura, mesmo havendo outras alternativas que passem a implicar os homens no processo reprodutivo.

A apresentação do uso do preservativo interno e externo foi uma das atividades que mais mobilizou a participação e curiosidade das mulheres. Muitas não conheciam o uso do preservativo interno e os benefícios deste, nunca tinham visto ou pegado neste material. De forma geral, as mulheres não conheciam o preservativo interno, mas algumas, mais jovens, ouviram falar na escola. A maioria conhecia outros métodos contraceptivos, especialmente o anticoncepcional hormonal. É importante destacar a função dupla dos preservativos, que, além de prevenir a gravidez, também previne IST e HIV.

Durante a distribuição dos preservativos, ao final das oficinas, várias mulheres levaram os dois tipos de preservativo, afirmando que testariam o uso do preservativo interno, uma vez que o manejo deste poderia ser feito por elas. O fato de haver uma maior curiosidade no preservativo interno pode ser relacionado com as discussões sobre maternidade e contracepção, já que as mulheres relataram ser responsabilidade delas se prevenir da gravidez, assim como, ao engravidar, era de seu encargo cuidar dos filhos. Algumas afirmaram que poderiam apresentar dificuldade em utilizar o preservativo interno, porém outras gostaram de ter esta possibilidade, pois, “mesmo quando o homem não quer, já tá lá”, ao que outra relatou “quem tem que gostar (do preservativo interno) sou eu e não meu marido”.

Os métodos contraceptivos possibilitaram uma série de mudanças na vida das mulheres, especialmente para as brancas e economicamente favorecidas, sendo tanto fonte de liberdade sexual, aspecto importante para a luta feminista, como ferramenta de controle moral da reprodução. A hierarquia histórica entre homens e mulheres ainda se faz presentes na família, no trabalho, no espaço que ocupam socialmente, assim, destacamos que os direitos sexuais e reprodutivos não são capazes de garantir sozinhos a equidade de gênero. É importante ainda ressaltar que a forma como as pessoas exercem sua sexualidade, usando ou não métodos contraceptivos não é uma questão apenas do âmbito privado, mas também um interesse do Estado com o controle de natalidade [@Brasil2013].

Os recortes das falas das mulheres assistidas no SUAS, em sua maioria mulheres negras e pobres, visibilizam que, ao longo da história, a propagação de informação de qualidade sobre direitos e saúde sexual e reprodutiva não foi bem-sucedida em reunir mulheres de diferentes origens sociais, não havendo muitas vezes verdadeira preocupação dos movimentos sociais com as mulheres da classe trabalhadora. Além disso, precisamos ser cuidadosas nas nossas ações no campo dos direitos sexuais e reprodutivos, pois, algumas vezes, os argumentos desenvolvidos pelos defensores do planejamento familiar se baseiam em premissas flagrantemente racistas, como o interesse de diminuir a natalidade entre a população mais empobrecida, especialmente a negra. O histórico desse movimento deixa muito a desejar no âmbito da contestação do racismo e da exploração de classe [@davis2016mulheres].

A reprodução não é uma questão apenas individual, mas uma questão de controle populacional, na medida em que demanda investimentos com saúde pública, assistência social e educação pública, por exemplo. Dessa forma, os processos reprodutivos têm sido historicamente controlados, pois tornam-se um problema social que deve ser governado por ações do Estado e políticas públicas [@preciado2008testo].

## Considerações finais

O direito à saúde sexual e reprodutiva envolve uma série de elementos, desde escolha individual, acesso a políticas públicas, justiça social, distribuição de métodos contraceptivos seguros, etc. Essa discussão precisa considerar as diferentes realidades das mulheres, especialmente aquelas em situação de vulnerabilidade social, que são assistidas pelas políticas de assistência social. O acesso informado e igualitário aos direitos sexuais e reprodutivos é um pré-requisito fundamental para a emancipação das mulheres em geral. Uma vez que o direito ao controle de natalidade é, obviamente, uma vantagem para as mulheres de todas as classes e raças.

Dessa forma, faz-se necessário reforçar a importância de atividades de assessoria técnica, bem como as que foram realizadas pela extensão universitária, por possibilitar a reflexão e o acesso à informação, de maneira que valorize os saberes que as mulheres têm sobre o assunto, ampliando seu repertório. É a partir de estratégias lúdicas e participativas que se pode, de forma gradativa, desconstruir os discursos de responsabilização e culpabilização feminina no que diz respeito aos processos reprodutivos ou à interrupção destes, de modo que seja possível assegurar o direito à cidadania.

A promoção de intervenções como essas, que objetivam a transformação da lógica vigente, possibilitam a construção de um caminho para a autonomia e igualdade das mulheres, que foram silenciadas durante grande parte da história. Sendo assim, refletir e perceber essas questões auxilia as mulheres a entender seus direitos e reivindicá-los.
