---
author: 
  - name: Artur Gevásio Lira da Silva
    url: http://lattes.cnpq.br/0489213279118397
    orcid: 0000-0002-0030-6865
    email: artur.gevazio@outlook.com
    affiliations: 
      - name: Faculdade Princesa do Oeste    
  - name: Maria Suely Alves Costa
    url: http://lattes.cnpq.br/2185576054040094
    orcid: 0000-0002-3545-0613
    email: suelycosta@ufc.br
    affiliations: 
      - name: Universidade Federal do Ceará
language: 
  title-block-author-plural: "Autores"
filters:
  - section-bibliographies
bibliography: silva_costa_material_didatico.bib
reference-section-title: Referências
---
# Esquizofrenia e qualidade de vida: construção de materiais didáticos voltados aos profissionais e usuários da Rede de Atenção Psicossocial

## Introdução

Os transtornos do espectro da esquizofrenia são um grupo de transtornos mentais graves, caracterizados pela presença de alucinações e delírios (Barlow & Durand, 2021; Dalgallarrondo, 2019). Além disso, há a presença de sintomas psicomotores, déficits cognitivos, sintomas afetivos e uma miríade de alterações em diversas outras searas do funcionamento cotidiano (Barlow & Durand, 2021). A nomenclatura de espectro é adotada para este grupo de transtornos porque sua natureza essencial ainda não foi esclarecida (Valença & Nardi, 2021\) e pela multiplicidade de características presentes em cada diagnóstico, que irão variar conforme a presença de alguns sintomas e/ou marcador específico, bem como pela intensidade e duração do quadro sintomático (Silva, 2023). Dessa forma, conforme a última versão da Classificação Internacional de Doenças (World Health Organization, 2022), esse grupo é subdividido em Esquizofrenia, Transtorno Esquizoafetivo, Transtorno Esquizotípico, Transtorno psicótico agudo e transiente, Transtorno Delirante, Manifestações sintomáticas de transtornos psicóticos primários, transtorno psicótico induzido por substâncias e outro transtorno psicótico não especificado.

Devido à sua gravidade, os transtornos deste espectro estão intimamente relacionados a diversas outras questões de saúde, como doenças cardíacas (Azad et al., 2016), alguns tipos de lentidão psicomotora (Morrens et al., 2007), transtorno depressivo maior (Cardoso et al., 2007), tentativas de suicídio e comportamento suicida (Bai et al., 2021). Ademais, o grupo também está associado a vários déficits e limitações de cunho social, como dificuldades relativas à interação social, comunitária e amorosa, assim como à empregabilidade e atividades geradoras de renda. Dados do Institute for Health Metrics and Evaluation (2024) apontam que os transtornos deste espectro são uma das principais condições associadas a internações hospitalares em todo o mundo.

Dada a complexidade e cronicidade da condição em alguns casos, pessoas com transtornos deste espectro apresentam diversas limitações e dificuldades em diferentes áreas da sua vida. Uma das principais áreas afetadas é a qualidade de vida (QV), que se refere às percepções individuais sobre seu contexto cultural e sistemas de valores, assim como em relação aos seus objetivos, expectativas, padrões e preocupações (The WHOQOL Group, 1995). Nesse sentido, sujeitos com a condição tendem a apresentar níveis menores de QV em relação a outras pessoas com ou sem transtornos mentais (Dong et al., 2019).

A QV é uma variável associada a melhoras em várias condições de saúde, sendo um dos objetivos principais de intervenções (Awad & Voruganti, 2012), relacionada à recuperação funcional, bem-estar e outros aspectos. Nesse sentido, devido à cronicidade da condição em alguns casos, o manejo terapêutico do espectro vai muito além da remissão de sintomas, baseando-se em um amplo processo de cuidado fundamentado no paradigma da recuperação funcional e inserção comunitária (Vergunst et al., 2017). A partir desta lógica, as intervenções se pautam no ideário de produzir qualidade de vida, a partir de ações em diferentes frentes da vida do sujeito, em um modelo de cuidado ampliado.

A Rede de Atenção Psicossocial (RAPS) é o paradigma adotado como política pública para cuidado em saúde mental no Brasil, sendo os Centros de Atenção Psicossocial (CAPS) um dos seus principais representantes. Os CAPS têm o intuito de fornecer apoio em saúde mental para pessoas com transtornos mentais moderados a graves (Brasil, 2024). A estratégia de trabalho adotada nos CAPS se baseia no ideário da inserção social, fortalecimento de vínculos com a comunidade e no oferecimento de estratégias de cuidado de caráter multiprofissional. Nesses espaços, são oferecidas diversas atividades terapêuticas e acolhimento por uma equipe interdisciplinar (Ribeiro, 2004), visando trabalhar de formas diversas a produção de saúde em uma perspectiva geral e pautada na construção da cidadania.

A rotina diária ao lidar com políticas públicas é marcada por incertezas, dificuldades e limitações no que diz respeito à abrangência do serviço, assim como nos aspectos técnicos relacionados a como lidar com cada tipo de demanda. O cuidado em relação aos transtornos mentais graves, como os do espectro da esquizofrenia, exige uma habilidade profissional refinada e constante atualização. Dessa forma, este manuscrito tem o intuito de apresentar o processo de construção de dois materiais didáticos voltados ao público usuário da RAPS, especificamente os profissionais atuantes com pessoas com transtornos do espectro da esquizofrenia e os usuários do serviço.

Assim, a pesquisa ora relatada teve como objetivo elaborar dois livros eletrônicos. O primeiro com informações referentes à avaliação e intervenção na qualidade de vida de pacientes com transtornos do espectro da esquizofrenia, produzindo um material técnico que abrangesse intervenções voltadas para a avaliação e o aumento da qualidade de vida desses pacientes, direcionado aos profissionais atuantes na RAPS. O segundo livro, com cunho informativo, tinha o intuito de divulgar e apresentar informações sobre a condição para usuários e o público geral, de modo a trabalhar o estigma negativo acerca do espectro, combater preconceitos e servir como material de divulgação científica. Este capítulo de livro visa apresentar o percurso de pesquisa percorrido na realização dos livros propostos.

## Método

### Participantes

Os participantes desta pesquisa foram profissionais de nível superior atuantes em um Centro de Atenção Psicossocial do Município de Tamboril, Ceará, maiores de idade e que possuíssem no mínimo seis meses de atuação no equipamento e experiência no lidar com usuários com transtornos do espectro da esquizofrenia.

### Procedimentos

Tratou-se de uma pesquisa de natureza qualitativa, de abordagem descritiva, utilizando o método de pesquisa-ação, visto que buscava identificar problemáticas existentes em um campo e, a partir dos seus achados, propor soluções (Thiollent, 1986). Desta forma, a pesquisa foi estruturada em três etapas. A etapa inicial consistiu na elaboração de duas revisões de literatura. A primeira foi uma revisão sistemática da literatura científica existente acerca de intervenções voltadas ao incremento da qualidade de vida em pessoas com esquizofrenia. A segunda revisão foi uma revisão de escopo, com o intuito de mapear os instrumentos psicométricos validados e adaptados ao Brasil, com foco na avaliação dos níveis de qualidade de vida na esquizofrenia. A etapa seguinte consistiu na aplicação de entrevistas semiestruturadas com profissionais de nível superior atuantes em um Centro de Atenção Psicossocial do Município de Tamboril. Esta teve o intuito de conhecer a prática profissional desses atores frente à esquizofrenia, suas concepções acerca do serviço e outros aspectos importantes relacionados ao processo de cuidado na condição. Posteriormente, os dados obtidos com as revisões foram apresentados aos profissionais para selecionar as intervenções e instrumentos mais adequados ao contexto, visando produzir as versões iniciais dos ebooks.

### Coleta de dados

Acerca da etapa relativa à entrevista, as falas dos profissionais foram gravadas utilizando um smartphone e posteriormente transcritas, para que se pudesse realizar as análises necessárias. Nos encontros de grupos focais com os profissionais, os dados foram coletados de forma manual, a partir de diários de campo.

No que diz respeito às revisões de literatura, a primeira revisão (sistemática) foi operacionalizada através da utilização do acrônimo PICO (Paciente, Intervenção, Comparação e Desfecho) para revisões de literatura, com base na seguinte pergunta de partida: Em relação a pacientes com algum transtorno do espectro das esquizofrenias (População), quais são as intervenções (Intervenção) que estão sendo utilizadas com foco na melhora da qualidade de vida (Desfecho)?

Dessa forma, realizou-se buscas nas bases de dados Scientific Electronic Library Online \- SciELO, MEDLINE, Literatura Latino-americana e do Caribe em Ciências da Saúde – LILACS (acesso através da plataforma BVS-Salud) e PUBMED, no período de abril a maio de 2022, através da combinação dos descritores na língua inglesa: “quality of life”, “QVRS”, “schizophrenia” e “psychosis” e demais variações. Os descritores foram selecionados a partir de consulta na plataforma dos Descritores em Ciências da Saúde (DeCS/MeSH).

Os critérios de inclusão adotados foram artigos empíricos (ensaios clínicos com e sem randomização) publicados em periódicos científicos revisados por pares na língua portuguesa e inglesa nos últimos cinco anos (2017 a 2022), que apresentassem intervenções focadas em aspectos da esquizofrenia e com desfechos primários e secundários relacionados ao aumento da qualidade de vida. Os critérios de exclusão adotados foram artigos publicados em outros idiomas, sem acesso ao texto completo, fora do período de publicação delineado, protocolos de pesquisa e demais tipos de publicações, como resumos expandidos, capítulos de livros, revisões de literatura (sistemática, narrativa e metanálise), artigos duplicados nas bases, anais de eventos e trabalhos de conclusão de curso (dissertações, teses e monografias).

Acerca da segunda revisão (escopo), esta também foi operacionalizada a partir da pergunta de pesquisa: “Quais são os instrumentos psicométricos validados e disponíveis no Brasil, para a avaliação da qualidade de vida de pacientes com transtornos do espectro da esquizofrenia?”. Houve a estruturação do processo de busca, no qual utilizou-se como base a variação PCCS do acrônimo PICO para revisões de literatura, no qual P (População) – Pacientes com transtornos do espectro da esquizofrenia; C (conceito) – Qualidade de vida, C (contexto) – Brasil; S (delineamento do estudo) – Instrumentos psicométricos.

A busca foi realizada no período de março a maio do ano de 2023, nas bases de dados da Scientific Electronic Online Library – SCIELO, Literatura Latino-Americana e do Caribe em Ciências da Saúde – LILACS, Index Psicologia Periódicos Científicos e Medical Literature Analysis and Retrieval System Online – MEDLINE (acessos via plataforma BVS-Salud), as quais indexam pesquisas diversas no campo da saúde e da psicologia. Para a seleção dos descritores, realizou-se uma consulta na base dos Descritores em Ciência da Saúde – DECS, com vistas a obter o máximo de variações disponíveis de cada termo de busca. Na base SciELO, foi utilizada a combinação “esquizofrenia AND (qualidade de vida) AND escala OR teste OR instrumento”. Já nas bases MEDLINE, LILACS e Index-PSI se adotou a combinação “esquizofrenia OR (espectro da esquizofrenia) OR psicose AND (qualidade de vida) AND escala OR teste OR instrumento”.

Em cada base, houve a utilização de filtros para restringir e refinar o processo de busca. Não houve restrição temporal quanto ao ano de publicação das pesquisas. Quanto ao idioma, houve restrição à língua portuguesa e inglesa. Utilizou-se os seguintes critérios de inclusão: (1) pesquisas executadas no Brasil; (2) pesquisas que tivessem sido feitas com amostras de pacientes com algum transtorno do espectro da esquizofrenia e voltadas à avaliação da qualidade de vida desse público; (3) pesquisas de natureza quantitativa que utilizassem instrumentos psicométricos para a avaliação desse construto. As pesquisas que não se adequassem a esses critérios foram excluídas do corpus de análise. Especificamente, estudos qualitativos, revisões de literatura (sistemática com e sem metanálise, integrativa e narrativa), resenhas e pesquisas eminentemente teóricas. Duplicatas e demais tipos de publicações acadêmicas, como teses, dissertações, resumos e afins, também foram excluídas do escopo da pesquisa.

### Análise de dados

No processo de estudo de revisão de literatura, foram considerados os títulos e os resumos dos artigos identificados. A partir do processo sistemático de busca, revisão e análise de publicações nacionais e internacionais, foram selecionados artigos para a leitura integral de seu conteúdo e se extraiu informações relevantes aos objetivos da pesquisa. As informações de interesse foram: instrumentos utilizados para avaliar a qualidade de vida de usuários com esquizofrenia; as características psicométricas dos instrumentos utilizados; as intervenções utilizadas para lidar com a sintomática do transtorno e incrementar a qualidade de vida; o delineamento adotado no estudo; a qualidade metodológica; a viabilidade de aplicação das intervenções nas políticas públicas; e o estado da arte sobre a temática.

As informações obtidas por meio das entrevistas foram analisadas através do método da Análise de Conteúdo de Bardin (2016), no qual se obteve resultados divididos em eixos, os quais versavam acerca da: dificuldade de adesão ao tratamento do usuário; a necessidade de aproximação da família ao serviço; a necessidade de expansão do serviço; o papel dos grupos como ferramenta de cuidado para o usuário e sua família; o preconceito acerca da condição; e a importância do acolhimento.

Além disso, nos encontros de grupos focais com os profissionais, apresentaram-se as versões preliminares dos ebooks. Nestes momentos, coletaram-se sugestões, críticas, opiniões e demais informações a serem incluídas, que foram sugeridas pela equipe técnica. Estas informações foram incluídas no escopo da construção das cartilhas e serviram como estratégia de construção do conhecimento coletivo junto aos atores sociais envolvidos.

## Resultados e discussão

A partir de cada eixo obtido com as falas dos profissionais, houve a construção de cada seção dos ebooks. O intuito foi construir o material com base nas vivências, experiências e reais necessidades desses profissionais no lidar com a condição. Dessa forma, a versão profissional do ebook foi dividida nas seguintes seções: Apresentação; Histórico do conceito de esquizofrenia; O que é o espectro da esquizofrenia?; Qualidade de vida e o espectro da esquizofrenia; Acolhimento ao usuário com o espectro; Apoio e cuidado aos cuidadores e/ou familiares; Grupos – Subdividida em Temáticas para discussão de grupo e terapia de grupo baseada em mindfulness; Estratégias de cuidado – Subdivida em Atividades comunitárias e de inclusão social, Amizade voluntária (Befriending volunteer); Integração entre o manejo farmacológico e psicossocial, Atividades artísticas, Pintura e artes plásticas, Atividades físicas, Exercícios aeróbicos e Treinos de força; Considerações finais; Referências; Escalas para a avaliação da qualidade de vida.

Já a versão voltada ao público em geral foi dividida na seguinte estrutura: Apresentação; O que é a esquizofrenia?; Onde procurar apoio e tratamento para alguém que tenha esquizofrenia – Subdividida em Terapêuticas medicamentosas, psicoterapia, intervenções psicossociais e comunitárias e exercícios físicos; Como ajudar alguém com esquizofrenia? – Subdividida em episódios de crise, manutenção do tratamento, apoio social e fortalecimento de vínculos; Considerações finais; Referências usadas, dicas de vídeos e leituras; Obras na mídia que tratam da esquizofrenia.

O ebook profissional possui uma linguagem técnica, embasada na literatura mais recente na área acerca da psicopatologia da esquizofrenia e aspectos relacionados ao seu cuidado. Além disso, foram usadas como referências os resultados obtidos nas revisões de literatura. A revisão sistemática forneceu as diretrizes de intervenção baseadas em evidências mais adequadas ao contexto e que estivessem alinhadas aos eixos obtidos através da análise de conteúdo. A revisão de escopo forneceu as escalas a serem incluídas no material. No entanto, foram obtidas duas escalas na busca: a Quality of Life Scale in Schizophrenia – QLS-BR (Cardoso et al., 2003\) e a WHOQOL-BREF (Fleck et al., 2000). Dessa forma, os dois instrumentos foram apresentados aos profissionais em mais um encontro grupal, e houve a seleção da WHOQOL-BREF como o instrumento oficial, devido à sua facilidade de aplicação e possibilidade de correção informatizada. O intuito da escala era fornecer um material de avaliação complementar, com o intuito de verificar o impacto e as melhorias trazidas pelo processo de cuidado elaborado pela equipe.

O ebook voltado aos usuários e público em geral possui uma linguagem mais cotidiana e simplificada, visto que possui a intenção de fornecer informações acessíveis e claras. Assim, possui um caráter de divulgação científica, também tendo sido embasado na literatura mais recente na área obtida com a revisão sistemática. Assim, este versa sobre aspectos gerais acerca do espectro, como as características, sinais, sintomas, possibilidades de cuidado e como lidar em situações de crise. Ao final do material, também foram listadas algumas obras midiáticas (documentários, livros e jogos) que abordam o espectro de forma adequada, sem reproduzir estigmas e preconceitos.

## Considerações finais

Esta pesquisa teve como objetivo elaborar um material didático direcionado para profissionais atuantes na RAPS, na forma de um ebook sobre aspectos psicopatológicos, de acolhimento e de intervenção voltados ao incremento da qualidade de vida de pessoas com transtornos do espectro da esquizofrenia. Além disso, também objetivou elaborar outra versão do material, mas voltado aos usuários com transtornos do espectro da esquizofrenia da RAPS e o público em geral. Esta segunda versão tinha o intuito de ser um material informativo acerca de aspectos gerais sobre a condição, estratégias de cuidado e formas de acesso a informações confiáveis sobre esse grupo de transtornos.

O caráter inovador destas produções reside no seu caráter pautado em evidências e por ter sido construído com base nas necessidades, problemáticas e demais desafios enfrentados pelos profissionais atuantes na RAPS, os quais tendem a se repetir em vários contextos. Além disso, também se pautou em ser uma construção pautada nas reais necessidades do território, visto que as diversas variáveis sociais, históricas, econômicas e afins, que atravessam a sua gênese, também se expressam nas falas desses atores. O ebook final foi apresentado e compartilhado à prefeitura do município e aos profissionais do serviço e busca vias de divulgação mais amplas.

Os transtornos do espectro da esquizofrenia guardam uma miríade de questões associadas ao seu tratamento e compreensão, assim como inúmeros preconceitos, temores e vieses negativos. Nesse sentido, o cuidado que deve ser fornecido às pessoas que possuem a condição, assim como a seus cuidadores, deve ter um caráter humanizador e desmistificador acima de tudo, devendo ver o sujeito para além da sua condição e seus sintomas, mas sim como um ser humano que precisa de acolhimento e atenção. Assim, pautar-se na ciência é a melhor forma disponível para enfrentarmos com efetividade e segurança todos estes desafios.